### ISSUE TITLE
First Contribution by Ameerah Kabir.

### ISSUE THREAD

**Issue by AmeerahKabir** [numfocus/outreachy-contributions-2023#10]
**Name**: Ameerah Kabir (she/her)
**Project**: OpenJS Foundation (https://openjsf.org/)
**Link to The Open JS Foundation governance model:** https://openjsf.org/about/governance/

The governance model of the OpenJS Foundation is overseen by the Board of Directors. The Board is responsible for setting high-level technical policy through its mission and vision statements, bylaws, and outlining the Foundation's initiatives, technical vision, and direction. The Board also appoints the Executive Director (ED) to run the organization's day-to-day operations, who is tasked with implementing the strategic initiatives set out by the Board, hiring staff and contractors within the current budget, and partnering with other organizations to achieve the Foundation's goals. The ED reports to the Chairperson of the Board, with additional oversight and input from the full Board.

Each project within the OpenJS Foundation has its own governance structure, tailored to the needs of its respective community. The Foundation provides high-level requirements to ensure each project operates sustainably and equitably. Project maintainers have the flexibility to manage day-to-day operations as they see fit. 

**There are three major project roles within the OpenJS Foundation:** 

Maintainer,
Contributor, 
End User. 

 There are various committees which make up the executive council members in charge of various operations, such as the Officers Committee, Governance Committee, Finance Committee, and Program Committee. 

The OpenJS Foundation's decision-making process involves voting by eligible community members who are considered active in the community. To be eligible to vote, individuals must have completed an Instructor or Trainer certification within the past two years and have taught at least one OpenJS Foundation workshop, or have participated in a committee as a mentor or maintainer in the past year. The Executive Director is exempted from voting. A majority of votes by the Board of Directors is required to approve an appointment or removal of any party. The OpenJS Foundation strives for transparency in its activities and decision-making processes.

**How easy or difficult was it to find and understand the governance model**?

For my first time it was pretty easy, a section in the about had all the information about the governance model, I got a little confused by it was from my own end 😂, overall locating the governance model was easy.

**Comment by AmeerahKabir** [comment]
Hi @arliss-NF ,
I would appreciate your thoughts on this

**Comment by Chimnwendum** [comment]
Hello @AmeerahKabir, your issue is closed, you need to reopen it so it will be more visible to our mentors. 

Also, have you seen the update in the slack channel?

**Comment by AmeerahKabir** [comment]
Oh, I would reopen it, closed it while I analyze the governance model, plan
on reopening to make some changes.

Thank youu, yes I saw it, picked out a project already. Yet to open an
issue tho

**Comment by arliss-NF** [comment]
@AmeerahKabir - your first contribution is great, exactly what we were looking for.  Your responsiveness to feedback from a fellow contributor was perfect!
