### ISSUE TITLE
Second Contribution by Tanishka Goel

### ISSUE THREAD

**Issue by tg-100** [numfocus/outreachy-contributions-2023#101]
**Name:** Tanishka Goel
**Projects analyzed:** [signac](https://signac.io/) | [FluxML](https://fluxml.ai/)
**Governance Model Links:** Project 1 [signac governance model](https://signac.io/governance/) | Project 2 [FluxML governance model](https://fluxml.ai/governance/)

### Governance Model Overview of FluxML
The FluxML governance model follows the approach of contribution-based merit which is not solely based on the code contributions and rather has a holistic view of contributions to the community in both quality and quantity. It divides its roles between ***Project Contributors, Steering Council, Advisory Committee, and Community***. The main features of their model are as follows:
- _Consensus-based and values majority vote_
- _Strongly believes in inclusivity and diversity_
- _Simple yet effective rules for the community_

### Governance Model Overview of signac
The governance model of signac follows a Meritocratic Governance Model and divides its major roles between ***Users** (Committers, Contributors, Project Maintainers, and Administrators)* and ***Project Managers** (Triage and Community Managers)*. It has the following features:
- _Consensus-based and values majority vote_
- _Inclusive_
- _Open to all_

### Similarities:
- Both models are open-source, community-based, and inclusive of people from all backgrounds.
- The decision-making process involves majority voting and is based on the consensus of all.
- Each of the models is thorough in defining project roles and responsibilities.
- Commitment to the project, alignment with project goals, and quality contributions to the community are valued.
- They place importance on the growth and progress of the project.

### Differences:
- Project Roles:
  - The FluxML model has an Advisory Committee in addition to Project Contributors and Council. 
  - The signac model has multiple divisions under the User and Manager roles and does not have an Advisory Committee.
- Decision-making:
  - FluxML model is solely based on clear majority voting.
  - signac model has a 2/3rd voting system for the Project Maintainer role.
- Privileges:
  - FluxML gives no privileges to the Steering Council except for decision-making power for the project.
  - Project Maintainers have a higher position than Committers and members and can accept or reject them in the signac model.
- Merit:
  - FluxML has a holistic view of merit which considers peer participation, different viewpoints, outreach, etc. apart from code contributions while considering members of the council. Nominations are done by the Council.
  - Only project contributions and a strong understanding of project strategy are enough for signac. Self-nomination or people with the existing role can nominate for a position.
- Special Guidelines/Roles:
  - Fiscal decisions are taken by the Committee in the FluxML model. There is also a special guideline for when a Conflict of Interest arises.
  - No role is explicitly specified for making financial decisions and there are no guidelines to resolve Conflicts of Interest in the signac model.

## Which Model do I consider better and Why?
I consider the FluxML model to be better than the signac model because of the following reasons:
1. The model is simple to understand and apply without any complicated rules for nomination or hierarchy.
2. It implements the concept of inclusivity and diversity in the truest form by having an overall approach and not having any set quantitative merit benchmarks which could play a role in the selection. When considering members, one's participation in the mailing list/chat group, outreach and education, code contributions and code reviews, and community building.
3. Despite the rules being simple, the model is effective in thorough with the responsibility for the contributors, Council and Committee members, and the community. There is flexibility for being a part of the Council with the availability of a grace period after inactivity and there is no ejection from the community by only a few people being in charge for doing so.
4. There is a special Advisory Committee which I believe is important for the proper functioning of projects and taking financial decisions. Guidelines for Conflict of Interest are also taken into consideration which could result from people with various life backgrounds.
5. There is no unnecessary role and the project management is simpler with all the users being allowed to contribute and only the members of the Council delegating the project - from raising issues to merging contributions and working towards the growth of the project.

**Comment by tg-100** [comment]
@arliss-NF I would be glad to receive any modifications/instructions you have for me. :)
Thank you!

**Comment by arliss-NF** [comment]
@tg-100 - great analysis.  it was very easy to read.  Very concise, so it was a quick read which is appreciated when there are over 57 projects to be analyzed.  Your arguments are solid and exactly what we wanted to see. Well done!

**Comment by tg-100** [comment]
@arliss-NF I am really grateful to you for giving your time and giving me such personalized and encouraging feedback. Thanks so much!
