### ISSUE TITLE
Second Contribution by Victory Brown

### ISSUE THREAD

**Issue by Victorybrown** [numfocus/outreachy-contributions-2023#102]
**Name:** Victory Brown
**Project 1:** [ESLint](https://eslint.org/docs/latest/contribute/governance)
**Project 2:** [OpenJS Foundation](https://openjsf.org/about/governance/)
**Relevant Links:** [Understanding open source governance models](https://www.redhat.com/en/blog/understanding-open-source-governance-models)

### Analysis

The Open Js Foundation is a nonprofit organisation that is home to several other projects. The openJS Foundation uses the Self Appointing or Board governance model. It is led by a board of directors, who appoint an executive director to handle the day-to-day activities of the foundation. Other projects under the JS foundation have the flexibility to determine their own governance model, but overall the foundation is headed by the Board of Directors.

ESLint is a project under the OpenJs foundation. As I mentioned earlier, the Open JS is led by a board, but other projects under the umbrella can choose their governance model. The ESLint uses an electoral governance method because of the nature of the project. It allows all contributors to make suggestions and give their opinions, but the final decision is made by the technical steering committee. 

The executive director of JS foundation is appointed by the board, and other board members are appointed by Platinum members. The E.D. has the right to hire according to the budget of the foundation. They report directly to the chairperson of the Board. 

The Board governance model is often used by projects without a sponsoring foundation. ESLint on the other hand relies on sponsorships and other forms of donations. ESLint is governed by the core team members or technical steering committee, who is responsible for making decisions related to the project's direction, governance, and technical implementation. New members can only be added to the TSC through the standard TSC motion and can only be 5 at a time. 

Decision-making in ESLint is based on a consensus model. Contributors are recognised and rewarded based on the quality and quantity of their contributions. The project has a well-defined set of guidelines and procedures for contributing, reporting issues, and making decisions.

### Similarities:

The OpenJS Foundation and ESLint are open-source projects that rely on contributions from a community of developers.
Both projects rely on a consensus-based decision-making process, where decisions are made through discussion and agreement among members involved.

### Differences:

The OpenJS Foundation is a larger organisation that supports multiple projects, while ESLint is a single project with a smaller team of core contributors.
The OpenJS Foundation has a more formal governance structure, with a board of directors and a number of working groups and technical committees, while ESLint governance structure based on a core team of contributors.

### My opinion on both Governance models.
In my opinion both models are relevant to the structure of the project and community, the disadvantage of the board model is that it can hinder other community members from participating in leadership activities, while the ESLint gives committed contributors a chance to engage in leadership activities and even move roles through nominations.

**Comment by Victorybrown** [comment]
Hello @arliss-NF . I have made my second contribution.

**Comment by arliss-NF** [comment]
@Victorybrown - excellent work.  Agree with your conclusions.  The governance model needs to fit the project, and it's community.  Great to see you found the article on governance models, it's useful for understanding.
NOTE:  The links in this contribution worked for ESLint. Please copy the link to your first contribution.

**Comment by Victorybrown** [comment]
Thank you @arliss-NF The link has been updated. Thank you for taking time to go through this.
