### ISSUE TITLE
First Contribution by Abhishek bhardwaj

### ISSUE THREAD

**Issue by Abhishek02bhardwaj** [numfocus/outreachy-contributions-2023#11]
- Name - Abhishek Bhardwaj
- Project Assigned - [InterpretML](https://interpret.ml/)
- [Link to the Project Governance Model](https://github.com/interpretml/interpret/blob/develop/GOVERNANCE.md)
- **Governance Model**
- Introduction - InterpretML is a freely accessible software package that integrates the latest and most advanced techniques for interpreting machine learning models in one place. By using this package, we get the ability to develop models that are transparent and can be easily explained, as well as analyze complex blackbox systems. With InterpretML, we can gain insight into how our model behaves overall, or delve into the reasoning behind specific predictions.
- Project Roles - The following roles may be present in each Project, and the Project may decide to adopt additional roles and document them accordingly.

1.1. Maintainers 
1.2. Contributors 
 
- Decision making - The following are the procedures for decision-making in Projects:

2.1. Consensus-Based Decision Making: Decisions are made by consensus among the Maintainers. Although it is preferable for all Maintainers to explicitly agree, it is not necessary for consensus. Rather, the Maintainers will evaluate consensus based on several factors, including the dominant view of the Contributors and the nature of the support and objections, in good faith. The Maintainers will document evidence of consensus in accordance with the established criteria.

2.2. Appeal Process: If a decision is disputed, it may be appealed by raising an issue. The Maintainers will review the appeal in good faith and respond in writing within a reasonable time. If the appeal is rejected by the Maintainers, it may be further reviewed by the TSC, who will also provide a written response within a reasonable period.

> The Governance Model of InterpretML was easy to find as it was available in the repository of the InterpretML. Talking about the understanding of the InterpretML's Governance Model, it was easy to comprehend and understand as it is really well written, compact and understandable. While reading about the Governance Model I also came across the work ethics of the project which are very good reasonable. This was all. I hope this analysis helps in understanding better about the Governance Model of InterpretML. Any views or suggestion for improvement are welcome.

**Comment by Abhishek02bhardwaj** [comment]
@arliss-NF, I wanted to reach out to ask if you would be willing to review my recent work reviewing the governance model of InterpretML and share your thoughts on it. As a mentor, your guidance and feedback would be invaluable in helping me improve my skills and abilities.
If it's not too much trouble, I would appreciate any constructive criticism or suggestions you may have. I understand that you likely have many other commitments, so please let me know if and when you would be able to provide feedback.
Thank you for your time and consideration. I look forward to hearing from you.
Best regards.

**Comment by arliss-NF** [comment]
Hello @Abhishek02bhardwaj - great first contribution.  We appreciate the detailed coverage of a model that has been written very concisely.  Also, it was good to see that while you were focused on the governance model, you investigated other areas of the project and documented them.  Good luck with contribution 2.
