### ISSUE TITLE
Third Contribution by Bhaswati Roy

### ISSUE THREAD

**Issue by BhaswatiRoy** [numfocus/outreachy-contributions-2023#112]
Work Sample Links:

1. [Superfast Differential Privacy](https://blog.openmined.org/superfast-differential-privacy/)
2. [Differential Privacy Advanced 1 - Strengths & Weaknesses](https://blog.openmined.org/differential-privacy-advances-part-1-strengths-weaknesses/) 
3. [Edge Computing vs Cloud Computing](https://bhaswatiroy.hashnode.dev/edge-computing-vs-cloud-computing)
4. [Measuring Open Source Community Health with the CHAOSS Project](https://bhaswatiroy.hashnode.dev/measuring-open-source-community-health-with-the-chaoss-project)
5. [Data Visualization Series with Matplotlib+Seaborn](https://cppsecrets.com/user/index.php?id=articles&uid=14456) 
6. [Documentation on supporting AsyncAPI Initiative](https://github.com/asyncapi/community/blob/master/PROJECT_FINANCE.md)
7. [Style Guide on Inclusive Language](https://github.com/BhaswatiRoy/website/blob/style-docs/pages/docs/community/styleguide/inclusive-language.md)
8. [MOM of Moja Global Community Meeting](https://github.com/moja-global/About_moja_global/blob/master/working-groups/community_meeting/28-01-2023.md)

Additional Links:

1. [Medium Profile](https://medium.com/@BhaswatiRoy)

**Comment by BhaswatiRoy** [comment]
The 2 HashNode articles were uploaded today but were written a long time ago, attaching the google docs link of the same as a reference, where the history of comments can be checked -

1. Measuring Open Source Community Health with the CHAOSS Project https://docs.google.com/document/d/1gv7mU2BYW2T06lzUi736SRixKshpEOftOoEH_7g-2nw/edit

2. Edge Computing vs Cloud Computing -
https://docs.google.com/document/d/1kEt6d5hM-qfjRilw_guHlSTZB9ehjgYTQjEotq2CQHY/edit

The articles are added to Hashnode for better readability.

**Comment by BhaswatiRoy** [comment]
cc: @arliss-NF 
I have added all of my past work samples

**Comment by arliss-NF** [comment]
Thank you very much for completing your third contribution.  We have really enjoyed reviewing your written submissions. I hope you've enjoyed the experience.

**Comment by arliss-NF** [comment]
@BhaswatiRoy - you have a wide selection of work.  I really enjoyed reading all the areas that you have engaged in.  The CHAOSS project is one of my passions, and seeing it on your list is great.

**Comment by BhaswatiRoy** [comment]
> @BhaswatiRoy - you have a wide selection of work. I really enjoyed reading all the areas that you have engaged in. The CHAOSS project is one of my passions, and seeing it on your list is great.

thank you for your feedback
