### ISSUE TITLE
Third Contribution by Phebe Radiant Momoh.

### ISSUE THREAD

**Issue by pheberadiant** [numfocus/outreachy-contributions-2023#113]
**Product**- **iHELP**. 

iHELP is an online mental health platform created to help young individuals dealing with mental health challenges like anxiety, work related stress, peer pressure, etc. 

The product case study linked below describes:
- the product idea, 
- basic assumptions my team members and I sent out to test, 
- results from user research, 
- various prototypes of the product, 
- and so many more. 

[Product Case Study- iHELP](https://medium.com/@phebe.radiant/product-case-study-ihelp-5fcb178cef90)

Second write up [Knowledge, Attitude, and Practice of Telerehabilitation in Stroke Management Among Physiotherapists in Rivers State, Nigeria](https://drive.google.com/file/d/1J4yq5Vl1YioxrLPygEE7K4aP3qFY8qFk/view?usp=drivesdk)

**Comment by pheberadiant** [comment]
cc: @arliss-NF @SavannahSimons 
Here is my submission for the third contribution. Thank you for your time.

**Comment by arliss-NF** [comment]
Thank you very much for completing your third contribution.  We have really enjoyed reviewing your written submissions. I hope you've enjoyed the experience.

**Comment by pheberadiant** [comment]
Hello @arliss-NF 
This was definitely a learning experience for. Thank you once again🙏.
