### ISSUE TITLE
Third Contribution by Chinenye Ibegbunam

### ISSUE THREAD

**Issue by chinenye3** [numfocus/outreachy-contributions-2023#114]
Here are links to some of my writing samples:

- [https://medium.com/@cesar_zowa/what-is-link-tracking-why-is-it-important-6252e619f1c4](url)

- [https://medium.com/@cesar_zowa/tracking-url-how-does-it-work-8499adfa54a5](url)

- [https://medium.com/@cesar_zowa/grow-your-online-business-in-2022-with-these-6-best-link-tracking-software-5aafc5d5c452](url)

- [https://www.linkedin.com/pulse/missing-link-content-marketing-chinenye-ibegbunam/?trackingId=B%2BZlZmqrQ7OqsWSG2nUi5g%3D%3D](url)

- [https://www.linkedin.com/posts/chinenye-ibegbunam_community-web3-communitybuilding-activity-6960230013270917120-BSjn?utm_source=share&utm_medium=member_desktop](url)

- [https://www.linkedin.com/pulse/your-key-success-community-management-chinenye-ibegbunam/
](url)

**Comment by chinenye3** [comment]
cc: @arliss-NF  @SavannahSimons 

Here's my submission for task 3, kindly review. Thank you for your time.

**Comment by arliss-NF** [comment]
Thank you very much for completing your third contribution.  We have really enjoyed reviewing your written submissions. I hope you've enjoyed the experience.

**Comment by chinenye3** [comment]
Thank you @arliss-NF for the feedback. I look forward to doing more work with you in the future
