### ISSUE TITLE
Third Contribution by Esther Jolomi

### ISSUE THREAD

**Issue by jolomi942** [numfocus/outreachy-contributions-2023#115]
LinkedIn Post on my write-ups:

Topics: 
Mental health and Awareness: https://www.linkedin.com/posts/esther-jolomi_kindness-respect-people-activity-6871013250272690176-mRYf?utm_source=share&utm_medium=member_desktop

Words of encouragement to parents on raising both girl and boy children equally: https://www.linkedin.com/posts/esther-jolomi_genderequality-gendergap-girlseducation-activity-6890258868812029952-6E3W?utm_source=share&utm_medium=member_desktop

**Comment by jolomi942** [comment]
@arliss-NF 
@SavannahSimons 
Kindly take a look at my third contribution. Many thanks.

**Comment by arliss-NF** [comment]
Thank you very much for completing your third contribution.  We have really enjoyed reviewing your written submissions. I hope you've enjoyed the experience.

**Comment by jolomi942** [comment]
It has been eye-opening for me to choose this project and the privilege to collaborate. Thanks for your guidance all through @arliss-NF. I look forward to the next phase with NumFocus.
