### ISSUE TITLE
Third contribution by Oluwaseun Odunayo

### ISSUE THREAD

**Issue by oluwaseun-tech** [numfocus/outreachy-contributions-2023#116]
The research writing was done on "orphanhood policy in Nigeria"
Link: https://docs.google.com/document/d/1K6sirUrWn9_smk_0rnsWSoOAAmb9OKUWKgbkAXYhhbo/edit?usp=sharing

**Comment by oluwaseun-tech** [comment]
cc @arliss-NF 
cc @SavannahSimons 
Please take a look. Thank you!

**Comment by maryamgbemisola** [comment]
@oluwaseun-tech . I suggest you give a viewer permission to the link provided . So that mentor can view your work easily.

**Comment by oluwaseun-tech** [comment]
@maryamgbemisola Thank you for the observation. I will do just that

**Comment by arliss-NF** [comment]
Thank you very much for completing your third contribution.  We have really enjoyed reviewing your written submissions. I hope you've enjoyed the experience.

**Comment by oluwaseun-tech** [comment]
Thank you so much
