### ISSUE TITLE
Third Contribution by Ufuoma Ejite

### ISSUE THREAD

**Issue by joy-commits** [numfocus/outreachy-contributions-2023#117]
## Name: Ufuoma Ejite

[Here is a Google Drive containing some of my writing samples](https://drive.google.com/drive/folders/1OBXhktAUYpOIun2z0gNlZ0mMukzbEhAg?usp=sharing).

However, my most recent publication is [here](https://python.plainenglish.io/how-to-extract-tweets-on-a-hashtag-from-twitter-api-using-tweepy-34d697ecba21) on [web scraping](https://python.plainenglish.io/how-to-extract-tweets-on-a-hashtag-from-twitter-api-using-tweepy-34d697ecba21).

**Comment by joy-commits** [comment]
@arliss-NF @SavannahSimons 
Hello, I've made my third contribution.
I'd appreciate your kind review.
Thank you.

**Comment by arliss-NF** [comment]
Thank you very much for completing your third contribution.  We have really enjoyed reviewing your written submissions. I hope you've enjoyed the experience.

**Comment by joy-commits** [comment]
Thank you very much @arliss-NF 
I've enjoyed the contribution experience so far
