### ISSUE TITLE
Third Contribution by Maryam Gbemisola 

### ISSUE THREAD

**Issue by maryamgbemisola** [numfocus/outreachy-contributions-2023#118]
Kindly check out my 

**1 . [My Portfolio Website](https://sites.google.com/view/maryam-gbemisola)**

**Comment by maryamgbemisola** [comment]
@arliss-NF 
@SavannahSimons . 

Kindly check out my Past Works

**Comment by arliss-NF** [comment]
Thank you very much for completing your third contribution.  We have really enjoyed reviewing your written submissions. I hope you've enjoyed the experience.

**Comment by maryamgbemisola** [comment]
Thank you ma'am. The experience was an insightful one and has made me push myself harder. 

Looking forward to the review of the other contributions
