### ISSUE TITLE
First Contribution by Riya Sharma

### ISSUE THREAD

**Issue by Riya2909** [numfocus/outreachy-contributions-2023#12]
**Name:** Riya Sharma 
**Project:** ESLint (https://eslint.org/)
**Link to the ESLint Governance Model:** (https://eslint.org/docs/latest/contribute/governance)
**Link to the ESLint GitHub:** (https://github.com/eslint/eslint)

ESLint is an open-source project which finds and fixes bugs in a JavaScript code. As an open-source project, ESLint relies on community contributions. Anyone can contribute at any moment by sending code, taking part in conversations, or making any other kind of contribution they deem appropriate.
The governance model has the following features:

1. **Consensus Orientation:** ESLint governance mediates divergent interests and opinions to reach broad consensus keeping in mind all policies and what is in the best interests of the project associates and stakeholders. 
2. **Community Driven:** ESLint is an open-source project and works on community contributions for enhancement and maintenance of the project. 
3. **Active Participation:** The community promotes active participation of teams and the users to directly or indirectly in the smooth running of the project. For example, all the contributors can freely put forward their opinions in the decision making.
4. **Transparency and Inclusivity:** All contributors are included in the working and decision making of the project irrespective of their identity. Transparency is ensured by the free flow of information through different servers regarding a particular group or individual.

The ESLint project welcomes contributions from the community, and encourages community members and users to become involved in the project by contributing code, documentation, or other resources. Community members can also provide feedback and suggestions directly through GitHub issues and pull requests, or by participating in the project's discussion forum over servers like discord. The governance model of the ESLint project is designed to be inclusive, transparent, consensus oriented and community-driven, with the goal of better user experience to its users and conducive development environment to its contributors.

### Project Roles
The project roles and responsibilities of ESLint can be summarized as:

1. **Users** are community contributors which use the platform to meet their requirements and help in improving the user experiences by providing valuable inputs which can be taken into consideration for a proficient user experience.
2. **Contributors** are community members who contribute in concrete ways to the project, most often in the form of code or documentation. There is no expectation of commitment to the project, no specific skill requirements, and no selection process.
3. **Website Team Members** are community members who have shown that they are committed to the continued maintenance of the website through ongoing engagement with the community, They work continuously in the close contact of public branches of the source code to bring some variety on the table. 
4. **Committers** are community members who have shown that they are committed to the continued development of the project through ongoing engagement with the community.
5. **Reviewers** are members of the community that have invested a lot of time in the project by triaging issues, resolving bugs, developing features, and serving as respected community leaders.
6. The **Technical Steering Committee (TSC)** jointly govern the ESLint project by providing high-level guidance and taking final decisions keep in mind the best of the contributors and the users.

### Decision-Making Process
ESLint community follows the consensus seeking decision making which is a type of formal decision making accompanied with a fallback voting procedure. In this type of decision making all the community members and stakeholders can freely express their advices and all the concerns and opinions are taken into consideration. Then the TSC members formulates a broad consensus. This is done to ensure timely decision making. If the consensus is unattainable then fallback voting process is characterized by high number of votes with the idea that this approximates decision by consensus. This is controversial as minority issues get neglected.  Designation of positions is an important part of decision making. The recruitment of committers, reviewers and website team members are nominated by previous members of that particular team. Then the final authority resides with TSC they vote for a potential candidate. The TSC can also remove anybody through TSC motion.  

### How easy or difficult it was to find and understand the governance model ?
Altogether, the governance model is relatively easy to find and understand, especially for me who is familiar with open-source project governance models. I have actively participated in open-source activities at college so, I am quite familiar with the technicalities and documentation process. This might be a cumbersome process for people new beginners, who have just started their journey in open source.

**Comment by Riya2909** [comment]
@arliss-NF

**Comment by arliss-NF** [comment]
Hello @Riya2909 - this is very well done.  I can see your experience with open source coming through.  Your communication is very clear and concise and you understand what the value points of open source are.

**Comment by Riya2909** [comment]
Thankyou @arliss-NF for the feedback !
