### ISSUE TITLE
Third Contribution by Chimnwendum

### ISSUE THREAD

**Issue by Chimnwendum** [numfocus/outreachy-contributions-2023#120]
This is a blog post I wrote about a real estate start-up in my home country. 

Their goal is to make houses/lands accessible to low-income earners by providing an opportunity for these set of people to co-own properties. 

Like any curious mind, I did my research to ensure they are legit. 

Enjoy. 

https://chimnwendum.medium.com/cribstock-my-property-investment-story-8b501002002b?source=friends_link&sk=3bb16690086f98adeeb716b970fdb969

**Comment by arliss-NF** [comment]
Thank you very much for completing your third contribution.  We have really enjoyed reviewing your written submissions. I hope you've enjoyed the experience.
