### ISSUE TITLE
Third Contribution by Veronica Emiola

### ISSUE THREAD

**Issue by VeronicaTee** [numfocus/outreachy-contributions-2023#122]
Name: Veronica Emiola
Here are links to some of my writings:

https://medium.com/@veronicatomilola/why-bitcoin-is-money-or-not-8be669415f86
https://medium.com/@veronicatomilola/building-on-bitcoin-and-the-lightning-network-a-beginners-guide-for-african-software-developers-2d4769787d56

**Comment by VeronicaTee** [comment]
cc @arliss-NF Here's my third contribution for your review.

**Comment by arliss-NF** [comment]
Great work - thanks for sharing.  This is a topic area I'm very interested in.

**Comment by VeronicaTee** [comment]
> Here are links to some of my writings:
> 
> https://medium.com/@veronicatomilola/why-bitcoin-is-money-or-not-8be669415f86 https://medium.com/@veronicatomilola/building-on-bitcoin-and-the-lightning-network-a-beginners-guide-for-african-software-developers-2d4769787d56
