### ISSUE TITLE
Third Contribution By CHIDIOGOR AKUPUE 

### ISSUE THREAD

**Issue by akupueerica** [numfocus/outreachy-contributions-2023#123]
Third contribution by Chidiogor Akupue.
This is an excerpt from my research project to conclude my undergraduate studies in Pharmaceutical sciences. Linked [here](https://www.linkedin.com/posts/chidiogor-akupue-7b7ba823b_university-research-project-excerpt-activity-7043960840420507649-A_7P?utm_source=share&utm_medium=member_desktop)

**Comment by maryamgbemisola** [comment]
@akupueerica . Kindly check out your contribution again. There seems to be no link attached

**Comment by akupueerica** [comment]
Hello @arliss-NF please review and would appreciate any feedback

**Comment by arliss-NF** [comment]
Hi @akupueerica - thanks for adding the link.  The sample was a great read.  Very technical, but I thought it was well-written.  What a great scientific field to be interested in.
