### ISSUE TITLE
Second Contribution by Meggan Nyakwaka

### ISSUE THREAD

**Issue by MegNyakwaka** [numfocus/outreachy-contributions-2023#124]
Name : Meggan Nyakwaka
Projects: [BentoML](https://www.bentoml.com/) | [Yellowbrick](https://www.scikit-yb.org/en/latest/)
Governance Model links: [BentoML](https://github.com/bentoml/BentoML/blob/main/GOVERNANCE.md#conflict-of-interest) | [Yellowbrick](https://github.com/DistrictDataLabs/yellowbrick/blob/main/docs/governance/index.rst)
Other relevant links: 
https://github.com/readme/guides/making-decisions-in-OSS
https://www.scikit-yb.org/en/latest/governance/index.html

**Comparative Analysis of the Governance Models**
According to the governance models linked above, they both have a Benevolent Dictator For Life/ founders who provide leadership to the contributors and project members. Similarly both have a core team that ensure smooth project running.
Other than the regular contributors, Yellowbrick has other distinct roles as explained in the document need to meet the time commitment :a semester that comes with assuming a role as an active contributor. Giving credit where due a specific role is committed to mentoring new members with little to zero experience. A plus which ensures the community is steadily growing by providing a learning opportunity. With BentoML, the contributors have the freedom to show up, contribute in whatever capacity they are able to, with no mandatory time commitments.
BentoML follows a consensus decision making process where it is very member centered and the core team rarely gets involved unless a decision is not reached when a proposal is presented. At Yellowbrick, the community can vote on issues but the founders have the final say eventually which in essence discredits everything done by the community where the founders disagree and vote against the proposal.

Considering the similarities in nature (ML, Python, Open Source) and how decisions influence the direction a project will take, the consensus route is ideal as this ensures that everyone is heard. It yields more success with every proposal bringing new ideas and perspectives to projects. The sense of community is embraced with this collaborative decision making process. 
The Yellowbrick system depicts rigidity and hinders collaboration more so with newer members in view of who has the final say, quite dictatorial if you will. If however the aim of the organization is short term then this is ideal as no time wasted awaiting votes and discussions from a vast community and at the same time ensures accountability for decisions made. 

I still think the effectiveness or reliability of a governance model can be investigated further and deeper based on the success rate of the organization and it's projects. This is not very easy with open source but we could explore other metrics of success such as number of contributors (which is significantly different with both case studies above), the rate of return contributors, and the effects of bottom up approach in open source given the opportunity.

**Comment by MegNyakwaka** [comment]
Hey @arliss-NF , kindly take a look at my contribution. Thanks!

**Comment by arliss-NF** [comment]
@MegNyakwaka - well done - your writing is very good.  I really liked this line "_Considering the similarities in nature (ML, Python, Open Source) and how decisions influence the direction a project will take, the consensus route is ideal as this ensures that everyone is heard. It yields more success with every proposal bringing new ideas and perspectives to projects_."
Kudos!

**Comment by MegNyakwaka** [comment]
@arliss-NF Thank you!! Looking forward to learning more about open source
