### ISSUE TITLE
Third Contribution by Imaobong Njokko

### ISSUE THREAD

**Issue by imanjokko** [numfocus/outreachy-contributions-2023#125]
Name: Imaobong Njokko

This is the link to the documentation of one of my earlier data analytics projects. In this project, I aimed to understand the customer demographic of a Bike Store, what the people who made purchases had in common, and any potential factors that may have contributed to particular groups making more purchases than the others.

[Bike Store Customer Demographic](https://docs.google.com/document/d/1QH-qEvnH_o0x27N7ZcqVsf3YAo1UoqsYV1kvNrcmzy8/edit)

**Comment by imanjokko** [comment]
@arliss-NF Kindly review my third contribution. Thank you

**Comment by arliss-NF** [comment]
@imanjokko - this was a fun read.  Thank you for sharing.  Providing analysis with data and visualizations effectively is very important in the data science world.  Continue to improve your storytelling using both and assessing the size of your visualizations is key as small font size in visuals is hard to read quickly.

**Comment by imanjokko** [comment]
@arliss-NF Thank you very much for your feedback and notes, I will apply them and continue to improve.
