### ISSUE TITLE
Second Contribution by Owoeye Isaac

### ISSUE THREAD

**Issue by isaackingx** [numfocus/outreachy-contributions-2023#126]
Name: Owoeye Isaac
Analyzed Projects: [BQplot ]( https://github.com/bqplot/governance/blob/master/governance.md)|  [Signac](https://signac.io/)

### ANALYSIS 

Contents:
- Overview
- SIgnac 
- BQplot
- Signac Governance Model
- Comparation Between Signac and BQplot Governance Model
- Differences
- Similarities
- Author's Opinion

**Overview**

**Signac**
The signac framework is an open-source project that enables and aids in the management and implementation of large, heterogeneous data spaces, it provides an accomplised workspace for its users by integrating a versatile dashboard. Signac simplifies the storage, generation and analysis of multidimensional data sets associated with large-scale, file-based computational studies. 

**BQplot**
BQplot is an interactive plotting and charting library intended to be used with Jupyter notebooks and ipywidgets.
It is a great visualization tool which includes advanced featues such as candlestick chart, choropleth map, correlation map, etc. which makes it relatively easy to use for beginners.

**Signac Governance Model**
Governance model of signac describes the roles of community members and their required participations, privilledges and responsibilties. It also explains how these community members collective efforts came to create an intellectual property (Signac).

### **Comparation Between Signac and BQplot Governance Model**

**Differences**
Signac governance model operates in a decentralized form in term of decision making thereby giving every Contributor (community member) the opportunity in the decision making, while BQplot governance model operates a centralized form which gives the Steering Council Members the sole responsibilty of making decision even though the inputs of other contributing member such as the Contributors and Instituional Partners are been recognized.The decision making form is a clear difference in the comparation of the duo.

**Similarities**
A seeming similarities in both governance models is that both model of governance relies in their community involvement and thereby giving a lots of people in different geolocation the opportunity to participate and contribute to the projects, and in so doing bringing together diverse of inspirations, skills and intellectual capacities into the project to develop, maintain and sustain a versatile tool for data creation, management, implementation and manipulation.

**Author's Opinion**
In my opinion, the decentralized form of decision making implemented by Signac governance model is better than the centrallized form of decision implemented the BQplot governance model. A decentralized form of decision helps in making un-biased decisions as there is an inclusiveness of all contributing members which include the users. Though a time factor might pose a problem to this model of decision making but if managed well, it's bring about a sense of inclusiveness which makes the project even better.

**Comment by isaackingx** [comment]
cc @arliss-NF this is my second contribution kindly review, thank you.

**Comment by arliss-NF** [comment]
@isaackingtv - well done.  Clear and concise, and well-organized making it easy to read with just the right level of content.  Your conclusion is clear and well-expressed.
