### ISSUE TITLE
Third Contribution by Khadijah Amusat

### ISSUE THREAD

**Issue by Khadeeejah** [numfocus/outreachy-contributions-2023#127]
I write technical articles, tutorial, and documentations. Below are some of my  Writing Samples and Documentations.

[Deploying a proposal For Dao on Celo](https://docs.celo.org/blog/tutorials/deploying-a-proposal-for-daos-on-celo)

[White Paper for a Decentralized Library](https://khadijahs-organization-1.gitbook.io/delibra/)

[Lazerpay Documentation](https://lazerpay-documentation-v2.vercel.app/docs/quick-start)

[Celo Africa Dao Proposal](https://celo.stake.id/#/proposal/85)

Link to my blog on [Hashnode ](https://khadeeejah.hashnode.dev/)where i have series of Technical tutorials

**Comment by Khadeeejah** [comment]
@arliss-NF  here is my third contribution, thank you 🥰

**Comment by arliss-NF** [comment]
@Khadeeejah - wow, you are a prolific writer.  Your tutorials are great.  Being able to do this type of writing in open source is really valuable.  I hope you will keep this up.  This is a skill I wish I could be better at.
Did I read it right that your DAO proposal was successful and you received funding?

**Comment by Khadeeejah** [comment]
> @Khadeeejah - wow, you are a prolific writer.  Your tutorials are great.  Being able to do this type of writing in open source is really valuable.  I hope you will keep this up.  This is a skill I wish I could be better at.
> 
> Did I read it right that your DAO proposal was successful and you received funding?

Yes we did, we are bringing web3 to Africa by educating young talents and assisting them with building projects on the Blockchain.

Thank you so much for your feedback
Means a lot
