### ISSUE TITLE
Third Contribution by Owoeye Isaac

### ISSUE THREAD

**Issue by isaackingx** [numfocus/outreachy-contributions-2023#128]
Name: Owoeye Isaac

1.This article speaks on the role of blockchain technology in cyber security, it's benefits, uses, and how it has helped fight against cyber attacks in recent times.

Link:[ The Role Of Blockchain Technology In Cyber Security](https://medium.com/@Isaacking365/roles-of-blockchain-technology-in-cybersecurity-f1e9441cc9f2)

2. This article educates cryptocurrency users on the need to use hardware wallet to protect their funds, what to look out for when choosing a hardware wallet, benefits of hardware wallet compare to software wallet and recommends a certain type of hardware to the readers.

Link: [Keeping Your Cryptocurrency Assets Safe Using Hardware Wallet ](https://medium.com/@Isaacking365/keeping-your-cryptocurrency-assets-safe-using-hardware-wallet-safepal-hardware-wallet-b74c549f4c06)

**Comment by isaackingx** [comment]
cc @arliss-NF this is my third contribution kindly review, thank you

**Comment by arliss-NF** [comment]
@isaackingtv - thanks for sharing.  Blockchain, what can I say?  Super important topic to be writing about.  Your writing is good and easy to read.  The analogy of "rain" was an interesting way to keep my attention.  Kudos!  Adding imagery to your storytelling will kick it up a notch.  Being on Medium is a good decision.  Well done.
