### ISSUE TITLE
Third Contribution by Rashid Leonard

### ISSUE THREAD

**Issue by rashidleonard** [numfocus/outreachy-contributions-2023#129]
The essay discusses how small businesses, particularly those in the informal economy such as barbershops, face technological challenges that impede their business growth. One of the main challenges for barbers is that they are limited to physical spaces, which can be problematic as customers often demand on-site service delivery regardless of price. To address these challenges, the essay suggests using computer programming and software architecture to create automated systems that can shorten the gap between service provision and customer convenience. The essay also explains how software architecture takes a top-down approach to component-oriented development and can be applied to businesses like barbershops. Overall, the essay argues that incorporating technology into business operations can help small businesses thrive in today's economy.

Here is the link to the paper published on ResearchGate: [DESIGNING A SERVICE-BASED DIGITIZED APPLICATION FOR BARBER SERVICES IN GHANA](https://www.researchgate.net/publication/369378521_DESIGNING_A_SERVICE-BASED_DIGITIZED_APPLICATION_FOR_BARBER_SERVICES_IN_GHANA)

Thank you.

**Comment by rashidleonard** [comment]
Hi @arliss-NF @SavannahSimons, here is my third contribution. Thank you.

**Comment by arliss-NF** [comment]
@rashidleonard - thanks for sharing.  I am closing this quickly to meet the deadline but I will be reading this today as the topic is very interesting and I'd like to know more about Ghana.  Please submit a final application if you are still interested.

**Comment by rashidleonard** [comment]
Hi Arliss, would love to talk about Ghana too. Many historical sites, delicious foods, great music and generally beautiful people, nice weather and soo much more to explore :)

And yes, I have submitted a final application for the project. 

Thank youu:)
