### ISSUE TITLE
Third Contribution by Treasure Okafor

### ISSUE THREAD

**Issue by Teekafy** [numfocus/outreachy-contributions-2023#135]
Name: Treasure Okafor

Hello, These are the links to two of my research writings:
[Technology may have helped introverted individuals, or not](https://1drv.ms/w/s!AuX55ransLX7gUbpm_cUdPKgwdjk)
[Exploring the Impact of Artificial Intelligence (AI) on Employment and the Future of Work](https://1drv.ms/w/s!AuX55ransLX7gTw9GdAJ3VH8Sal3)

**Comment by Teekafy** [comment]
Hi @arliss-NF @SavannahSimons , I would appreciate a look at my contribution, reviews and feedback. Thank you very much.

**Comment by arliss-NF** [comment]
@Teekafy - thank you for sharing your writing.  I was very interested in your piece on introverts.  This is a topic I investigate as I have children and wonder how social media is affecting them.  it would be great to keep digging into that topic.  And ... including visuals in your writing keeps readers interested.  Great approach.
A colleague read your Ai work and said it was well-written.  Continuing to work in this focus area as well is important.

**Comment by Teekafy** [comment]
@arliss-NF wow! that's really interesting.. Yes, I would keep digging into it. Thank you so much!!
