### ISSUE TITLE
Third Contribution by Bukola Ajayi

### ISSUE THREAD

**Issue by BukolaM** [numfocus/outreachy-contributions-2023#136]
#### Topic 1: Exploring the World of Data Science through EDA
I recently delved into the fascinating world of data science and performed an exploratory data analysis (EDA) on a dataset. The insights I gained from this process were eye-opening and allowed me to understand the importance of data in decision-making. Check out my latest LinkedIn post to learn more about the techniques I used and the insights I uncovered!

- Link: https://www.linkedin.com/posts/ajayi-margaret-bukola_data-datascience-eda-activity-7042180920681902082-5x4E?utm_source=share&utm_medium=member_desktop

#### Topic 2: The Power of Data Cleaning: Detecting and Handling Outliers
Data cleaning is an essential step in any data analysis process, and detecting and handling outliers is a crucial aspect of this step. In my latest LinkedIn post, I share my experience of working with a dataset that had outliers and the techniques I used to detect and handle them. Check out the post to learn more about the importance of data cleaning in ensuring accurate and reliable data analysis.
- Link: https://www.linkedin.com/posts/ajayi-margaret-bukola_data-datacleaning-outliers-activity-7026098726272180224-mZT3?utm_source=share&utm_medium=member_desktop
-

**Comment by BukolaM** [comment]
@arliss-NF @SavannahSimons, I would appreciate it if you could kindly review my third contribution. Thank you in advance!

**Comment by arliss-NF** [comment]
@BukolaM - thank you so much for sharing.  It's a great approach to share your writing on LinkedIn, as we use it frequently when we are hiring for positions.  The topics you are writing about are interesting and relevant.  Data science is up and coming, and working in that area through open source will be invaluable.  Your writing style is strong and interesting.  Storytelling using data and visualization is extremely important.  Keep this up.

**Comment by BukolaM** [comment]
Thank you @arliss-NF, for taking the time to share your thoughts on my writing. Your feedback is greatly appreciated, and I'm thrilled to hear that my topics are interesting and relevant to your hiring practices. 

It's reassuring to know that my work is making a positive impression. I will definitely keep working on my storytelling approach using data and visualisation. Thanks again for your kind words
