### ISSUE TITLE
Third contribution by Riya Sharma 

### ISSUE THREAD

**Issue by Riya2909** [numfocus/outreachy-contributions-2023#137]
Hello all !
I have been an avid researcher since my freshman year and have always hoped to use my technical knowledge to make a difference. Mental illnesses and neurological disorders have always interested me. I also desired to participate in that venture and develop tools using technology to help people suffering from the same. My devotion and diligence towards research can be proven through my two publications in **IEEE sponsored international conferences.**  I have extensively worked in the field of dementia a neurological disease which leads to loss of cognitive abilities like memory , speech and etc. My publications includes **"**Aspect Analysis of dementia**"** work on dementia dataset to predict trends of the syndrome. Using that knowledge I published my second publication of **End-to-End recognition approach for Cognitive Impaired speech using Sequential Conv-Nets** . I built a computational tool for the speech recognition of demented patients using convolution neural network , an application of machine learning.  It can be used as a powerful tool for dementia screening of the patients eradicating the manual interventions. 

Link to the research papers- [Research Parpers ](https://drive.google.com/file/d/1TJEePb7UC2UJseDDkShauQdd-nwI6bSB/view?usp=sharing)
 
I hope this provides you a good understanding of my technical writing and interests.

**Comment by Riya2909** [comment]
@arliss-NF

**Comment by arliss-NF** [comment]
@Riya2909 - thank you for sharing your research paper.  Being able to do this type of writing is invaluable.  While I couldn't read the whole paper I found what I read, clear and well-written.  Keep up the great work!
