### ISSUE TITLE
Third contribution by Pamela Ropafadzo Pfunye

### ISSUE THREAD

**Issue by PamelaRopafadzo** [numfocus/outreachy-contributions-2023#139]
This is a research paper that I wrote about the: : IMPACT OF COVID-19 ON THE ADOPTION OF DIGITAL TECHNOLOGIES 
AS SEEN THROUGH THE MARKETING INDUSTRY. I hope you enjoy.

Link: https://drive.google.com/file/d/1PxPeBzr9dWg4zcERODb3laA5i08G-TlM/view

PDF paper: [Pamela_Ropafadzo_Pfunye_Research Paper.pdf](https://github.com/numfocus/outreachy-contributions-2023/files/11038074/Pamela_Ropafadzo_Pfunye_Research.Paper.pdf)

**Comment by PamelaRopafadzo** [comment]
@arliss-NF please have a look at this contribution

**Comment by arliss-NF** [comment]
@PamelaRopafadzo - thank you for sharing.  While I was unable to read the entire paper (I will, though, because the topic is very interesting and relevant), it is obvious you are a strong writer.  Thank you for all your great contributions.  You are a strong candidate for this project.
