### ISSUE TITLE
First Contribution by Deborah Oyegue

### ISSUE THREAD

**Issue by Dee-Tyan** [numfocus/outreachy-contributions-2023#14]
**Name: Deborah Oyegue**
**Project: Electron**
[Project Governance Model](https://www.electronjs.org/governance)

# About Electron

Electron is a framework that allows you to build desktop applications using CSS, HTML, and JavaScript. This cross-platform application builder will enable you to maintain a single JavaScript codebase with little to no development experience.

## Governance Model:

Electron operates on the [Electoral Governance Model](https://www.redhat.com/en/resources/guide-to-open-source-project-governance-models-overview), which means that elections determine governance. In an electoral model of governance, community members have the power to vote and decide on various aspects of the project's governance, such as electing individuals for different roles or approving updates to policies and procedures. The community agrees upon and documents the electoral procedures that will be used, and these procedures are consistently applied in decision-making processes. 

This model is helpful for large open-source projects because it provides a clear framework for sponsors and potential contributors. Electron shows this by providing detailed documentation of its decision-making processes, procedures, project roles, and [contribution guidelines](https://github.com/electron/electron/blob/77bd80dfb21e0d4419eff093e5232dd8fb05432f/CONTRIBUTING.md).

## Project Roles:

As a characteristic of the Electoral governance model, Electron has the project roles explicitly stated on its website. The project roles include:

1. The Administrative Working Group (AWG)
2. API Working Group
3. Community and Safety Working Group
4. Ecosystem Working Group
5. Outreach Working Group
6. Releases Working Group 
7. Security Working Group
8. Upgrade Working Group 

## Decision-making Process:

In Electron, the different working groups are in charge of various operations of the project, such as managing API designs to ensure they meet the standard design principles, managing the community to ensure safety and adherence to the code of conduct, managing projects in the ecosystem, developing and implementing strategies to grow the community, managing software releases, and ensuring project security. While the administrative working group manages all the working groups in the Electron ecosystem.

The administrative group has the responsibility of overseeing other working groups to manage conflicts and ensure interoperability within the Electron ecosystem. If you want to join any of the working groups, you need to contact an existing member who will submit a case on your behalf to be voted on by at least 2/3 of the working group members (your acceptance depends heavily on collaboration with and contributions to the community). However, becoming a member of the administrative working group requires a higher level of expertise. Members must have prior experience managing substantial parts of the project and supporting contributors. 

### Ease of Discovery: 

The governance model used in the open-source project implementation was straightforward and easy to understand. This can be attributed to the clear documentation of the governance model on the project website, which includes links to different working groups (project roles) and contribution guidelines.

**Comment by Dee-Tyan** [comment]
@arliss-NF

**Comment by arliss-NF** [comment]
Hello @Dee-Tyan - great first contribution.  Well-organized, visually easy to read with good flow.  I appreciate the use of embedded links in the information, keeps it clean.  Looking forward to your 2nd contribution.
