### ISSUE TITLE
Third contribution by Desire Oluwarotimi.

### ISSUE THREAD

**Issue by RotimiDesire** [numfocus/outreachy-contributions-2023#141]
**TITLE:-**
The role of open source in education.

**LINK:-**
https://rotimidesire.hashnode.dev/the-role-of-open-source-in-education

**Comment by RotimiDesire** [comment]
@arliss-NF This is my third contribution. Kindly review. Thanks.

**Comment by arliss-NF** [comment]
@RotimiDesire - thanks for sharing your sample of writing.  I am a true believer in your topic that open-source needs to be a part of education, especially for the accessibility aspect.  Improving the accessibility to free software for early career individuals was one of the key reasons I decided to work in open-source.  Kudos.

**Comment by RotimiDesire** [comment]
@arliss-NF Thank you for the review.
