### ISSUE TITLE
Third Contribution by Tanishka Goel

### ISSUE THREAD

**Issue by tg-100** [numfocus/outreachy-contributions-2023#143]
**Name:** Tanishka Goel
**Contribution Types:** 
1. Study and Research of an Indian Start-up Unicorn
**Link to the project:** [Project Report](https://in.docs.wps.com/l/sIKm53fmPAZzq5IwG) 

> **Note:**
> - Please download the file if the preview takes longer to open 
> - The document is a bit lengthy so I recommend reading pages 12-28 (research part) and pages 29-32 (analysis part)

2. Rotaract Project on Forest Conservation
**Link to the project:** [Project Ankuran](https://www.canva.com/design/DAFG2_h_og0/5QzIMyg9Fl5jnXfSRejEyw/view?website#2:project-ankuran)

Hello folks!
The above links are the projects where I used my research skills and data-gathering skills a lot. It also required me to have a clear understanding of the topics to squeeze them into short, limited pages. Hence, the analysis was something implicit in the process. Although I tend to do research and analyze topics and opinions almost on a routine basis, they're not always documented. So, here I have included the projects I did as a part of an official submission or a bigger flagship program.

### Project 1
I made a project report analyzing the Indian start-up unicorn Swiggy as a part of my summer training back in 2021. The project report showcases the following skills used:
- Research and analysis on how they ' made it big ' in India
- Research on their marketing strategy, financial modeling, ideas, etc.
- Analysis of how the strategies worked in their favor 
- Probable drawbacks they could possibly face in future

The project included collecting data from various resources available on the web which have been well-referenced at the end of the project. 

### Project 2
This project was made in 2022 for the flagship project under the Rotaract District 3011 for forest conservation. Highlights of the project:
- It is in the form of a  presentation that is visually engaging
- Showcases research on forest cover
- Analyses best practices to increase forest cover

### My Views on General/Random Research
In general, I love to research various topics that I find interesting, ranging from science and tech, and social issues, to personality types. I hope to open a personal blog/website soon!

**Comment by tg-100** [comment]
@arliss-NF @SavannahSimons I hope you like this contribution. I would love to have your opinions on this :)
Thank you!

**Comment by arliss-NF** [comment]
@tg-100 - your work is so great and fascinating.  I love stories of entrepreneurs.  Becoming a very strong storyteller using text and visualizations is extremely important in data analysis, and you are already using these concepts well.  Also, writing about your interests comes out in your work's quality.  Well done.

**Comment by tg-100** [comment]
@arliss-NF Thank you so much for reviewing all my contributions. I am really grateful to you for giving me such positive and encouraging feedback. It has helped me a lot! 
Really, thank you once again!
