### ISSUE TITLE
First Contribution by Devansh Raizada

### ISSUE THREAD

**Issue by DevanshRaizada** [numfocus/outreachy-contributions-2023#144]
Name: Devansh Raizada
Project Assigned: HoloViz

**Important links for reference:**
[Community Page](https://holoviz.org/community.html) 
[Contribution Page](https://holoviz.org/contributing.html)
[Main Page](https://holoviz.org/)
[GitHub Page](https://github.com/holoviz/holoviz/issues)
[Governance Summary](https://holoviz.org/about.html#governance)
[Organization Charter](https://github.com/holoviz/holoviz/blob/main/doc/governance/org-docs/CHARTER.md)
[Governance Model](https://github.com/holoviz/holoviz/blob/main/doc/governance/project-docs/GOVERNANCE.md)

**HoloViz**
The HoloViz project is based on a shared governance model, which means contributions are welcomed by everyone belonging to any background and expertise. HoloViz functions like a community in which everyone has their say and follows attributes like credibility, inclusion, and joint responsibility. The HoloViz project was formerly known as PyViz.

Contributions of any magnitude are welcome ranging from a small grammatical error or writing a piece on the internet to major changes according to the need and your capabilities. The new contributors are encouraged to first set up the correct environment and then start small contributions growing gradually on the way. There are many benefits of contributing ranging from the benefits of HoloViz and your skill growth to you earning major sums. The HoloViz governance has two levels - the HoloViz Organization and the individual HoloViz Projects.

The project member roles in HoloViz are divided into the following fashion.
**1)The Project Roles**
(i)_Contributors_: These are those people who have at least made one contribution to the project. The definition of a contribution ranges from submitting, reviewing, and discussing GitHub Pull Requests and issues to sharing their opinion in public forums in important discussions.

(ii)_Maintainer_: These are also contributors with some extra responsibilities and power. Maintainers are responsible for developing, maintaining, and updating the project. They have Github permissions like merge permission. They are added and removed to the list by mutual agreement voting process in a cycle of 3 months.

(iii)_Lead Maintainer_: A lead maintainer is also a maintainer with additional responsibilities who are elected or removed by a voting process in the maintainers. A lead maintainer is a person who is highly involved in all aspects of the project such as advocacy, planning, support, review, and development. 

(iv)_Project Director_: Director is a person who gives overall direction to the project in addition to the responsibilities of a maintainer. The director is expected to follow the vote of the maintainers but has the power to veto the verdict with a written explanation. The maintainers can override the veto with a 3/4 vote in their favor and can elect or remove a director with 4/5 votes.

2)**Decision Making-**

(i)_Consensus-Based Decision Making_: The maintainers are the ones involved in the decision-making process and are expected to have an explicit agreement through consensus. In general, the consensus is defined by the absence of strong objections. If consensus cannot be reached, the Maintainers will decide by vote.

(ii)_Voting_: A maintainer can call for a vote with reasonable notice and set a deadline(minimum of 3 working days). The maintainers are explained how to vote and have one vote for each which is publically accessible.

(iii)_Appeal Process_: Decisions may be appealed by opening an issue. Maintainers will judge on the appeal. If still unsatisfied the appeal may be brought before the Organization Steering Committee.

(iv)_Quorum_: Unless otherwise stated, a quorum for a vote can be met with the participation of at least 50% of Maintainers, and at minimum, 2 participants.

3)**How We Work**-

(i)_Openness_: Participation is open to anyone whose affected by the activity. There shall be no undue financial barriers to participation.

(ii)_Balance_: The development process should balance the interests of Maintainers, Contributors, and other stakeholders. 

(iii)_Coordination and Harmonization_: Good gestures shall be shown to resolve potential conflicts between releases in this project.

(iv)_Consideration of Views and Objections_: Prompt consideration shall be given views and objections of all maintainers and contributors.

(v)_Written procedures_: The documentation of any material in this project shall be given to anyone interested.

4)**No Confidentiality-**
Information disclosed in connection with any Project activity is not confidential.

5)**Trademarks-**
Any names, trademarks, logos, or goodwill developed by and associated with the Project (the "Marks") are controlled by the Organization.

6)**Amendments-**
Amendments to this governance policy may be made by an affirmative vote of 2/3 of all Maintainers, with approval by the Organization's Steering Committee.

**Comment by DevanshRaizada** [comment]
Hi @arliss-NF this is my first contribution kindly review, Thanks!!

**Comment by arliss-NF** [comment]
Hi @DevanshRaizada - this is good work.  HoloViz has a large governance model and you did a great job consolidating the information.

**Comment by DevanshRaizada** [comment]
@arliss-NF Thank you so much for reviewing my contribution.
