### ISSUE TITLE
Third Contribution by Khairat Ayinde

### ISSUE THREAD

**Issue by khaiyra** [numfocus/outreachy-contributions-2023#145]
[Mathematical Concepts for Data Science](https://khaiyra.medium.com/mathematical-concept-for-data-science-ec002b18f0b0).

Skills: Research | Technical Writing | Data Science | Analysis | Statistics

**Comment by khaiyra** [comment]
cc @arliss-NF kindly review, thanks.

**Comment by arliss-NF** [comment]
@khaiyra - great topic - I totally agree that math is the basis of data science and it's an important place to start a career in  the field.  I loved the way you wrote about your personal experience.  Keep it up!

**Comment by khaiyra** [comment]
Thanks Arliss for your feedback
