### ISSUE TITLE
Third contribution by Rufus Godgift 

### ISSUE THREAD

**Issue by Godgiftr** [numfocus/outreachy-contributions-2023#146]
The link below is a file containing some of my research and writing works. You can peruse  through
https://drive.google.com/drive/folders/1Q03e2pTZNy_UCUtcbjNkHDGcwgKwbAFS

**Comment by Godgiftr** [comment]
Cc @arliss-NF please your review is highly required

**Comment by arliss-NF** [comment]
@Godgiftr - please provide me access to your doc.  I'd love to read it.  Thank you.

**Comment by Godgiftr** [comment]
Thank you for your response. I have granted you access to my documents. You
can go ahead to review and peruse through them.

Thanks.
Rufus Godgift
