### ISSUE TITLE
First Contribution by Queeneth Ogbonna

### ISSUE THREAD

**Issue by kwin-eth** [numfocus/outreachy-contributions-2023#15]
**Name: Queeneth Ogbonna
Project: QuTip:  https://qutip.org/index.html
Link to the QuTip Governance Model: https://github.com/qutip/governance/blob/main/governance.md
Link to the QuTip GitHub:  https://github.com/qutip**

QuTiP, an open-source software package written in Python, provides users with a variety of tools to learn and simulate quantum systems. It is a versatile toolbox that allows users to explore the intricacies of quantum mechanics, study noise and dissipation effects on quantum systems, and perform advanced research in quantum science.
The top-notch numerical packages Scipy, Numpy, and Cython are all necessary for the QuTiP library to function. Additionally, Matplotlib offers graphical output.

The Community 
QuTiP has fostered a dynamic ecosystem and community of individuals who contribute to and use the software. The community has created a wide range of tools that facilitate the study of different aspects of quantum physics and information processing. QuTiP has over 80 code contributors and has been downloaded over 300,000 times by thousands of users, making it an invaluable resource for researchers and enthusiasts.

GOVERNANCE MODEL:

QuTip Code Of Conduct
QuTiP values inclusivity and respect for all individuals who contribute to the project. They strive to provide a harassment-free experience regardless of gender, gender identity, and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, religion, or nationality. Those who violate this policy will be permanently removed from the project.

Project Roles 

Core Contributors and Contributors:
They are project maintainers who have the right and responsibility to manage and oversee the project. They may remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions as necessary.

Admin Team:
The Admin Team keeps the QuTiP project lively, maintaining the software, and expanding and improving its features.
They are responsible for technical code development and managing QuTiP-related activities which include maintaining the project through software updates and bug fixes, developing new features, participating in forums, providing support, and mentoring others.

Board Members:
The Board Members are in charge of providing scientific advice, monitoring the project's progress, and ensuring that the Admin Team and the project have adequate financial and logistical support. The Board Members are volunteers who pledge to fulfill the responsibilities assigned to them.

Non-Profit Support:
QuTiP is an affiliated project of NumFOCUS, and their primary responsibility is to promote QuTiP knowledge in the quantum software and sci-dev communities amongst other responsibilities.

Decision-Making Process
 
The voting Process and decision making is made in groups: 

Voting Process For Admin:
Core developers and significant contributors are chosen and elected by the already existing admin team to make up the admin team. Candidates who are not nominated may also submit their own applications with statements outlining their prior involvement with QuTiP and their dedication to the organization's future.

Decision-making For Admin: 
Each member of the Admin Team has a vote when making decisions. Prior to making changes, they also make an effort to solicit feedback from the larger community and promptly communicate significant software updates.

Voting Process For Board Members:
The admin team initially selected the members of the Board based on their potential to support the project's growth and their willingness to join. New members may be proposed by current board members or elected by the admin team and existing board members.

As part of their application, potential board members can also include statements about their prior involvement with QuTiP and their dedication to the organization's future. Seats on the Board are held indefinitely, and there must be a minimum of three members and a maximum of seven. A board member who does not participate in the project or does not show up for meetings may be removed by a majority vote.

Decision-Making For Board Members: 
Every board member has one vote, and decisions are made by a majority of votes cast.

How Easy Or Difficult Was It To Find And Understand The Governance Model?

At first, I found it a bit challenging to locate the governance model of the QuTip project, as it wasn't immediately obvious where to find it. However, after doing some research on the meaning of governance models, quantum Python, and the project's affiliation with NumFOCUS, I was able to grasp the concept and figure out how to complete the task. Despite the initial difficulty, the process of familiarizing myself with these topics turned out to be a valuable learning experience. Overall, I was able to successfully complete the task and gained a better understanding of open-source project governance in the process.

**Comment by kwin-eth** [comment]
i just submitted my task. I am hoping and expecting your feedback @arliss-NF

**Comment by arliss-NF** [comment]
@kwin-eth - this is a strong summary of the governance model for QuTiP.  Yes, this project was a bit more challenging, but you did a great job.  We are hoping that doing this type of research will also familiarize beginners to open source to learn about many topics instead of just governance.  Great job!
