### ISSUE TITLE
Third Contribution By Ogbonna Queeneth

### ISSUE THREAD

**Issue by kwin-eth** [numfocus/outreachy-contributions-2023#151]
**Here is a link to a sample of my writing skill:** https://medium.com/@nneomatech/lets-be-real-we-ve-all-been-down-the-rabbit-hole-of-twitter-scrolling-through-endless-tweets-and-442a70f27aea

**An additional write-up:** https://medium.com/p/1b2f736a2516

**Comment by kwin-eth** [comment]
@arliss-NF Thank you!

**Comment by arliss-NF** [comment]
@kwin-eth - thanks for sharing your writings.  They were both a fun read.  I really like your style of writing.  Storytelling with data and visualizations is very important in data analysis these days, and you are doing great.  Keep up the good work.
