### ISSUE TITLE
Third Contribution by Ameerah Kabir.

### ISSUE THREAD

**Issue by AmeerahKabir** [numfocus/outreachy-contributions-2023#152]
Link to my first blog : https://medium.com/@thecyberian29 

The doesn't exactly reflect my writing style, I believe I have made significant changes in finding my writing style and voice. 

Link to my newsletter : techverse.substack.com. 

Started this recently, yet to started writing, making Research and understanding the waters before walking in it, I believe it would reflect my current writing style. Thank youu.

**Comment by AmeerahKabir** [comment]
Hi @arliss-NF and @SavannahSimons I would appreciate your review on both of them, thank youu.

**Comment by arliss-NF** [comment]
Kudos on both these efforts.  Writing and sharing publicly is a skill I wish I had.  Keep doing this work!
Your first blog was a great read.  I learned something new about blockchain.  Thank you
