### ISSUE TITLE
Third  Contribution by BLESSING KAZ

### ISSUE THREAD

**Issue by BlessingKaz** [numfocus/outreachy-contributions-2023#157]
Here is a link to a sample of my writing skill.
 [The future of work in the age of automation and artificial intelligence](https://docs.google.com/document/d/1gS1VkWjQ_Jl73jcfj-uuQ5l7XM3UfKDzb14Iqp9SBo4/edit?usp=drivesdk)  and [The impact of globalization on economy and culture](https://docs.google.com/document/d/1lkOwaX7KZLNCH9RGk8TmZniVXTYoOO9RTG6sdAnqytc/edit?usp=drivesdk)

**Comment by BlessingKaz** [comment]
@arliss-NF  and @SavannahSimons  please kindly review  the sample of my writing skill.

**Comment by arliss-NF** [comment]
@BlessingKaz - love the topics that you've written about. Why did you write on these topics?  Was this part of your education?
I have read through them, and your writing is very good.  I really appreciate all the references at the end of the doc.

**Comment by BlessingKaz** [comment]
@arliss-NF  thanks a lot for the feedback
