### ISSUE TITLE
Third Contribution by Devansh Raizada 

### ISSUE THREAD

**Issue by DevanshRaizada** [numfocus/outreachy-contributions-2023#158]
Recently one of my pieces was selected for a geo-political magazine I'm leaving the piece below-

### The sweet spot of Indian diplomacy

Today in the 21st century, we can see the world getting divided into two very evident groups just like in the Cold War Era. There is the USA & its allies or the liberal world on one side and Russia-China Nexus with its allies on the other side. But as Indians, we identify ourselves in neither of the two camps. Why is it so?? When all the major nations are on one side or the other. This is exactly what's known as the sweet spot of Indian diplomacy.

India is the only major military and economy in the world which enjoys such great relations with the so-called West, that the USA describes India as their biggest partner in the 21st century and Russia calls India a true friend and an independent great power that this world needs. It's absolutely astonishing to see how this new India which once use to be a people-pleaser on the world stage has become completely fearless to the extent that its foreign minister says sitting in Europe "Europe has to grow out of the mindset that Europe's problem is world's problem but world's problem is not Europe's problem" and the Indian P.M said sitting in front of the Russian president "It's not the Era of war".

In a world where the USA, the sole superpower of the world openly says you are either with us or against us also makes exceptions for India. One of these cases was the CAATSA waiver for the purchase of the S-400 air defense system when they didn't even forgive their NATO ally Turkey on the same issue. India is the only country that has active participation in East predominant groups like BRICS and SCO and Western groups like the QUAD and is a common guest in the G-7. No other country can even think about even coming close to this. Such has been Indian diplomacy in recent times that the former P.M of arch-rival Pakistan Imran Khan also couldn't help himself in singing praises of the great and independent foreign policy of India when faced pressure from the USA on the Ukraine issue.

But all of this is not because the world has suddenly developed interest in Indian street food. There is a very famous saying and the very basis of foreign policy "There are no permanent friends just permanent interests" and India's case is no different. India is currently the 5th largest economy in the world and is on course to be the 3rd largest by 2030 according to IMF. It's also the fastest-growing major economy in the world. India has the largest workforce of young and fresh legs in the world where the western world is aging overall India is still very much relatively young. The Western world knows that India is their greatest ally against their biggest rival China. India is a huge nuclear country with a huge physical border with China. India is the solution to all their China problems. Too much manufacturing dependency on China's cheap labor, India is your solution. China is the largest socialist country in the world, India is the largest democracy in the world. When it comes to the Russia-China nexus or the Eastern world Russia has long-standing deep relations with India. Not only is Russia the largest arms exporter of India but has deep partnerships in the field of science, space, international cooperation, etc. Russia has come even closer to India in recent times after the new western sanctions and the trade volume between the two grew exponentially reaching $50 billion much of which is the energy exports of Russia to India which provide cheap discounted oil to India and much-needed cash flow to Russia. India hasn't had normal relations with China but they also understand that if India joins hands with the West it would be a blunder. China has also realized that its bet on Pakistan a failed state is not paying off, which is a bitter pill that the USA has already swallowed. We can also not forget the fact that the Indian diaspora is the largest and is quite influential.

Moreover, India has great relations with the developing world. India has emerged as a leader and voice of the developing world. Which got formal recognition as India hosted the first summit "Voice of the global South". India was the only country to donate huge amounts of quality vaccines to the poor and small countries of the world initially when they needed them the most under "Vaccine Maitri" while the western world was busy stock pilling up to 5 times their population's stock and China was providing inefficient low-quality vaccines. India displayed great leadership skills. 

India is a shining star on the global stage and is enjoying a sweet spot perfectly balancing between the Western and Eastern worlds. India needs all of this for experiencing the rapid rise it's witnessing. As result, India is continuously experiencing growth in stature on the world stage. And this growth is expected to continue this year as well with India hosting SCO, QUAD, and G-20 summit.

**Comment by DevanshRaizada** [comment]
@arliss-NF @SavannahSimons, Kindly review my third contribution, Thanks!!!

**Comment by arliss-NF** [comment]
@DevanshRaizada - great read.  Your writing is solid, with an excellent level of content.  It was a very interesting piece, and I learned a lot.  India is definitely in a good position for growth and has been noticeable, particularly in open source.

**Comment by DevanshRaizada** [comment]
@arliss-NF Thank you so much for the review. Really appreciate the hard work you're putting in for us.
