### ISSUE TITLE
Third Contribution by Sajid Khallow

### ISSUE THREAD

**Issue by khallow7** [numfocus/outreachy-contributions-2023#159]
Sample of written work: [IOT Research Paper](https://docs.google.com/document/d/1tC6RY6L10Uq-fEz-TlV-vMYxyZxdH-7-/edit?usp=sharing&ouid=108053439431322831110&rtpof=true&sd=true)
I have also done some UX writing that I can share, or is this enough?

**Comment by khallow7** [comment]
@arliss-NF @SavannahSimons  Third task completed.

**Comment by arliss-NF** [comment]
@khallow7 - great piece of writing - I love the topic.  Your writing is clear and easy to read.  Adding visualizations would be a good next step.  This is a hot topic now, especially for open-source IoT devices.  Well done.
