### ISSUE TITLE
First Contribution by Susan Mwanzia

### ISSUE THREAD

**Issue by Susan-254** [numfocus/outreachy-contributions-2023#160]
Name: Susan Mwanzia
Project assigned: Open Refine
Link to the Governance model: https://github.com/OpenRefine/OpenRefine/blob/master/GOVERNANCE.md

The Governance Model:

A governance model is a set of tools, guidelines ,procedures and policies used to support and oversee the management of a project. Open refine is a free-open source ,powerful tool used for working messy data. It is based on user consensus and open discussion between users.  The project has used both Cooperative and management team governance model to oversee the overall management of the project. Cooperative governance model in a way that all members share equal responsibility in decision making and same leadership model. Management governance model because the board has divided itself into departments like committee to oversee those areas.

Project Roles:
Release Manager
Steering Committee
Advisory Committee
Project Director

Decision-Making Process:
Open Refine decision making process is done in transparency nothing is done in private without community involvement and participation. Community participation is very vital during the entire decision making process. The governance model used entails all pillars set for achievement of project's set objectives. They include 1.teaming-successfully working together to achieve common purpose, 2.Accountable empowerment-successfully empowering people while at same time holding them accountable, 3.Democracy-all communities participate regardless of their sex, ethnicity, gender, beliefs and values and lastly 
4.Strategic Leadership- defining purpose and setting direction.

Easy to find/ Understand the Model:
Sincerely, it was not easy for me to find the link to Open refine Governance model.  Through my research I got to understand the model used better. The mission of Open refine  project is to help humanitarian cause.

**Comment by Susan-254** [comment]
cc@arliss.NF

**Comment by arliss-NF** [comment]
@Susan-254 - thanks for completing your first contribution.  The OpenRefine governance model was hard to find so I'm glad that you kept going.  You have definitely grasped the ideas of the governance model.  Well done.
