### ISSUE TITLE
Third Contribution by Esther Ewete

### ISSUE THREAD

**Issue by Abosed** [numfocus/outreachy-contributions-2023#161]
I wrote a blog post on Mental Health. I used Schizophrenia as a case study and gave a brief analysis of its Stigma and Awareness in my country Nigeria and China.

Link : [Mental Health](https://myesthers0.wordpress.com/2023/03/24/schizophrenia-in-nigeria-and-china-a-comparative-analysis-of-stigma-and-awareness/)

**Comment by Abosed** [comment]
@arliss-NF @SavannahSimons 

I look forward to hearing your personal opinions on my blog.

**Comment by arliss-NF** [comment]
@Abosed - thanks for sharing your blog post.  It is the type of written analysis we would be looking for.  It was a very interesting read with a good analytical approach.  Thank you very much for completing your third contribution.  We have really enjoyed reviewing your written submissions.
