### ISSUE TITLE
Third Contribution by Susan Mwanzia

### ISSUE THREAD

**Issue by Susan-254** [numfocus/outreachy-contributions-2023#162]
[Susan Mwanzia Project.pdf](https://github.com/numfocus/outreachy-contributions-2023/files/11077430/Susan.Mwanzia.Project.pdf)

The above file is a research project  I conducted last year. I was able to analyze the effects of government policies  towards the growth of tour firms in our Country. My set goals of the study were achieved in a way the research was used as a tool in developing tourism policies.

**Comment by Susan-254** [comment]
@arliss-NF @SavannahSimons 
Kindly review my contribution. Thank you.

**Comment by arliss-NF** [comment]
@Susan-254 - thank you for your third contribution.  I will close this now but am going to read your work.  The topic is interesting to me.  I'll return here for feedback shortly.
