### ISSUE TITLE
First Contribution By Harshita Badwal

### ISSUE THREAD

**Issue by Harshita221** [numfocus/outreachy-contributions-2023#163]
Name: Harshita Badwal
Project Assigned: InterpretML

Important links:
WEBSITE:
https://interpret.ml/
GITHUB:
https://github.com/interpretml/interpret/
README PAGE:
https://github.com/interpretml/interpret/blob/develop/README.md
GOVERNANCE PAGE:
https://github.com/interpretml/interpret/blob/develop/GOVERNANCE.md

InterpretML
A governance model is a set of guidelines that establishes the management and control of projects. There are various governance model types, and the choice of model depends on the objectives and requirements of the project or organization.
Interpret ML is an open source python package developed by Microsoft Research that provides a tool that is used for interpreting and explaining machine learning models. This package helps to train interpretable glass box models and black box systems.
As an open-source project,  InterpretML follows a community-based governance model in which the project's development and maintenance are guided by a team of core contributors and a larger community of contributors and users. The project's core contributors are in charge of supervising the project's direction, evaluating and integrating code contributions, and making sure the project is of a high standard and stable. They specify the project's roadmap and rank the importance of adding new features and fixing bugs.
Overall, the governance model for InterpretML is designed to promote collaboration and community participation, ensuring that the project evolves and improves over time.

Roles:
1. Maintainer
2. Contributors

Decision-Making Process:
Decision-making is one of the most important factors.InterpretML has two types of decision-making processes.
1. Consensus-Based Decision Making. :
Project choices are made by the maintainers' contracts. Consensus doesn't really require explicit agreement from all Maintainers. Maintainers will decide on a consensus after carefully considering a number of factors, including the Contributors' dominant viewpoint and the nature of support and opposition. As per these specifications, the Maintainers will provide paperwork of the consensus.
2. Appeal Process:
Choices may be offered by opening an issue which request will be considered by the maintainers in great confidence, who will react in composing within a sensible time. On the off chance that the maintainers deny the offer, the request may be brought sometime recently to the TSC, who will also react in composing in a sensible time.

How do we work?
1. Openness:
All individuals affected by the activity are eligible to participate. There won't be any unreasonable financial barriers to taking part.
2. Balance: There should be a balance of interests during the development process. In order to strike a balance, contributors with a variety of interests will be sought out.
4. Coordination and Harmonization: Any conflicts or incompatibilities between releases in this Project must be resolved in good faith.
5. Consideration of Views and Objections Brief thought will be given to the composed perspectives and complaints, all things considered.
6. Written procedures. Anyone who is interested in learning more about the project's development process can access this governance document and other materials.

No Confidentiality:
Regardless of any markings or statements to the contrary, information disclosed in connection with any Project activity, including but not limited to meetings, contributions, and submissions, is not confidential.

 Trademarks.
Regardless of ownership, the Project's names, trademarks, logos, and goodwill may only be utilized in accordance with the Organization's Trademark Policy.

How easy or difficult it was to find and understand the governance model?
As I am new to open source contribution so I faced a little difficulty understanding the project but then I do a lot of research and I find it quite interesting . Earlier I only heard the name of the governance model but now with this first contribution, I am able to understand the governance model more clearly. According to my understanding, the mission of interpretML is to make machine learning models more transparent and explainable to both experts and nonexperts.

**Comment by Harshita221** [comment]
cc @arliss-NF 
kindly review my first contribution.

**Comment by arliss-NF** [comment]
@Harshita221 - very thorough first task.  I hope you will continue to develop with open source.  We hoped that we would have applicants like you taking their first steps in open source.  Learning how projects govern themselves is valuable knowledge.
