### ISSUE TITLE
Third Contribution by Meggan Nyakwaka

### ISSUE THREAD

**Issue by MegNyakwaka** [numfocus/outreachy-contributions-2023#164]
Here is the [Link](https://docs.google.com/document/d/1inWXPStACbt4BKZhG_PPkcyN3EKCa7lD/edit?usp=sharing&ouid=109247585157878139044&rtpof=true&sd=true) to my research paper for my third contribution.

@arliss-NF , @SavannahSimons kindly take a look. Thank you!

**Comment by arliss-NF** [comment]
@MegNyakwaka - thank you for sharing your work.  While I couldn't read all of it, I did read most of your "Literature review' - well-written, clear, and concise.  Very interesting topic - I gain awareness that is valuable.  Well done.

**Comment by MegNyakwaka** [comment]
Thank you so much @arliss-NF for the feedback
