### ISSUE TITLE
Third Contribution By Kako Nodia 

### ISSUE THREAD

**Issue by kakonodia** [numfocus/outreachy-contributions-2023#165]
Dear Mentor Hope you are Doing well 
Following the instructions of the Third contribution  
i saw it Good to be creative and i wrote About "Exploring the Prospects and Obstacles of Open Source and Open Science in Scientific Computing and Data Science "
An essay of which i m planning to submit in Open Life Science program  though i m still working and deepening more 
Hope you See it usefull 
Link [Readme Here ](https://docs.google.com/document/d/19zYpoxiaOk5FPt656_k36KYNhE81LAaxEe9K12Rgp54/edit?usp=sharing)

**Comment by kakonodia** [comment]
cc @arliss-NF  
Thank you for your time and consideration

**Comment by arliss-NF** [comment]
@kakonodia - that was a fast read and presented a very concise analysis.  In my work, writings like this are valuable for newcomers to open-source.  You should continue to build this out.  It's a great start.  If you're comfortable, you should share this publicly as much as you can.

**Comment by kakonodia** [comment]
Thank you for the Feedback , about the writings i m actually still working on it and i will publish it  soon !  
under Open Life Science  i would also wish to  contact  when its done  for the review  i will appreciate it so much 
cc @arliss-NF
