### ISSUE TITLE
Second Contribution By Harshita Badwal

### ISSUE THREAD

**Issue by Harshita221** [numfocus/outreachy-contributions-2023#166]
Name: Harshita Badwal
Projects:  InterpretML, Electron
Links:[ https://www.electronjs.org/governance](https://www.electronjs.org/governance)
https://github.com/interpretml/interpret/
Governance model
Electron is a free and open-source framework that lets developers develop desktop applications using web technologies such as HTML, CSS, and JavaScript. GitHub created it and released it as "Atom Shell" in 2013.
Working Groups and Roles
Community & Safety
Docs & Tooling
Outreach
Releases
Security
Upgrades
Website

The Decision-making Process
One of the advisors must propose a vote, which is then submitted to the chair, who defines whether or not the vote can take place. To hold a vote, a core group of all advisors should be present or be accounted for in some way. The vote could be carried out in two ways: by secret vote or by counting individual advisor votes. The only people who can ratify a proposal are the founders, and they have the final say in all decisions. The founding members' decision cannot be overturned.

Analysis of two models:
Similarities:

1. Both Projects are open source and encourage contributions from the community to improve and maintain the software.
2. Both projects have a core team or foundation in charge of managing software development and setting overall direction.
3. In their governance models, both InterpretML and Electron prioritize transparency and open communication.
4. Both projects have established channels for interacting with and soliciting feedback from the community.

Differences:

1. InterpretML's governance is more centrally organized around Microsoft, whereas Electron is more decentralized.

2. Microsoft primarily sponsors InterpretML, whereas Electron is more community-driven and reliant on individual contributions.
3. InterpretML is more open to contributions from anyone, with final decision-making authority resting with Microsoft and the core team, whereas Electron provides more opportunities for community members to participate in working groups and committees.
4. The governance model for Electron is designed to handle the challenges of managing a large and diverse community, whereas InterpretML is more focused on maintaining the software's quality and consistency.

 Opinion on which one is better

In my opinion, both projects have their own pros and cons and have had their own successes. So it will be difficult to say which one of them is the best.  but in my personal opinion,I like the ElectProjectject a little more. The reason for this is that it is a decentralized governance model, which is best suited for projects with a large and diverse community.   It allows for more democratic decision-making and encourages more community participation.

**Comment by Harshita221** [comment]
cc @arliss-NF

**Comment by arliss-NF** [comment]
@Harshita221 - great work.  Solid analysis.  The lead-in to your conclusion is accurate, the decision on which model to use for a project is different for each one, and they do need to weigh the pros and cons.  However, I'm glad you chose one because it's important to be able to have an opinion when doing an analysis.
