### ISSUE TITLE
Third Contribution By Harshita Badwal

### ISSUE THREAD

**Issue by Harshita221** [numfocus/outreachy-contributions-2023#167]
Here is the link for my writing work.

https://harshitasblog.hashnode.dev/

**Comment by Harshita221** [comment]
cc @arliss-NF kindly review my work.
Thank you for your time and consideration

**Comment by arliss-NF** [comment]
@Harshita221 - thanks so much for sharing this personal blog post.  I do hope 2023 will be a better year for you.  There are lots of opportunities to join open-source communities.  One community that is very welcoming to newcomers to OS is the NumPy community - take a look.
