### ISSUE TITLE
Third contribution by Japhet Koech

### ISSUE THREAD

**Issue by ghost** [numfocus/outreachy-contributions-2023#168]
## Third Contribution

Here's the link to my third contribution. Its a OneDrive link to a  research article I did for my Undergraduate studies. 

[Research article Link ](https://1drv.ms/b/s!Ag2rv52kB48ahBZ4yIuPk_ZR4m55?e=ufFNGS)

**Comment by ghost** [comment]
@arliss-NF

**Comment by arliss-NF** [comment]
Very interesting topic to write about.  Your writing is a strong example of scientific research.  Thank you very much for completing your third contribution.  We have really enjoyed reviewing your written submissions.
