### ISSUE TITLE
Third Contribution by Faith Nchifor

### ISSUE THREAD

**Issue by wenebob** [numfocus/outreachy-contributions-2023#169]
### Link:
 https://docs.google.com/document/d/1JcCCBoC62fWPoLQTkRWCddxK_bt_458VVIMxXlmVJ-I/edit?usp=sharing
### About:
This is documentation on an Omdena Local Chapter Project. My tasks include researching on project topic (Automated Left Ventricular Ejection Fraction Assessment using Deep Learning), creating the table of contents, and the writing of the Project statement (Project Background and Project Overview)

**Comment by wenebob** [comment]
Here is my third Contribution @arliss-NF, @SavannahSimons. I will very much appreciate your response

**Comment by arliss-NF** [comment]
@Faith-Nchifor - thank you for selecting this submission.  It was a good sample to share for review.  Your writing is clear and concise.  Thank you very much for completing your third contribution.

**Comment by wenebob** [comment]
Thank you for your review Mme.
