### ISSUE TITLE
Third Contribution by Ogochukwu Onwujiobi

### ISSUE THREAD

**Issue by Og-star** [numfocus/outreachy-contributions-2023#170]
This is a link to a research Project i worked on in Nigeria. I researched on the causes of Domestic Violence in Nigeria.

[https://us.docworkspace.com/d/sILzOvP88soyooQY?sa=03&st=1t](url)

**Comment by Og-star** [comment]
cc @arliss-NF

**Comment by arliss-NF** [comment]
@Og-star - thanks for completing the third contribution.  I will close the issue so you have a merge date; however, I was unable to access your work.  If you could update the link, I'd love to read it.

**Comment by arliss-NF** [comment]
@Og-star - I was able to access the doc you sent.  I will read it today.  Good luck with your final application.

**Comment by Og-star** [comment]
thank you arliss
