### ISSUE TITLE
First contribution made by Samuel Busayo

### ISSUE THREAD

**Issue by bellatrick** [numfocus/outreachy-contributions-2023#20]
Name: Samuel Busayo 
Project: Signac
Link to governance model: https://signac.io/governance/

## Governance model

Signac follows a community-based governance model. This allows any willing participant to contribute to the project and participate in the decision-making process. The community make decisions by voting, and the decision will stand if two-thirds of the community approves. 

Signac employs a rotating management approach to select project managers. The project manager is selected from within a pool of project maintainers and committers. Maintainers and committers are preferred for the managerial role because they are people who have shown exceptional commitment to the project. 

The community measures success by evaluating the different perspectives of the project users.

## Project roles
The following are roles a contributor can take up in Signac:

- Users
- Contributors
- Committers
- Project maintainers
- Administrators
   - Project managers
  - Triage managers
  - Community managers

## Decision making

Although, most of the decision making process in Signac is made by the community, project maintainers and other administrators are more involved in making these decisions:

- Accepting or rejecting self-nominations made by prospective committers.
- Acting on project's strategic direction.
- Inviting and approving new project maintainers, based on their track records in the project.
- Merging of pull requests.

## Task's level of difficulty

 I was able to quickly locate the link to the governance model on the website's navigation bar. I found Signac's governance model to be clear and concise, so I had no issues collating my points for this task.

**Comment by bellatrick** [comment]
@arliss-NF here is my submission for the first phase of the contribution.

**Comment by arliss-NF** [comment]
Closing this issue - feedback is given on the second contribution by this applicant.
