### ISSUE TITLE
FIRST CONTRIBUTION BY PHEBE RADIANT MOMOH. 

### ISSUE THREAD

**Issue by pheberadiant** [numfocus/outreachy-contributions-2023#21]
**Name -** **Phebe Radiant Momoh**
**Assigned Project-** [HoloViz](https://holoviz.org/) 
 [HoloViz GitHub](https://github.com/holoviz/holoviz) 
**Link to the governance model -** 
[HoloViz Organization Governance Model](https://github.com/holoviz/holoviz/blob/main/doc/governance/org-docs/CHARTER.md) 
   [HoloViz Project Governance Model](https://github.com/holoviz/holoviz/blob/main/doc/governance/project-docs/GOVERNANCE.md) 

HoloViz is an open-source Python library that provides tools for creating interactive and web-based visualizations of scientific and engineering data. It is designed to be flexible, allowing users to choose from a variety of different visualization libraries and tools to create custom visualizations that suit their needs.
HoloViz is a collaboration between the maintainers of several Python packages (tools), including HoloViews, GeoViews, hvPlot, Datashader, Param, Colorcet, and Panel.
The authors of these tools are working together closely to help make them into a coherent solution to a wide range of Python visualization problems.
HoloViz is widely used in scientific research, data analysis, and other fields where data visualization is important. HoloViz has both Organization and Project levels. 

**THE GOVERNANCE MODEL:**
The HoloViz governance has two levels - the HoloViz Organization and the HoloViz Projects (including the HoloViz website). This division allows the organization stays aligned as a community while supporting and benefiting from diverse initiatives. 

**HOLOVIZ ORGANIZATION:**
It is an open-source and collaborative effort with a mission to develop visualization solutions for Python.

**HOLOVIZ PROJECT:**
HoloViz project is a subset of the HoloViz Organization. HoloViz offers an all-inclusive solution for visualization by incorporating a suite of effective Python tools that work together to tackle the entire range of visualization problems ranging from investigative data analysis to the deployment of complicated dashboards. 
The core HoloViz projects are: 
- Panel, 
- hvPlot, 
- HoloViews, 
- GeoViews, 
- Datashader, 
- Lumen, 
- Colorcet, 
- Param.
All HoloViz project are freely available for commercial or non-commercial use according to a permissive open-source license as described in each project’s website.
Each HoloViz Project have their own governance that is in accordance with the HoloViz Organization governance. As an example of governance at the HoloViz Project level, is the HoloViz.org website Project. The governance model for other HoloViz Projects can be found in the appropriate repository here - [Link to the governance model of other HoloViz Projects](https://github.com/holoviz) 

**PROJECT ROLES**
**THE GOVERNING BODY AT HOLOVIZ PROJECT LEVEL:**
1. **Contributors** 
2. **Maintainer** 
3. **Lead Maintainer** 
4. **Project Director**

**THE GOVERNING BODY AT HOLOVIZ ORGANIZATION LEVEL:**

1. **Steering Committee:** This committee is responsible for higher-level aspects of the organization, such as setting the overall scope, vision, policy, and direction. 
[Steering Committee Members](https://github.com/holoviz/holoviz/blob/main/doc/governance/org-docs/STEERING-COMMITTEE.md) 

2. **Code of Conduct Committee (CoCC):** This committee is responsible for enforcing and updating the code of conduct.

**THE DECISION-MAKING PROCESS AT THE PROJECT LEVEL.**
1. Consensus-Based Decision Making
2. Voting
4. Appeal Process
5. Quorum 

**THE DECISION-MAKING PROCESS AT THE ORGANIZATION LEVEL.**
1. Decision Making
2. Voting
3. Quorum 

**FINDING THE HOLOVIZ GOVERNANCE MODEL:**
The governance model of HoloViz was easy to find and understand. I used the “Search the Docs” feature on the website to locate the governance model. This led me to the “About Us' page where I found the governance model. 
HoloViz made its governance model straightforward, clear and concise.
As a first-time contributor to Open Source, this was a task I found interesting. I am open to learning and making more meaningful contributions to this community and to Open Source in general.
**Link for further reading** - [HoloViz GitHub](https://github.com/holoviz/holoviz)

**Comment by pheberadiant** [comment]
Hello @arliss-NF 

Here is my submission for the contribution stage. 

Kindly review and I would appreciate your feedback. 

Thank you for your time 😊.

**Comment by arliss-NF** [comment]
@pheberadiant - I appreciate how you explained exactly how you found the governance model as documenting analysis methods is part of this project.
Closing this issue - feedback is given on the second contribution by this applicant as well.

**Comment by pheberadiant** [comment]
Thank you for your feedback @arliss-NF . I am grateful.
