### ISSUE TITLE
First Contribution by Faith Nchifor

### ISSUE THREAD

**Issue by wenebob** [numfocus/outreachy-contributions-2023#22]
### Links to documents:
* [Governance Summary](https://holoviz.org/about.html#governance)
* [Organization Charter](https://github.com/holoviz/holoviz/blob/main/doc/governance/org-docs/CHARTER.md)</li>
* [Governance Model](https://github.com/holoviz/holoviz/blob/main/doc/governance/project-docs/GOVERNANCE.md)
### Governance Model
The HoloViz project follows a hierarchical governance structure. The ranks are listed below from the lowest to the highest
* Contributors
* Maintainers
* Lead Maintainer
* Project Director
#### HoloViz Project Member Roles
-  **Contributors** Are those who contribute the HoloViz project. Their tasks include creating issues, participating in discussions, and creating pull requests.

- **Maintainers** Are those who coordinate activities around the development, maintenance, and update of the project. They are decision makers in all the aspects of the project. Maintainers are Contributors who are active participants with GitHub permissions. The project may add Maintainers by agreement primarily or by vote. Inactive Maintainers may also be voted out.
- The **Lead Maintainer** manages the technical aspects of the project in addition to the responsibilities of a Maintainer.
The Lean Maintainer must be highly involved in all aspects of the project. Maintainers may add or remove a Lead Maintainer by consensus or by vote if consensus cannot be reached.
- The **Project Director** is responsible for setting the scope and overall direction of the project in addition to the responsibilities of a Maintainers. The project director can also reject the result of vote by Maintainers in some cases. The Project Director can be elected/removed by Maintainers by a 4/5 vote.

#### The Decision Making Process 
* The Maintainers are those in charge of making project decisions. Decisions are made through a **Consensus**, taking into consideration the influential factors. Maintainers may make a decision by vote if a consensus cannot be reached.
* A Maintainer can call a **vote** with reasonable notice, notify the other Maintainers and set a deadline for votes to be cast. Every Voting representative will have one vote each and the record of votes ought to be publicly accessible.
* **Appeal process**: Decisions may be appealed by opening an issue. Maintainers will look into the appeal and may grant the appeal or deny it.
* **Quorum**: A quorum for a vote requires at least 50% of Maintainers and a minimum of 2 participants

The governance model was not hard to find it was summarized on the site and the link to the actual document was also provided on the site. Also the governance model is quite easy to understand.

**Comment by wenebob** [comment]
Hello @arliss-NF, everyone. Here is my project. I wish to know what I could do to make it better.  I am open to all your remarks. Thanks.

**Comment by Chimnwendum** [comment]
Hello Faith, just saw you comment in the Google Group. 

Your first contribution looks great. The goal is to write a summary of a project's governance model in your words. And also to include any and every necessary link.

**Comment by wenebob** [comment]
Okay @Chimnwendum. 
Thank you for your review

**Comment by arliss-NF** [comment]
@Faith-Nchifor - great work.  Thank you for sharing all the necessary links to help me find all the places you found the information.  The consolidation is clear and concise.  Well done.
Closing this issue - feedback is given on the second contribution by this applicant.

**Comment by wenebob** [comment]
Thank your for your review @arliss-NF .
