### ISSUE TITLE
First Contribution by Kehinde Adebisi

### ISSUE THREAD

**Issue by Kehindeadebisi** [numfocus/outreachy-contributions-2023#24]
I am Kehinde Adebisi
I was assigned [CVXPY](https://github.com/cvxpy)
Here is the link to the governance model - https://github.com/cvxpy/org/blob/main/governance.md

CVXPY is an open-source Python-embedded modeling language for convex optimization problems. It has a community of researchers, data scientists, software engineers, and students from all over the world.

CVXPY adopts a combination of the Founder-Leader and Self-Appointing governance models while embracing transparency and contribution. 
The roles include:
Benevolent Dictator for Life - Creator
Project Maintainers – Technical Support Lead and Authorities
Emeritus Project Maintainers – Previous Project Maintainers (Now less active)
Steering Committee – Administrative and Legal Duties

The Decision-Making Process was categorized into Financial and Non-Financial Decisions. 
Financial Decisions require majority approval from the Steering Committee while Non-Financial Decisions are made through the consensus of the Project Maintainer (Emeritus Project Maintainers are excluded). 

Non-Financial Decisions are further broken down  as follows:
Code-related – Discussed via GitHub issues, pull requests, or a developer call
Changes to Public APIs – Approval from at least half of the Project Maintainers
Non-Code Related – GitHub issues or a developer call
In the event of a lack of consensus on a non-financial decision, the Steering committee, if delegated or the Benevolent Dictator for Life(BDFL) makes the final decision.

When a conflict of interest occurs, members involved in the conflict are allowed to participate in discussions regarding the issue but not in voting or decision-making.

Finding the governance model was relatively easy, it took a quick scan of the repositories, a visit to the website, and a keyword search on the site. The model is also quite precise and comprehensible.

**Comment by Kehindeadebisi** [comment]
cc @arliss-NF

**Comment by arliss-NF** [comment]
@Kehindeadebisi - good first contribution.
Closing this issue - feedback is given on the second contribution by this applicant.
