### ISSUE TITLE
First Contribution by Khadijah Amusat

### ISSUE THREAD

**Issue by Khadeeejah** [numfocus/outreachy-contributions-2023#25]
Name : Khadijah Amusat
Project Assigned :[ Bento Ml](https://www.bentoml.com/)
[Governance Model](https://github.com/bentoml/BentoML/blob/main/GOVERNANCE.md)

BentoML's governance system is meritocratic and consensus-based.
Everyone with an interest in the project is welcome to join the community, contribute to it, and participate in decision making. And below are document that aims to define how that involvement takes place.

* Contribution guidelines: https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md
* Code of Conduct: https://github.com/bentoml/BentoML/blob/main/CODE_OF_CONDUCT.md
* Development guidelines: https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md
* BentoML contributor mailing list: https://groups.google.com/forum/#!forum/bentoml
* BentoML contributor slack channel: https://bentoml.slack.com/archives/CKC2JP3TM

## Project Roles
1 Contributors
2 Core Team
3 Benevolent dictator (project lead)

## Decision Making Process

Decisions concerning the project's future are determined in consultation with all members of the community, from the newest user to the most experienced PMC member. The [BentoML contributors mailing list](https://groups.google.com/forum/#!forum/bentoml) is where all non-sensitive project management conversation takes happen.

To avoid being mired down by protracted debate and vote, the project employs a policy of lazy consensus. This enables for majority choices to be reached without the need for a formal vote.

#### Lazy consensus

Decision making typically involves the following steps:

* Proposal
* Discussion
* Vote (if consensus is not reached through discussion)
* Decision

Every community member can propose a proposal for the community to consider. They should send an email to the BentoML contributors' list or write a Github issue outlining the new concept to start a conversation about it. This will cause the concept to be reviewed and, if necessary, discussed. This review and debate is intended to acquire approval for the contribution. Because most members in the project community have a common vision, there is frequently little need for dialogue to obtain agreement.

In general, a proposal or patch is considered to have community support as long as no one expressly opposes it. This is known as lazy consensus, and it means that individuals who have not expressed their view explicitly have implicitly consented to the proposal's adoption.

Lazy consensus is a crucial notion in the project. This technique enables a big number of individuals to create an efficient agreement since someone who has no objections to a proposal does not need to spend time articulating their stance, and others do not need to spend time reading such messages.

Allowing at least 72 hours before presuming that there are no objections to the idea is required for lazy consensus to be successful. This stipulation guarantees that everyone has sufficient time to read, absorb, and reply to the proposal. This time span was intended to be as inclusive to all participants as possible, regardless of their location or time obligations.

#### Voting

Lazy consensus is not appropriate for all decisions. Problems affecting the project's strategic direction or legal status must be explicitly approved by the Core Team, which will use the [Apache Foundation voting process](https://www.apache.org/foundation/vote.html).
Every member of the community is urged to participate in all discussions and votes. Yet, only Core Team members have binding votes in decision making.

## How easy or difficult was it to find and understand?
That was fairly simple because the guidelines mentioned that the governance may be available on the website or on the project's Github.
Because of my web3 experience, I understand what a governance model is and how it works, and I am a member of three separate DAOS (Decentralized Autonomous Organizations), which are community-led entities with no central authority. The DAO's activities are quite similar to the governance model.

**Comment by Khadeeejah** [comment]
@arliss-NF here is my submission for my first contribution. thank you

**Comment by Khadeeejah** [comment]
hello @arliss-NF @stefanv  i have still not gotten a review on all my contributions

**Comment by stefanv** [comment]
Sorry, I am not part of this Outreachy project.

**Comment by Khadeeejah** [comment]
> Sorry, I am not part of this Outreachy project. 

Apologies

**Comment by Khadeeejah** [comment]
@arliss-NF

**Comment by arliss-NF** [comment]
Hi @Khadeeejah - excellent work.  Very detailed and well-organized.  Thank you for all the great links.  Gathering these is a part of the project work, so this is a very good start.  I did not know about Lazy consensus, so I learned something.  Thanks for sharing your background in DAOs - this is good to know.
