### ISSUE TITLE
First Contribution By Jamillah Bello

### ISSUE THREAD

**Issue by StrangeJay** [numfocus/outreachy-contributions-2023#26]
Name: Jamillah Bello 
Project Assigned: GNU Radio 
[Project Governance Link](https://github.com/gnuradio/gr-governance) 

GNU Radio is a free and open-source software development toolkit that provides signal processing blocks to implement software-defined radios and signal processing systems. It is used in research, academia, industry, and hobbyist applications to explore and experiment with a wide range of wireless communication systems. GNU Radio is developed by a community of engineers, researchers, and enthusiasts who collaborate to create a flexible and powerful software platform that can be customized to suit various needs. It is licensed under the GNU General Public License (GPL) and runs on various platforms such as Linux, Windows, and macOS.

###  GOVERNANCE
---
GNU Radio has a community-driven governance model with the goal of ensuring that all contributors have an equal say in the development and management of the project. The project is led by a Steering Committee that is composed of active contributors to the project who are elected by the community. The committee members work together to set project priorities, allocate resources, and make decisions about major changes to the software.
Decision-making in the project is typically done through a consensus-based process, where all stakeholders are encouraged to participate and contribute to discussions about the project's direction. When necessary, the Steering Committee may also use a voting procedure to make decisions, where each committee member has an equal vote.

The project has a Code of Conduct that outlines the expected behavior of all contributors and a set of bylaws that govern the operations of the project. These documents help to ensure that the project is run in a fair and transparent manner and that all contributors are treated with respect and valued for their contributions.

### PROJECT ROLES IN GNU RADIO
---
There are several project roles within the GNU Radio community, including:

- Users
- Contributors
- Maintainers
- Reviewers
- Release Managers
- Steering Committee

### RULES AND PROCEDURES FOR ONLINE VOTING
---
The articles of association of GNU Radio Organization state that certain decisions can be made through online voting, including voting on new members, certain rules of procedures, and some financial transactions. The organization also allows online voting for decisions not covered in the articles of association. Different types of votes exist with varying procedures and methods for calculating results. The rules aim to ensure a fair and practical way for the organization to make decisions through online voting.

### GENERAL PROCEDURES FOR VOTING ONLINE 
---
The GNU Radio Organization allows online voting for certain decisions and assigns voting administrators responsible for sending and receiving ballots and calculating and publishing results. Online voting is initiated by a voting proposal and followed by a discussion period before the voting period begins. The voting period lasts for two weeks, and only votes cast during this period are considered for results. The results are published to the membership mailing list, including the number of persons permitted to vote, the total number of votes, and the number of votes for each option. The voting proposal can be retracted by the member who initiated it within the discussion period.

### TYPES OF VOTING
---
There are three types of votes allowed in GNU Radio Organization, namely: 
- Voting for new members 
- Electing groups of people 
- Voting for decisions 

For new member votes, a discussion period of one week is followed by a voting period of one week, with options of "Yes", "No", or "Abstain". For electing groups of people, there is a candidacy period of two weeks followed by a two-week discussion period and options are voted on according to section 3.4. For voting about decisions, a discussion period is started by a voting proposal and at least two members must declare their support for the vote before the voting period begins. The responsible party sends the voting proposal and options are voted on according to section 3.4.

### VOTING SYSTEM
---
The voting system has two sections, 3.4.1 for multiple options and 3.4.2 for two options. If there are more than two options, a meeting procedure must be suggested to ensure all votes count and that voting for an item cannot count against it. If there are exactly two options, each active member can vote with "Yes", "No", or "Abstain". The decision is accepted if there are more "Yes" than "No" votes and the vote isn't invalid according to section 5.

Members of the GNU Radio Organization who are active at the time of the voting period have the right to vote, and online votes are anonymous. The result of a voting only becomes effective if more than 20% of active members vote and if the number of total votes is greater than or equal to 50% of active members. Voting results, except for rejected votes about new members, are published on the GNU Radio website, and the board may modify voting procedures upon request with good reason.

### LEVEL OF DIFFICULTY FINDING AND UNDERSTANDING THE GOVERNANCE MODEL
---
Overall, it was relatively easy to find and understand the governance model of GNU Radio, as the project's website provides clear and concise information about its structure and decision-making processes. The community-driven approach to governance has helped to create an inclusive and collaborative environment that encourages participation and innovation in the development of software-defined radio systems.

**Comment by StrangeJay** [comment]
@arliss-NF  here is my submission for the first phase of the contribution.

**Comment by arliss-NF** [comment]
@StrangeJay - excellent work.  Well-written and well-organized.  Excellent presentation. GNU Radio is a slight different type of open-source project, and you did a good job explaining it.

**Comment by StrangeJay** [comment]
@arliss-NF Thank you for the feedback
