### ISSUE TITLE
First contribution by Chidiogor Akupue

### ISSUE THREAD

**Issue by akupueerica** [numfocus/outreachy-contributions-2023#3]
My name is Chidiogor Akupue

Project Name: BQplot
[link to the project governance model]-(https://github.com/bqplot/governance/blob/master/governance.md)

**BQplot Governance Model** 
BQplot Project is an open-source software project for exploratory and interactive data visualization. The governance model of the BQplot project consists of the steering council and its members who take on leadership responsibilities for the project to ensure through working strategies, the long-term well-being of the project technically, and the community. Council membership terms last two years and initial terms are staggered, so there is a new selection of steering council Members every year. Council Members can serve multiple consecutive terms. Council Members are expected to participate in 3/4 of the regular meetings (at least monthly) to engage in discussions and offline votes on the Steering Council mailing list.
The steering council makes decisions about the project's overall scope, vision, and direction. They create strategic collaborations with other organizations and individuals to develop funding sources and manage expenses. They also make decisions when regular community discussion does not produce consensus on an issue in a reasonable time frame, mediate significant conflict between community participants regarding the direction of the project, resolve code of conduct issues [see here](https://github.com/bqplot/governance/blob/master/code_of_conduct.md), grant or revoke privileges (e.g., releasing, committing, triaging) to Project Contributors, mentor Project Contributors, and make decisions on major architectural or backward-incompatible changes, as well as major releases of The Project.
 
**Project Roles** 
•	Project Contributors - individuals who have helped the project with code contributions, documentation, designs, community management, etc. 
Here is a list of the current Contributors to the main BQplot repository: https://github.com/bqplot/bqplot/graphs/contributors
•	Steering Council - consists of Project Contributors who have produced contributions that are substantial in quality and quantity, and sustained over at least one year. 
•	Institutional Partners - include recognized legal entities that employ at least one Steering Council Member participating in Council work as part of their official duties at the Institutional Partner. Institutions are the project's primary funding mechanism, and it is important to formally acknowledge institutional participation in the project.
•	Users of the Project

**Decision-making process**
The decision of nominated potential steering council members to become members is based on a successful vote by existing council members. If a Council member becomes inactive in the project for a long period, they will be given a grace period of one year and If they do not return to active participation within that period, they will be removed by a vote of the Council without a further grace period.
Changes to the governance documents which are submitted via a GitHub pull request to the project’s governance GitHub repository at https://github.com/bqplot/governance must also be ratified by 2/3 of 80% of the steering council members to be valid.

**How easy or difficult was it to find and understand the governance model?**
The BQplot website [https://bqplot.github.io/bqplot/contributing/](https://bqplot.github.io/bqplot/contributing/),  shows the link to the official version of the BQplot governance document contained in the Project Governance Repository at [https://github.com/bqplot/governance](https://github.com/bqplot/governance) so finding it was relatively easy, understanding it, on the other hand, took a little bit of an effort.

**Comment by akupueerica** [comment]
@arliss-NF

**Comment by arliss-NF** [comment]
@akupueerica - great first contribution.  Understanding governance models can be challenging.  I appreciate your effort at condensing the content.  The content has been summarized to the level we are looking for.

**Comment by akupueerica** [comment]
Hello Arliss,
Thank you for your feedback, If you have any more recommendations for me
please don't hesitate to reach out.

Kind Regards
Erica

**Comment by akupueerica** [comment]
Hello @Arliss Collins ***@***.***>,
 I realized that I didn't tag you in my previous reply, so I'm doing that
now just in case you missed it.
Thank you.

Kind Regards,
Erica
