### ISSUE TITLE
First Contribution by Sai Mimansa Gupta

### ISSUE THREAD

**Issue by mimansa111** [numfocus/outreachy-contributions-2023#30]
Name: Sai Mimansa Gupta
Project: [QuTiP](https://qutip.org/) 
The project's governance model: https://github.com/qutip/governance/blob/main/governance.md

## The Governance Model 
QuTiP is an open-source software for simulating the dynamics of open quantum systems. It is freely available for use and modification on all major platforms such as Linux, Mac OSX, and Windows. It is free of any licensing fees and is ideal for exploring quantum mechanics and dynamics in the classroom for educational as well as state-of-the-art research purposes.

All software developed under the QuTiP Github organization is hosted at [www.github.com/qutip](https://github.com/qutip/governance/blob/main/www.github.com/qutip). All QuTiP project members and contributors should abide by the [Code of Conduct](https://github.com/qutip/qutip/blob/master/CODE_OF_CONDUCT.md).

The development of QuTiP is a community-based effort with developers contributing and adding new features to the growing list of its functions. People who wish to contribute to the project can do so by installing QuTiP from [here](https://qutip.org/docs/latest/installation.html), further they can fix bugs or add enhancements to the project with [Pull Requests](https://github.com/qutip/qutip/pulls). To discuss any bugs or ideas related to the project, they can communicate with other community members through [The Google Forum](https://groups.google.com/group/qutip), [QuTiP News](https://qutip.org/news) and the [Issue Tracker](https://github.com/qutip/qutip/issues).

### Project Roles

- Admin Team
- Board Members
- Core Contributors
- Additional Developers
- Non-Profit Support

### Decision-Making Process

The decision-making involves three ways:

1. **The Advice Process**: The admins make decisions about specific technical issues, features, bugs and pull requests. They try to take in feedback on changes from the wider community and then make their own choices as each admin has a vote in decisions.
2. **The Voting Procedure**:  The decisions regarding the financial and logistic support of the project are taken by the board members. Each board member has a vote in decisions, which are taken by a majority vote.
3. **Consensus**: When new projects wish to come under the umbrella of QuTiP, the maintainer of the new project can only join the admin team upon a consensus reached by the existing admins.

### How is the Project Success Measured?

Every year an annual report is drafted by an Admin Team member which is further sent for review to the QuTiP board. The annual reports for the last two years can be found [here](https://github.com/qutip/governance/blob/main/annual-reports/README.md).

## How easy or difficult it was to find and understand the Governance Model?

I am entirely new to Open-Source so the term governance model was new to me. But, as I researched about it the term now is not foreign to me anymore. For this project, I found the governance model conveniently from the official website itself under the 'Devs' link. As I started reading the governance document everything was precisely written in points so it was comprehensible on the first go, hence I would say it was quite easy to understand it.

**Comment by mimansa111** [comment]
@arliss-NF Eagerly waiting for your input on this!

**Comment by SavannahSimons** [comment]
@zerioi9 
Hi Sai Mimansa Gupta,
Thank you for your contribution! I’m glad to hear the term ‘governance model’ is no longer foreign to you and you understand it better. Great work, looking forward to seeing your second contribution.
