### ISSUE TITLE
First Contribution By Esther Jolomi Adeyinka

### ISSUE THREAD

**Issue by jolomi942** [numfocus/outreachy-contributions-2023#31]
Name: Esther  Jolomi Adeyinka
Project Name: [FluxML](https://github.com/FluxML)
Link FluxML Governance Model: https://fluxml.ai/governance/#advisory_committee__2

My Contribution: [FluxML Governance.docx](https://github.com/numfocus/outreachy-contributions-2023/files/10941550/FluxML.Governance.docx)

how easy or difficult it was to find and understand the FluxML governance model:
I have never contributed to an open source before now. However, the term "governance model" is not new so finding and understanding it was not so difficult for me. Nevertheless, this project gave me a lot of insight into the roles and significance of the governance model in any business. I'm glad I signed up because it helped me improve my research and analytics skills and broadened my knowledge of the subject. 

cc @arliss-NF

**Comment by jolomi942** [comment]
cc @arliss-NF

**Comment by SavannahSimons** [comment]
@jolomi942 

Hi Esther Jolomi Adeyinka,

Thank you for your well written contribution. You have a great grasp of this topic and you were very thorough. Great work, looking forward to seeing your second contribution.
