### ISSUE TITLE
First Contribution by Imaobong Njokko

### ISSUE THREAD

**Issue by imanjokko** [numfocus/outreachy-contributions-2023#32]
Name: Imaobong Njokko

# Project- Django Open Source Project

### Link - [Django Open Source Project Governance Model](https://github.com/django/deps/blob/main/accepted/0010-new-governance.rst)
---
## Description
The primary goals of this proposal are to be more community-driven and less reliant on a certain "core" group of people, while also formalizing Django's processes.

In general, the governance model put forward in Django DEP 0010 seeks to encourage openness and responsibility in the project's decision-making processes. It provides a clear framework for project contributors to understand their roles and responsibilities.

---
## Project Roles
- **Merger:** This role is ideally held  by 3-5 persons, and refers to a person who merges pull requests to Django's repository <https://github.com/django/django/>. 
- **Releaser:** a person who has the authority (and will be granted the necessary permissions) to upload packaged releases of Django to the Python Package Index, and to djangoproject.com.
- **Triage & Review Team:** allows contributors permissions on GitHub to assist with the processing of pull requests.
- **Django Core Developer:** an honorary title given to individuals who make significant and extended contributions.
- **Technical Board:** A board of 5 members, they provide oversight of Django's development, assist in setting the direction of feature development and releases, and make tie-breaking votes when other decision-making processes fail. 

---
## Decision Making Process
All discussions and voting processes are held in forums and venues that are generally open to interested members of the public. i.e.  django-developers mailing list, the Django Forum, or in any other venues the Technical Board choses.

### How new ideas are proposed
Any member of the community in good standing may propose new features for Django at any time. 
For minor changes, proposers shall use the code.djangoproject.com bug tracker and/or any of the approved public forums. And, for major changes, proposers shall use the DEP process, with discussion taking place on any of the approved public forums.

### Voting process of the Technical Board
Proposals are made in the form of YES or NO. The possible outcomes of a vote are:
- **Accept:** "yes"; a score >=3
- **No Action:** "no"; a score between 0-3
- **Veto:** "no"; a score <0. Veto means proposal is subject to the waiting period for reconsideration.

The Technical Board has a voting period of one week. Each vote must be one of the following: "+1", "0", or "-1", and should be accompanied by the reasoning for that decision.

If a voting period ends and not all members of the Technical Board have voted, the vote is considered incomplete. It is also considered incomplete if the current score of the proposal is less than 3 which means that an additional vote can change its outcome. An additional voting period of one week is given, and repeated until the vote is completed. Members of the board can change their votes at any time prior to closing of the final voting period. 

Once a decision has been reached, it is documented and communicated to the community.

---
## Conclusion
While the governance model was easy to understand, it was difficult to find directly from their website; I had to do a google search that eventually led me to the model on their GitHub repository. I would suggest that they add a “contribution” tab at the top of their website that clearly details processes for contribution and easily directs to the governance model, or a link to the model in their Github repository.

**Comment by imanjokko** [comment]
@arliss-NF Kindly review my contribution, thank you.

**Comment by SavannahSimons** [comment]
@imanjokko 

Hi Imaobong Njokko!

Thank you for your contribution! Adding a contribution tab would be very helpful, awesome suggestion. I did notice many of the words were duplicated, it’s better to paraphrase the information. Secondly, an easy fix, please add your name to your issue so we clearly know who we are addressing 😊. Great work, looking forward to seeing your second contribution.

**Comment by imanjokko** [comment]
Hello @SavannahSimons 
I have made some changes based on your feedback and paraphrased the issue
Thank you for your corrections, I appreciate them and will apply them moving forward!
