### ISSUE TITLE
First Contribution by Oluwaseun Odunayo

### ISSUE THREAD

**Issue by oluwaseun-tech** [numfocus/outreachy-contributions-2023#33]
Name: Oluwaseun Odunayo Aribisogan
Project Assigned: FluxML
Link to the project assigned: https://github.com/FluxML

GOVERNANCE MODEL:
Everything about the governance model of FluxML is straightforward and brief. Most of the roles are focused on the committee called Steering Council. Each role and duty that bound them were stated clearly. 

cc @arliss-NF 

PROJECT ROLES:
There are two major roles, namely:
1. Steering council
2.  Advisory Committee

DECISON MAKING PROCESS:
The decision-making process is majorly from the steering council with a simple majority, and making such exceptional changes in the Governance document, but when there are exceptional cases/disagreements among the council then the community reached out to the advisory committee which annually meets on the project activities.

HOW EASY/DIFFICULT:
At first, it was not easy to locate probably because this is my first time contributing to open source and the governance model was new to me, but going through it, I understood perfectly the importance of this model in an organization. It has improved my research and analytical skills. And I know I can still do better if opportune.

**Comment by oluwaseun-tech** [comment]
cc @arliss-NF

**Comment by SavannahSimons** [comment]
@oluwaseun-tech 
Hi Oluwaseun Odunayo Aribisogan,

Thank you for your contribution. The goal of Contribution Task 1 is to read and understand the governance model and decision-making process by writing a paragraph describing them. In addition to providing a link, you are supposed to describe it in your own words. Please feel free to edit and add the paragraphs.

**Comment by oluwaseun-tech** [comment]
@SavannahSimons Thank you so much for the feedback. I will adjust it immediately.

**Comment by oluwaseun-tech** [comment]
@SavannahSimons @arliss-NF have edited it and added the paragraphs, I am open to feedback from you. Thank you for the opportunity.

**Comment by oluwaseun-tech** [comment]
Thank you so much for the feedback, Have corrected it and am open to
learning more.

**Comment by SavannahSimons** [comment]
@oluwaseun-tech Thank you for providing for additional verbiage, we look forward to reading contribution 2 :)

**Comment by oluwaseun-tech** [comment]
Thank you, sir.
