### ISSUE TITLE
First Contribution by Linda Njau.

### ISSUE THREAD

**Issue by Linda-Njau** [numfocus/outreachy-contributions-2023#34]
Name: Linda Njau.
Project Assigned: ESLint 
[Link to Governance model](https://eslint.org/docs/latest/contribute/governance)

**GOVERNANCE MODEL OF ESLint.**
The governance model of ESLint is based on a community-driven approach where anyone can contribute to the project in various ways, such as submitting code, participating in discussions, making suggestions, or providing moral support.
Based on the information available on ESLint's governance model, some of the core principles that can be deduced are:

***Transparency:*** The governance model is designed to be transparent, which means that all decisions made by the ESLint team are documented and available for public scrutiny.

***Community participation:*** The governance model encourages participation from the ESLint community. This means that contributors are welcome to voice their opinions and make suggestions for the future direction of the project.

***Collaborative decision-making:*** Decisions are made collaboratively through a consensus-based approach. This means that all contributors have an equal say in decisions, and the team works to find a solution that is acceptable to everyone.

***Maintainer accountability:*** Maintainers are held accountable for their decisions and actions. This means that if a maintainer makes a decision that is not in the best interest of the project, they can be held accountable by the community.

***Technical excellence:*** The governance model prioritizes technical excellence. This means that decisions are made based on what is best for the project technically, rather than based on personal opinions or agendas.

Overall, ESLint's governance model prioritizes transparency, community participation, collaborative decision-making, maintainer accountability, and technical excellence.
 
**PROJECT ROLES**

1.***Maintainers:*** They are responsible for the overall direction and development of the project, reviewing and merging pull requests, and managing releases.
2.***Collaborators:*** They have write access to the project's codebase and assist maintainers with reviewing and merging pull requests.
3.***Contributors:*** They are community members who contribute code, documentation, or other resources to the project.
4.***Users:*** They are individuals or organizations who use ESLint in their projects and provide feedback to the project team.

**DECISION-MAKING PROCESS**
ESLint governance model uses a consensus-seeking decision-making process, which is similar to formal consensus but with the additional option of a fallback voting procedure if consensus appears unattainable during the deliberations. The fallback voting option is only exercised after all reasonable attempts to address concerns have been exhausted. When consensus is deemed unattainable, the presenter or the facilitator can choose the closing option of a fallback vote.

**EASE OF FINDING THE GOVERNANCE MODEL.**
Finding the ESLint governance model is relatively easy. The website has a header section with a link to ***Docs***. Clicking on this link takes you to the project documentation. Under ***Contributing to ESLint*** in the side panel, there is a link to ***Governance.*** Although it takes a few minutes to locate, the documentation is clear, concise, and easy for anyone to understand.

**Comment by Linda-Njau** [comment]
@arliss-NF 
Looking forward to your feedback.

**Comment by SavannahSimons** [comment]
@Linda-Njau 

Hi Linda, thank you for your contribution! I'm so glad you were able to find the governance model with minimal effort. Great work, looking forward to seeing your second contribution.
