### ISSUE TITLE
First Contribution by Treasure Okafor

### ISSUE THREAD

**Issue by Teekafy** [numfocus/outreachy-contributions-2023#35]
## Project Assigned : **bqplot** 
[BQplot Governance Document](https://github.com/bqplot/governance/blob/master/governance.md)
<br>

### BQplot Governance Model
The BQplot Project  is an open source software project with an objective of developing open-source software for exploratory and interactive data visualization. 
The governance model of this project is based on **the Steering council** consisting of project contributors who participate daily in discussions, code review and other project activities as peers with all other contributors and the community to ensure the long-term wellbeing of the project technically and as a community. The Steering Council conducts regular meetings at least monthly to engage in  discussions and offline votes on the Steering Council mailing list.

The Steering Council makes decisions about the overall administration, collaboration with other organizations, financial sources and major structural and systemic changes to the project.
They may also resolve [code of conduct](https://github.com/bqplot/governance/blob/master/code_of_conduct.md) conflicts, grant or revoke privileges and mentor project contributors.
Openness & transparency, active contribution, institutional neutrality are key foundations of project governance.

 A Project Contributor who has produced contributions that are substantial in quality and quantity, and has sustained over a year is eligible to be a council member. Also, council memberships lasts two years.

### Project Roles
* Project [Contributors](https://github.com/bqplot/bqplot/graphs/contributors) --They are developers and individuals who help with code contributions, documentation, designs, community management, etc. 

* Institutional Partners -- Institutions partners don't succeed any projects however, they are the project's primary funding mechanism. It is important to formally acknowledge institutional participation in the project.

* Users of the Project

### Decision Making Processes

- Nominating potential Steering council members is based on a successful vote by existing council members. If in any case, a Council member becomes inactive in the project for a long interval, they will be given a grace period of one year but if  they do not return to active participation within that period, they will be removed by a vote of the Council without a further grace period.

- The Council reserves the right to eject current Members, if they are deemed to be actively harmful to the project’s well-being and attempts at communication and conflict resolution have failed.

- Changes to the governance documents are submitted via a GitHub pull request to The Project's governance documents [GitHub repository](https://github.com/bqplot/governance). 
This process has two phases; **The discussion phase** where the individual opens a pull-request (PR) in a _draft state_. They may call a vote when they believe enough feedback and iteration has occurred. Next is the **Voting phase**. A 4-week period where the PR is in the _active state_, the Steering Council votes on whether the changes are ratified. 2/3 of 80% votes must be in favor for the proposal to be a success.

### Ease or Difficulty in finding and understanding governance model
I was able to locate the governance document in the bqplot [repository](https://github.com/orgs/bqplot/repositories). To understand furthermore, took some time and keen comprehension. If understanding difficulty had a scale of 1 - 5, I would give it a solid 3.8.

Overall, I am glad I was able to contribute to this project.

**Comment by Teekafy** [comment]
@arliss-NF 
I would appreciate a look at my contribution, reviews and feedback. Thank you

**Comment by SavannahSimons** [comment]
@Teekafy 
Hi Treasure, thank you for your contribution! I'm glad it wasn't too difficult and you were able to read through the governance model. Great work, looking forward to seeing your second contribution.

**Comment by Teekafy** [comment]
Hello @SavannahSimons. Thank you so much. Looking forward to your review too🙏🏽
