### ISSUE TITLE
First Contribution by Sajid Khallow

### ISSUE THREAD

**Issue by khallow7** [numfocus/outreachy-contributions-2023#37]
**Name: Sajid Khallow**
**Project Assigned: GNU Radio**
**Project Link: [GNU Governance Model](https://github.com/gnuradio/gr-governance)**

## GNU Radio
GNU Radio is a free and open-source software toolkit used for developing software-defined radio (SDR) systems. It provides signal processing blocks to design, build and test SDR systems that can receive and transmit a wide range of radio signals, including digital and analog modulations.
 The software is written in Python and C++, and it is distributed under the GNU General Public License (GPL) version 3. GNU Radio is maintained by a community who contribute to the project through code, documentation, and support. It is widely used by researchers, hobbyists, and industry professionals for developing SDR systems for a variety of applications, including wireless communications, spectrum analysis, and radio astronomy, among others.

## GNU Radio Governance Model
GNU Radio is a community-driven open-source project, which means that its governance model is based on collaboration and consensus-building among its contributors. The project is managed by the GNU Radio Steering Committee (GRSC), which is composed of active contributors to the project. The GRSC is responsible for overseeing the development of the software, ensuring that it adheres to the project's mission and vision, and promoting the growth of the community.

The GRSC makes decisions through a consensus-based process, in which all members have an equal say. Discussions take place on mailing lists, forums, and in occasional face-to-face meetings.

## Various Project Roles in GNU Radio
- Steering Committee
- Core Developer
- Maintainers
- Release Managers
- Technical Writers
- Contributors
- Community Managers

## GNU Radio Decision-Making Process
The decision-making process in GNU Radio is based on a consensus-building approach. This means that decisions are made through discussion and agreement among the project's contributors, with the goal of reaching a solution that is acceptable to everyone involved.
The decision-making process typically begins with a proposal or idea being presented by a contributor. This proposal is then discussed by the community through various communication channels, including mailing lists, forums, and chat rooms.

## GNU Radio Voting Procedure
The voting system of GNU Radio consists of three types of votes:  

- New members
- Elections of groups of people
- Voting about decisions

The voting process is initiated by a proposal for voting, which is sent to the membership mailing list and has to include exact and complete information about what is being voted upon.
After the voting proposal is sent, there is a discussion period of two weeks in which active members can discuss and form opinions about the options available for voting.

The voting period lasts for two weeks and is started after the discussion period has ended. During this period, active members cast their votes, and only votes cast within the voting period are considered for the results of the voting.

The voting results are published to the active membership by sending them to the membership mailing list. The results include the number of people permitted to vote, the total number of votes, and the number of votes for each available voting option. The results also include a statement if the voting was valid according to section 5.

For new member votes, there are three options: "Yes," "No," and "Abstain." The new member is accepted if there are more "Yes" than "No" votes and the vote isn't invalid according to section 5.

For elections of groups of people, there is a candidacy period before the voting proposal is sent. The candidacy period lasts two weeks, and all members who declare their candidacy become candidates for the election.

For voting about decisions, the options are voted on according to section 3.4, which describes the voting system for multiple options.

## Easy or Difficult
It was fairly simple to find the governance model of GNU Radio. Just took a few steps in the GitHub Repository to find it. 
It was simple and straightforward to understand the GNU Radio's governance model. All the details are listed in the repository.

**Comment by khallow7** [comment]
Hey @arliss-NF  Here's the first task.

**Comment by SavannahSimons** [comment]
@khallow7 
Hi Sajid,
Thank you for your contribution! I'm glad it was straightforward to find and understand the governance model :) I did notice many of the words were duplicated, it's better to paraphrase the information. Great work, looking forward to seeing your second contribution.
