### ISSUE TITLE
First Contribution by Chimnwendum

### ISSUE THREAD

**Issue by Chimnwendum** [numfocus/outreachy-contributions-2023#4]
Name: Chimnwendum
Project: QuTip (https://qutip.org/)
Link to the QuTip governance model: https://github.com/qutip/governance/blob/main/governance.md#2-admin-team

The Governance Model: The governance model is straightforward. Each role has a list of responsibilities it is expected to carry, and every part is interdependent on one another. 
For instance, while the Admin Team is responsible for leading the technical code development, they need the Board Members to provide finance and logistics for the project. In addition, the Non-Profit will need to provide advice for the Admin Team and Board Members.

Any Project Roles: Yes, there are three distinct roles
1. The Administrative Team
2. The Board Members
3. Non-Profit Support

Decision-Making Process: QuTip exercise a **Voting Procedure**  for whatever decision-making process. For instance, changes to their governance model need to be approved by 3/4 of the Administrative Team through a voting process. For every voting process, the majority wins.

How easy or difficult was it to find and understand the governance model: It was easy as I located their governance model quickly. Understanding it was tricky, but I will not say it was hard.

**Comment by Chimnwendum** [comment]
Hello @arliss-NF, what are your thoughts on this?

**Comment by Chimnwendum** [comment]
Hello @arliss-NF, what are your thoughts on this?

**Comment by arliss-NF** [comment]
@Chimnwendum - this is a great first contribution.  Making the decision to describe the model in your own words was a good one.  
I hope you will move forward with Task 2.

**Comment by Chimnwendum** [comment]
Definitely. Thank you so much for the feedback Arliss
