### ISSUE TITLE
First Contribution by Ufuoma Ejite

### ISSUE THREAD

**Issue by joy-commits** [numfocus/outreachy-contributions-2023#40]
## Name: Ufuoma Ejite
# CVXPY

CVXPY is a Python-embedded modeling language for convex optimization problems, such as least-squares and linear programming. The goal of CVXPY is to improve accessibility and expand the scope of third-party convex optimization solvers. 

## Link to the Project's Governance Model
CVXPY governance model can be accessed [here](https://github.com/cvxpy/org/blob/main/governance.md).
More information on CVXPY can be found [here](https://www.cvxpy.org/).

## Description of CVXPY's Governance Model
CVXPY allows every community member to contribute to the project. Contributions made by members of the community are highly valued. However, CVXPY operates a founder-leader governance model, where the final decision-maker for the project is the Benevolent Dictator For Life (BDFL).
Also, the Steering Committee and the Project Maintainers serve as CVXPY's self-appointed council or board. The Project Maintainers have the last direct impact on the outcome of the CVXPY project, and the Steering Committee is in charge of all other non-technical decisions.

## Project Roles
The different entities that exist within the CVXPY project are as follows:
- **Benevolent Dictator For Life:** The benevolent dictator for life (BDFL) is the project founder, [Steven Diamond](https://stevendiamond.me/). This title is given to a few open-source software development leaders, typically project founders, who retain the final say in disputes or arguments within the community.

- **Project Maintainers:** The technical development leads for the CVXPY project are the project maintainers. They are in charge of overseeing the CVXPY project in the final analysis. 

- **Emeritus Project Maintainers:** These are individuals of the community who once served as project maintainers but have since reduced their level of activity.

- **Steering committee:** The Steering Committee consists of five people. The committee is in charge of running CVXPY's legal and administrative affairs.

## The Decision-Making Process
To make sure that any money are used in a way that advances CVXPY's objective, all financial decisions are decided by the Steering Committee.
The Project Maintainers reach consensus on all non-financial actions.
Although decisions in CVXPY are made by consensus, the BDFL ultimately has the last say.

### Voting Procedures
The Project Maintainers and the Steering Committee reserve the highest voting rights.
Every member of the community who has actively participated in the project is eligible for nomination and appointment by the committee.

### Approval Process
Contributors with commit access are trusted to use the CVXPY repository in a way that is compliant with the decision-making process. All contributions are made through pull requests that are approved by the Project Maintainers.

## Conclusion
Finding the governance model was very easy, as it was just in the GitHub repository of the project. It was very interesting for me, as it was easy to navigate through and understand. 
I got to discover that CVXPY operates 2 governance models - the founder-leader governance model and a self-appointing council or board (an electoral kind-of governance model).

**Comment by joy-commits** [comment]
@arliss-NF Hello, I've made my first contribution.
Thank you

**Comment by arliss-NF** [comment]
@joy-commits - closing this along with your second tasks. Notes on your second contribution.  Well done.

**Comment by joy-commits** [comment]
Thank you @arliss-NF
