### ISSUE TITLE
First Contribution by Bukola Ajayi

### ISSUE THREAD

**Issue by BukolaM** [numfocus/outreachy-contributions-2023#44]
#### PROJECT: GNU Radio
GNU Radio is a flexible software toolset for implementing software radio with inexpensive hardware or simulation. It supports study on wireless communications and actual radio systems in academic, industrial, governmental, and recreational settings. 

#### THE GOVERNANCE MODEL
The governance model of the GNU Radio organization is defined by its articles of association (AOA), which set out the rules and procedures for the organization's operation. Online voting is a crucial component of decision-making within the organization, with specific types of decisions being allowed for online voting under the AOA, such as new members, rules, and financial transactions. The GNU Radio Organization also permits online voting for decisions not explicitly covered by the AOA. Different types of online voting are available, each with unique procedures and methods for calculating results. Members of the organization are granted varying voting rights based on their level of involvement, such as associate or corporate members. The GNU Radio Organization is dedicated to maintaining these principles and regularly updating its governance procedures to meet the changing needs of its members

#### PROJECT ROLES
- Users
- Developers
- Board Members
- Researchers
- Project Members

#### THE DECISION-MAKING PROCESS 
The project positions in the government model have varying degrees of authority and responsibility which can be described as follows:
1. General Assembly

The General Assembly is composed of the active members of the Association, each of whom has one vote. General Assembly makes decisions for the Association, elects the board, and reviews the annual report. It also has the exclusive right to decide on financial transactions and matters submitted by the board or members. Only certain items, such as board elections and changes to the Articles of Association, can be decided in a real-time assembly. A two-thirds majority is required for removing a member from the board.

2. The Board

The Board is comprised of 3 active members who serve a 2-year term and can be re-elected. A president and two proxies are elected from the Board. The Board's duties are outlined in their by-laws, and they make decisions for the Association, implementing decisions from the General Assembly. Each Board member can represent the Association, and a provisional board member is appointed via internet vote if a member resigns. The General Assembly decides on the definite succession and must be informed of any regulatory, court or financial amendments to the Articles of Association.

The GNU Radio Organization is committed to upholding these values and continuously refining its governance procedures to meet the evolving needs of its members.

#### EASE OF FINDING THE GOVERNANCE MODEL
Based on my research experience, I was able to find and understand their governance model without much difficulty. However, I had to conduct additional research to locate their official Github repository as it was not available on their webpage. The repository provided all the necessary information in a clear and descriptive manner.

**Comment by BukolaM** [comment]
@arliss-NF

**Comment by arliss-NF** [comment]
@BukolaM - great work.  Excellent first contribution.  Good level of content.  It's a good thing that the model is easy to find because it should be on every open-source project.

**Comment by BukolaM** [comment]
@arliss-NF , I truly appreciate your valuable feedback. Your opinion means a great deal to me. Thank you for taking the time to share your thoughts with me
