### ISSUE TITLE
First Contribution by Bazgha Razi

### ISSUE THREAD

**Issue by Bazgha19** [numfocus/outreachy-contributions-2023#45]
**Name:** Bazgha Razi
**Project Name:** [BentoML](https://www.bentoml.com/)
**Project Governance Model:** [BentoML Governance Model](https://github.com/bentoml/BentoML/blob/main/GOVERNANCE.md)

_BentoML takes a meritocratic, consensus-based approach to its governance structure. Anyone with an interest in the project can join the community, contribute to the project and participate in the decision making process._

**Project Roles:**

- Contributors: _Anyone can become a contributor, and contributions can take many forms, as detailed in the [BentoML Contribution Guidelines](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md)._
- Core Team: _It consist of contributors who have produced contributions that are substantial in quality and quantity. The core team members has additional responsibilities over those of a contributor._
- Benevolent Dictator (Project Lead): _Dictator has the authority to make all final decisions for the project. BentoML have a BDFL (Benevolent Dictator for Life), who is currently Chaoyu Yang._
- Conflict of Interest: _Members with a conflict of interest in a particular issue may participate in Core Team discussions on that issue, but must recuse themselves from voting on the issue._

**Decision Making Process:**

- Lazy Consensus: _It is a very important concept within the project. It is this process that allows a large group of people to efficiently reach consensus, as someone with no objections to a proposal need not spend time stating their position, and others need not spend time reading such mails._
- Voting: _This process is adopt for issues such as those affecting the strategic direction or legal standing of the project must gain explicit approval from the Core Team. Every member of the community is encouraged to express their opinions in all discussion and all votes. However, only Core Team members have binding votes for the purposes of decision making._

**How easy or difficult it was to find and understand the governance model?**
_It was easy to find the governance model because it's added inside the repository, so it didn't take time to find it. 
As a beginner, understanding the governance model was also quite easy for me because it's well-written._

**Comment by Bazgha19** [comment]
cc @arliss-NF

**Comment by arliss-NF** [comment]
Hi @Bazgha19 - yes, this governance model was easy to find, but in many open-source projects, it can be buried or not public at all.  I agree with your summary that the model is well-written, it is a good example.
