### ISSUE TITLE
First Contribution by Adenike Ateloye

### ISSUE THREAD

**Issue by Oyetayo12** [numfocus/outreachy-contributions-2023#46]
**Name**: Adenike Ateloye
**Project Assigned**: Signac
Link to Signac Governance Model: [https://signac.io/governance/](https://github.com/numfocus/outreachy-contributions-2023/issues/url)

**Signac Governance model**
The signac project is an open-source community initiative with the aim of creating data management and processing software. Everyone who becomes interested in the project is welcome to join the group and participate in decision-making and project design.
Signac governance outlines the process by which contributions are made, the role that community members may play, as well as the responsibilities and advantages these roles include.
The management, supervision, and decision-making processes for projects are governed by a set of rules, protocols, and policies known as project governance. As part of the management process, project governance establishes the benchmark by which projects are judged to have been successful.

**Project roles** 
A variety of roles play a part in the project's success under the Signac governance paradigm. They consist of:

- Users
- Contributors
- Committers
- Project maintainers
- Administrators
- Project Managers
        o	Triage Manager
o	Community Manager

- **Decision-Making process**

- Project maintainers have a significant role in decision-making at Signac, however administrators and committers may also participate in some cases. They consist of;
- The acceptance or rejection of committer and project maintainer nominations, as well as debates and decision-making processes on the project's strategic direction, are expected of all project maintainers.
- Little improvements (to documentation, code, or CI settings) can be made by maintainers who are also committers without a pull request.
- Any member of the community who has demonstrated outstanding dedication to the signac project and command of its overarching goals may be extended an invitation to take on the role of project maintainer. The present project maintainers must vote by two-thirds to approve new project maintainers.
- The (self) nomination process is used to find new committers. By a majority vote, the project maintainers will decide whether to approve or reject the nomination.
- If necessary, such as after an extended period of inactivity, the project maintainers may revoke the committer role by majority vote.

**How simple or complicated it was to locate and comprehend the governance model:**
On the website's navigation bar, I readily found the link to the governance model. I thought the governance structure of Signac was straightforward and precise, thus I had no trouble compiling my points for this work. 
I struggled, though, to add the proper label to the issue in the repository, which was eventually fixed.

**Comment by Oyetayo12** [comment]
@arliss-NF Looking forward to feedback on this assignment. Thank you ma.

**Comment by Oyetayo12** [comment]
Thank you @arliss-NF for the update on the title of my issue. I really appreciate the feedback.

**Comment by arliss-NF** [comment]
@Oyetayo12 - great first contribution - well-organized so that I could read easily.  Your conclusions are spot on.  Being able to find the governance model quickly is the correct approach for any open-source project, but believe me, it is not always the case.

**Comment by Oyetayo12** [comment]
Thank you @arliss-NF for the feedback. point well noted.
