### ISSUE TITLE
First Contribution by Aayushi Chauhan

### ISSUE THREAD

**Issue by Aayushi-10** [numfocus/outreachy-contributions-2023#5]
o	Name: Aayushi Chauhan

o	Project Assigned: OpenRefine (https://openrefine.org/)

o	Link to the project governance model: https://github.com/matrix-msu/Enslaved-OpenRefine/blob/e5ff1107b703ab6df3e1a970d871d79e08f8017c/GOVERNANCE.md

o	**Governance Model:**

OpenRefine is a powerful open source that focus on working on messy data, this involves cleaning the data, transforming it from one form to another, matching the data with external databases via reconciliation services, and fixing inconsistencies by merging the similar values in data. It also takes proper care of the privacy of the data; the processes take place in our own device and not on some cloud.

_Project Roles:_
a.	Users: These are the members who use the project, these users give the project a purpose.
b.	Contributors: These are the members who contribute to the project, either one time or multiple times.
c.	Committers: These are the members who have a deep understanding on the project strategy and have worked closely with users and contributors.

_Decision Making Process:_
OpenRefine uses the Apache Decision making to decide the future of the project. This involves:
a.	Lazy Consensus: This means that one does not need an explicit approval from users to proceed, silence is also treated as a consent. This is done to avoid unnecessary discussions but one needs to be prepared if someone objects.
b.	Consensus Building: This is done to get the feedback of the users before introducing any new feature. There are notations like:
•	+1: This means that I agree with the project and will help to make it happen.
•	+0: This means that I agree with the project but will not make it happen.
•	-0: This means that I do not agree with the project but I am offering no alternative.
•	-1: This means that I do not agree with the project but I am offering an alternative.
c.	Voting: In this, not just consensus plays a part but a proper voting takes place to get the numbers.

Decision making is done in a transparent, open manner. No decisions about the project’s bug fixes or features is done without community involvement and participation. Discussions must begin at the earliest possible point, the community’s participation is vital during the entire decision-making process.

The Governance Model of OpenRefine was easy to comprehend and while reading about it I got familiar with some decision making processes and how an open source software works, how open source contribution happens and much more. Overall, it was a wonderful and interesting task, any views are welcome.

**Comment by Aayushi-10** [comment]
@arliss-NF

**Comment by Chimnwendum** [comment]
Hello, @Aayushi-10. Your contribution is closed. I think you have to open it so it can be as visible as the rest of ours. 

How do you do that? Scroll to the last message box in this thread and click on the visible **reopen issue** box. All the best.

**Comment by Aayushi-10** [comment]
Thanks a lot @Chimnwendum

**Comment by Chimnwendum** [comment]
You are welcome

**Comment by arliss-NF** [comment]
@Aayushi-10 - so glad you enjoyed the first task.  Understanding how an open-source project works is very important to finding the best way to make contributions and to set expectations.
