### ISSUE TITLE
Second Contribution by Ufuoma Ejite

### ISSUE THREAD

**Issue by joy-commits** [numfocus/outreachy-contributions-2023#53]
**Name:** Ufuoma Ejite

**Projects Analyzed:** CVXPY | OpenRefine

**Links to the Governance Model of the Projects:** CVXPY governance model can be accessed [here](https://github.com/cvxpy/org/blob/main/governance.md), and that of OpenRefine can be accessed [here](https://github.com/OpenRefine/OpenRefine/blob/master/GOVERNANCE.md)

### The Project Roles
**CVXPY:** The project roles that exist within CVXPY are
1. Benevolent Dictator For Life (BDFL): This is the project creator, and he retains the final say regarding disputes and arguments in the community.
2. Project maintainers: They are the ultimate authority regarding the CVXPY project.
3. Emeritus project maintainers: They are the ex-project maintainers, and perform a less active role.
4. Steering committee: They handle the legal and administrative tasks within CVXPY.

**OpenRefine:** The project roles that exist within OpenRefine are
1. Users: They are community members who have a need for the project.
2. Contributors: They are users getting more involved with the project.
3. Committers: They make regular contributions to the project. They can review and merge pull requests.
4. Release manager: They coordinate new releases, issues, and pull requests.
5. Steering committee: They oversee the general direction of the project, and perform advocacy duties.
6. Advisory committee: They run the administrative duties of the project.
7. Project director: They help to improve OpenRefine's governance and community diversity, and other day-to-day operations.

### The Decision-making Process
The decision-making process in **CVXPY** is based on the consensus of the project maintainers and steering committee; however, the BDFL is the final decision-maker. All financial decisions are made by the Steering Committee to ensure any funds are spent in a manner that furthers the mission of CVXPY. All non-financial decisions are made via the consensus of the Project Maintainers.
Decisions in **OpenRefine** are made transparently. All decisions are carried out with the involvement and participation of the community. This is done by first building a consensus with the users and then voting amongst the users.

## Conclusion
CVXPY operates a founder-leader kind of governance model where the BDFL (or project creator) has the final say regarding decision-making.
OpenRefine operates a meritocratic or democratic kind of governance model where everyone gets to be involved in decision-making. One advantage of this governance model is that it enables members to decide their level of involvement with that community. 
I think the governance model of OpenRefine is better than that of CVXPY because of its transparency, which, I believe, should be the core of every open-source project.

**Comment by maryamgbemisola** [comment]
@joy-commits . Check out your Conclusion

**Comment by joy-commits** [comment]
> @joy-commits . Check out your Conclusion

Thank you @maryamgbemisola. I was just already editing it

**Comment by joy-commits** [comment]
Hello @arliss-NF I've made my second contribution.
Thank you

**Comment by arliss-NF** [comment]
@joy-commits - this is great - I support your choice that OpenRefine is a better model.  BDFL model can stall a projects progress when only 1 person makes the final choice.  Thanks so much for completing Tasks 1 and 2.

**Comment by joy-commits** [comment]
Thank you @arliss-NF for the review
