### ISSUE TITLE
Second Contribution by Bhaswati Roy

### ISSUE THREAD

**Issue by BhaswatiRoy** [numfocus/outreachy-contributions-2023#54]
Name: Bhaswati Roy
Projects Analysed - InterpretML | BentoML
Link to Governance Model of InterpretML: https://github.com/interpretml/interpret/blob/develop/GOVERNANCE.md
Link to Governance Model of BentoML: https://github.com/bentoml/BentoML/blob/main/GOVERNANCE.md

# Brief Overview of Models

## InterpretML

Project management within InterpretML is defined in the Governance Policy. Two main roles are defined in the policy: Maintainers, who are responsible for developing and maintaining the project and determining consensus, and Contributors, who have contributed to it. Technical Steering Committee appeals may be made to the Maintainers if they disagree with decisions. All contributors' views and objections are considered in this policy, which emphasizes transparency, balance, coordination, and openness. 

## BentoML

BentoML utilizes a meritocratic, consensus-based governance structure that is community-driven. Contributions can take a variety of forms, as outlined in the BentoML Contribution Guidelines, and anyone can join the community. Contributors may answer questions, submit issues, report bugs, and write code. Other responsibilities of Core Team members include managing projects, releases, technical directions, and roadmaps. Decisions are usually deferred to the consensus of the community and the Core Team by the BDFL, which rarely exercises its authority. 

# Roles & Responsibilities

## InterpretML

The InterpretML document outlines the roles within a project, including Maintainers who are responsible for developing and maintaining the project, determining consensus, and designating new Maintainers. It also mentions the Contributors who have made contributions to the project. Additional roles may also be adopted and documented.

## BentoML

The BentoML document highlights three main groups of contributors: Maintainers, Contributors, and the Core Team.
Contributors are community members who make contributions to the project in various forms, such as answering questions, reporting issues, investigating bugs, contributing code or documentation, and creating new examples.

# Decision Makings

## InterpretML

The InterpretML project makes decisions through the consensus of the Maintainers. An explicit agreement of all Maintainers is preferred, but not mandatory. The Maintainers determine consensus based on their good faith consideration of a number of factors, including the dominant view of the Contributors and the nature of support and objections. Evidence of consensus is documented in accordance with these requirements. Decisions may be appealed by opening an issue and the maintainers will respond in writing within a reasonable time. 

## BentoML

The BentoML project makes decisions through discussion with all members of the community, using a policy of lazy consensus to avoid endless discussion and voting. Any community member can propose an idea, which is then reviewed and discussed to gain final approval. Lazy consensus means that as long as nobody explicitly opposes a proposal or patch, it is considered to have the support of the community.

**Comment by BhaswatiRoy** [comment]
Hello @arliss-NF, I have finished my 2nd contribution

**Comment by arliss-NF** [comment]
Hi @BhaswatiRoy - this is a great summary of the 2 projects - this is what we'd be looking for.   Thank you.
Closing both your first and second contributions with this note.

**Comment by BhaswatiRoy** [comment]
> Hi @BhaswatiRoy - this is a great summary of the 2 projects - this is what we'd be looking for. Thank you. Closing both your first and second contributions with this note.

thank you for your feedback!!
