### ISSUE TITLE
Second Contribution by Khadijah Amusat

### ISSUE THREAD

**Issue by Khadeeejah** [numfocus/outreachy-contributions-2023#55]
Name - Amusat Khadijah
Projects Analysed -  BentoML | OpenJS
Project 1 -  https://www.bentoml.com/
[Governance model ](https://github.com/bentoml/BentoML/blob/main/GOVERNANCE.md)
Project 2 - https://openjsf.org/
[Governance model](https://openjsf.org/about/governance/)

# Description of Both Models

### OpenJS Foundation Governance

The OpenJS Foundation is a 501(c)(6) nonprofit financed by its members. They maintain a distinct and consistent division of duties between technical and non-technical governance decisions, adhering to industry best practices.

### BentoML 
BentoML's governance system is meritocratic and consensus-based. Everyone with an interest in the project is welcome to join the community, contribute to it, and participate in decision making. 

# Similarities
Both models have a dictator which has the power to decide all crucial issues for The Project

# Differences

### OpenJS Foundation Governance
An Executive Director (ED) is chosen by the OpenJS Foundation Board of Directors to oversee the organization's daily operations. The ED is entrusted for supporting the strategic initiatives outlined by the Board, carrying them out, and then providing feedback on their effectiveness. In order to get the Foundation closer to its objectives, the ED has the power to cooperate with other organizations or recruit staff and contractors, within the constraints of the available budget. In addition to receiving supervision and feedback from the whole Board, the ED reports to the Chairman of the Board. 

### BentoML 
Unlike the OpenJs model we have one contributors, two core team and a three Benevolent dictator (project lead)
Community members who make tangible contributions to the project are considered **contributors.** 
Contributors who have provided contributions of a high caliber and volume make up the BentoML **Core Team.**
The **BDFL** has the power to decide all crucial issues for The Project in its capacity as Dictator. Benevolently, the BDFL decides to defer such power to the Core Team's and the community discussion channels' consensus in practice.

# Conclusion
With OpenJS, there is a power hierarchy and it doesn't really follow what governance is supposed to be about, however with BentoML, everyone has the ability to vote regardless of the post using the lazy consensus policy. This is why I think BentoML governance is better than OpenJS. Lazy consensus states that a proposal or fix is deemed to have the community's support as long as no one expressly objects to it.

**Comment by Khadeeejah** [comment]
@arliss-NF i just finished my second contribution, kindly review

**Comment by arliss-NF** [comment]
@Khadeeejah - good work.  I would have liked to see a bit more in the "Similarities" section but otherwise, good analysis.  It is definitely written in your own voice.  Thank you.
