### ISSUE TITLE
Second Contribution by Treasure Okafor

### ISSUE THREAD

**Issue by Teekafy** [numfocus/outreachy-contributions-2023#58]
### Projects Analyzed: BQplot | PySAL
 [BQplot](https://github.com/bqplot/governance/blob/master/governance.md)
 [PySAL](https://github.com/pysal/governance)

### Comparative Analysis of the Governance Models

-- **BQplot** and **PySAL** are both open source projects that develop software for data science, though BQplot is majorly for interactive and explanatory data visualization while PySAL focuses on spatial analysis with python.

The governance models of these two projects however have notable similarities and differences in administration, decision making and overall governance.

BQplot's governance model is based on The Steering Council consisting of significant project contributors which make decisions about the project's direction, collaboration with other organizations, financial sources and major structural and systemic changes to the project. Nominating potential Steering council members is based on successful votes by existing council members. The council reserves full authority to eject current member if need be.

PySAL's governance model follows a benevolent dictator for life (BDFL) model of governance who has the authority to make all final decisions for the project. Subsequentially, a subset of individuals called the Steering council, (usually 3 members- package maintainers) make decisions about day-to-day projects. Majorly, the BDFL can defer or override that authority in certain cases.

_____________________________________________
Substantial Project Contributors are eligible to be members of The Steering Council in BQplot, the membership terms last for 2 years.

In PySAL, The Steering council membership lasts for 1 year and a new member is nominated and elected. 

BQplot and PySAL have similar roles such as **the steering council**, **institutional partners**, **project contributors and developers** of course.
Openness & transparency, active contribution, institutional neutrality are key foundations of project governance.

___________________________________________
### Conclusion
In my own opinion, no governance model is better than the other, in the sense that each model has advantages and disadvantages.
The BQplot governance model has an open decision making process, this encourages more diverse perspectives, however this process could be slow if a decision point is not arrived at in time.
The PySAL governance model on the other hand, because of the BDFL enables a faster decision making in situations where there is a deadlock. However there isn't a diverse range of ideas or perspectives because of the small number of the steering council members (which are three). 
In general, the mode of governance would depend on the type of project goals or needs.

**Comment by Teekafy** [comment]
Hello @arliss-NF , @SavannahSimons , please kindly review my second contribution. Thank you😃

**Comment by arliss-NF** [comment]
Hi @Teekafy - great work - your conclusion is solid - I like how you presented your arguments with pros and cons.  Good approach.  Your comment that each project and its community are different from another project is correct. It is important to choose the model that works best for them.

**Comment by Teekafy** [comment]
Thank you @arliss-NF ..I really appreciate your review and feedback. I'm glad you liked it😁
