### ISSUE TITLE
Second Contribution by Esther Jolomi Adeyinka

### ISSUE THREAD

**Issue by jolomi942** [numfocus/outreachy-contributions-2023#59]
Name: Esther Jolomi
Project analyzed: [BentoML](https://www.bentoml.com/) | [FluxML](https://github.com/FluxML)
Link to the BentoML Governance Model: https://github.com/bentoml/BentoML/blob/main/GOVERNANCE.md

**Roles of the BentoML Governance Model**
The roles are basically shared amongst contributors and core team members who make substantial contributions and commitments to the project. The difference between them is their number of contributions and commitments both in quantity and quality. The contributors can become core team members through the consistent contribution of quality work. By this, they get profile recognition and can be nominated to be core team members. This is similar to becoming a member of the steering committee in FluxML.

Decision Making: Only core team member has binding votes during voting. However, all members can make contributions irrespective of when they joined the community. example NumFocus Vs Outreachy applicants.

**Comparative Analysis for FluxML and BentoML**
By and large, the administration models of FluxML and BentoML reflect the various needs and crowds of the two activities. Whilst BentoML is more concerned with practical applications and enterprise use cases, FluxML is with research and innovation. 
The development and success of both projects are driven by their communities of contributors and users.

In summary, the governance model for both FluxML and BentoML is similar in so many ways.  I personally feel the decision-making process of FluxML is a bit rigid as decisions take the benevolent dictator for life (BDFL) model of governance form. This permits a single person or a small group of persons to hold major control over the project's direction and decision-making. BentoML on the other hand has flexibility at its peak as both community contributors and the core team can contribute through discussions. However, their models were created to fit their different operational needs. I love the fact that contributions can take any form as everyone can identify where they belong and make meaningful contributions to the projects.
Based on this as fact, I wouldn’t say one is better than the other. But rather say they both have their uniqueness.

**How easy or difficult was it to find and understand the governance model:** 
Finding the governance model for BentoML was pretty easy as I was able to locate it via the GitHub link provided. I have become familiar with the governance model considering my involvement in both tasks. All thanks to NumFocus and Outreachy.

**Comment by jolomi942** [comment]
cc @arliss-NF what do you think, please?

**Comment by Chimnwendum** [comment]
Hello Esther, @arliss-NF will reply as soon as she can. Please be patient.

**Comment by arliss-NF** [comment]
@jolomi942 - well done - your analysis and summary are very clear and concise.  Your conclusion is perfect as the decision on which governance model to use on each project is not a "one size fits all" - it should meets the needs of the project and the community.
