### ISSUE TITLE
Second Contribution by Chimnwendum

### ISSUE THREAD

**Issue by Chimnwendum** [numfocus/outreachy-contributions-2023#60]
Name; Chimnwendum
Projects Analyzed: [QuTip](https://qutip.org/) | [CVXPY](https://www.cvxpy.org/)
Governance Model of QuTip: https://github.com/qutip/governance/blob/main/governance.md#2-admin-team
Governance Model of CVXPY: https://github.com/cvxpy/org/blob/main/governance.md

Projects Overview:
Although QuTip and CVXPY are open-source projects, their governance model differs in many aspects.

DIFFERENCES:
1. In QuTip, no one has the ultimate power to decide. In contrast, CVXPY has the Benevelont Dictator for Life (BDFL), who possesses the power of autonomy when non-financial decisions can't be made.

2. QuTip uses the **Voting System** for its decision-making, no matter the situation. Whereas CVXPY uses both the **Voting System and Consensus**. The Voting System is for Financial Decisions handled by the Steering committee, while Consensus is for Non-Financial Decisions the Project Maintainers handle.

3. QuTip has three distinct member roles, while CVXPY has four member roles.

4. Those responsible for the technical development in QuTip are called **Admin Team** and are 14 in number. While in CVXPY, they are called **Project Maintainers** and are 5 in number.

5. Those responsible for making financial decisions in QuTip are called **Board Members** and are usually 3-7 in number. While in CVXPY, they are called the **Steering Team** and are 5 in number.

6. The Board Members in QuTip meet once a year to review project development, while the Steering Team in CVXPY meets twice a year for the same purpose.

7. Communication Channels: QuTip uses GitHub as a communication channel for its members. While CVXPY makes use of 4 main communication channels, which include; Google groups, GitHub Discussions, Discord, and Developer Calls.

SIMILARITIES:
1. QuTip and CVXPY ensured no two roles has the same responsibility. This reduces role confusion.

2. Both QuTip and CVXPY use a Code of Conduct that binds the members together and requires members to treat one another with respect. 

3. They both have a mission statement that guides the project's activities.

4. They both have a vetting process for anyone who wants to join any role. One of the vetting processes is having a record of working for the project development.

MY OPINION:
When it comes to the power of autonomy in decision-making, the QuTip Governance Model is better because it does not give a single person the power to make decisions, unlike in CVXPY, where the BDFL exercises the power of autonomy.

**Comment by Chimnwendum** [comment]
Hello @arliss-NF, what are your thoughts on this?

**Comment by jolomi942** [comment]
@Chimnwendum Please be patient as @arliss-NF will respond as soon as can.
