### ISSUE TITLE
Second Contribution by Japhet Koech

### ISSUE THREAD

**Issue by ghost** [numfocus/outreachy-contributions-2023#62]
# Comparative analysis of Signac’s and Dolphicom’s governance model.

Name: Japhet Kiplangat Koech

Initial Project; [The Dolphicom Project](https://gitlab.com/dolphicom/dolphicom/-/commit/93ead820c311ef7aa023b1c1721f2d50c27db119)

Second Project; [The Signac framework](https://signac.io/governance/) 

## Analysis of the governance models
Primary project leadership in The Dolphicom project is provided through a Benevolent dictator for life (BDFL) and the Steering Council. Its governance model takes a hybrid form of governance in that through dependence on the benevolence of the BDFL, authorizing decisions are left to the consensus of the community indicative of a consensus-seeking technical governance model. Further, membership nomination and selection to the steering council is meritocratic, based on technical and non-technical qualifications. 
Signac’s governance model is community-driven, with the project’s code base under the maintenance of committers and project maintenance through a consensus-based approach. Key leadership roles within the community are on a periodical rotational basis guided by alphabetical order of member’s last name. At its core, this model promotes collaboration, inclusivity, and active engagement within the community.

##	Comparative study
While both models employ a level of hierarchies in their decision-making structures there exist differences in how this is implemented. Whereas Dolphicom’s governance model maintains the appointment to leadership positions such as BDFL, Council chair, and Release manager a preserve for the steering council, Signac’s model adopts a rather interesting way through offering these positions to community members on a rotational basis of the alphabetical order of their last name.
Dolphicom’s model recognizes corporate sponsorship through acknowledgment of Institutional partnerships as an important component in the project’s development through having institutions finance project contributors, unlike Signac’s model whereby community members are composed of common contributors and project enthusiasts.
On the voting and decision-making process, Signac employs a majority voting-based system where each voter has an equal say, unlike the Dolphicom which adopts a fractional-based voting system where fraction magnitudes close to 1 indicate strong agreement and fractions further from 1 indicate agreement. The majority-based approach is useful in making clear concise decisions the latter providing a more complex nuance of decision-making progress.

## Conclusion
A BDFL governance model can be truly successful if the BDFL has the project’s prosperity at heart however, solely basing trust on individuals inherently introduces uncertainty and risk to the project's governance. Signac attempts to ignore formal and elaborate governance conventions and tends to rest that on a rotary approach. Although the latter aims to reduce bureaucracy, frequent rotation of leadership can lead to a lack of consistency, reduced accountability, and disruptions in workflow. It is, however, important to note that frequent changes in leadership can also have their own set of advantages. The structured and formalized hybrid governance model of BDFL adopted by Dolphicom offers greater advantages and stability compared to Signac's governance model.

It is, however, important to note that the adoption of governance models is a highly dynamic process as it is dependent on the size of the project, community size, and the overall goals of the project which may vary from time to time. Different models may work for different projects depending on their stage hence it is only just to make comparisons between models adopted by projects that are almost at the same stage, this factor was considered in the selection of the second project for comparison.

**Comment by ghost** [comment]
My second contribution and presentation for your consideration, @arliss-NF

**Comment by arliss-NF** [comment]
@japhet-koech - Excellent analysis and summary - appreciate the flow of your thoughts.  Exactly what we'd be looking for.  Thank you.
Closing both your first and second contributions with this note.

**Comment by ghost** [comment]
@arliss-NF ,  thank you for reviewing my submission.
