### ISSUE TITLE
First contribution by Desire Oluwarotimi.

### ISSUE THREAD

**Issue by RotimiDesire** [numfocus/outreachy-contributions-2023#64]
NAME :- Desire Oluwarotimi
ASSIGNED PROJECT :- PyTorch
LINK TO PROJECT GOVERNANCE MODEL :-  https://pytorch.org/docs/stable/community/governance.html

PYTORCH GOVERNANCE MODEL.

PyTorch has a governance model in place which is traditionally hierarchical to manage the development, maintenance and decision making processes. The PyTorch governance model constitutes a main team that is largely in charge of the overall growth and overseeing of PyTorch. The main team is backed up by a community of contributors. The PyTorch governance model looks to be maximally transparent and involving because it has a place for contributors who submit code, documentation, bug reports and feature requests. 

Conclusively, the PyTorch model is designed to enhance a collaborative and inclusive development procedure involving its main team and group of contributors ensuring that the project meets the preferred need of its users.

PYTORCH PROJECT ROLES.

1. Contributors
2. Module maintainers
3. Core maintainers
4. Lead core maintainers.

PYTORCH DECISION MAKING PROCESS.

While seeking to maintain an aforementioned characteristic of transparency, PyTorch ensures to conduct a community-driven decision making process that incorporates feedbacks and opinions from every beneficiary of the project which includes the main team, contributors and users. Primarily, the decision making process happens on public forums such as GitHub and If need be, a vote could be conducted to arrive at a decision that would further promote the activities of PyTorch.

FINDING AND UNDERSTANDING THE PYTORCH GOVERNANCE MODEL.

Finding and locating the Pytorch governance model was pretty easy and stress free. This was majorly because the governance model had a dedicated page of its own on the PyTorch website. 

Understanding the the PyTorch governance model wasn’t a hassle in any way. There was a clear outline about what the governance model is all about on the website starting from a summary of PyTorch’s adoption of a technical governance structure to explaining the different available project roles and their responsibilities. Other important details about PyTorch such as the decision making process as well as the nominating, confirming and removing of maintainers were also not left out.

**Comment by RotimiDesire** [comment]
@arliss-NF This is my first contribution. Kindly review. Thanks.

**Comment by maryamgbemisola** [comment]
@RotimiDesire . You may proceed to the second project while you await the review of your first Contribution

**Comment by RotimiDesire** [comment]
@maryamgbemisola I'm aware. Thank you.

**Comment by maryamgbemisola** [comment]
You are welcome

**Comment by arliss-NF** [comment]
@RotimiDesire - great first task.  Apologies for not reviewing sooner.  I will move on to your second right away.

**Comment by RotimiDesire** [comment]
@arliss-NF Thank you for the review.
