### ISSUE TITLE
Second Contribution by Faith Nchifor

### ISSUE THREAD

**Issue by wenebob** [numfocus/outreachy-contributions-2023#68]
### Links:
* [HoloViz governance model](https://github.com/holoviz/holoviz/blob/main/doc/governance/project-docs/GOVERNANCE.md)
* [Pytorch governance model](https://pytorch.org/docs/master/community/governance.html)
#### Similiarities
There are some similiarities in the governace models of both products. 
Firstly, the governance structure of both models are hierarchical. 
Also, both models have four levels;
1) **HoloViz** has the following levels from smallest:
* Contributors
* Maintainers
* Lead Maintainer
* Project Coordinator 
3) **Pytorch** has the following levels from smallest:
* Contributors
* Module Maintainers
* Core Maintainers
* Lead Core Maintainers
The roles of Contributors in both models are the same. Some activities by Contributors include creating issues, creating pull requests. Again, in both organizations, the Maintainers/Module Maintainers are those in charge of the decision making process. Some of the activities for both models include reviewing, merging, and deleting pull requests.
#### Differences
There are some differences in the decision making process of both organizations.
Firstly, the governance model for Pytorch states that decision making is primarily by consensus meanwhile that of HoloViz states that default decision making is by Voting.
Secondly,  for Pytorch governance, Module Maintainer membership is given to individuals on merit basis after they demonstrated strong expertise of the component through contributions, reviews, and discussions. The same applies for removal of Maintainers. On the other hand, HoloViz governance model states that Maintainers are selected primarily by consensus. A vote may be used if a consensus cannot be reached.

#### My Preference
I would prefer Pytorch governance model primarily because of the model's method of nominating new role members. Merit based selection is more reliable for ensuring that capable individuals are select for the various roles.

**Comment by wenebob** [comment]
Hello @arliss-NF. Here is my second contribution. 
I must admit this second project made me go over my first project again and I made some corrections. Initially, I was confused if the project was about the HoloViz organization or HoloViz website project. I even wrote you on slack about this and I am yet to get a reply.
Here is a link to my first issue: #22 
Thanks.

**Comment by arliss-NF** [comment]
Hello @Faith-Nchifor - thank you for your feedback.  So sorry for my delayed response.  I was unaware there was confusion and I wish I'd responded sooner.
I just read your first contribution and it was very good, so the changes you made we a good decision.  
Your second contribution is well done.  Clear, concise, and easy to read.  And ... I agree with your conclusion.

**Comment by wenebob** [comment]
I'm relieved that you replied to my contribution. Thank you @arliss-NF for your review and kudos to the good work.
