### ISSUE TITLE
Second contribution by BLESSING KAZ

### ISSUE THREAD

**Issue by BlessingKaz** [numfocus/outreachy-contributions-2023#70]
-  **Name:** BLESSING KAZ

-  **Project :** [the Django](https://docs.djangoproject.com/en/4.1/#the-django-open-source-project/) | [The PySAL](https://pysal.org/)

- **Link(s) to relevant source:**
[The Django governance model overview](https://www.djangoproject.com/weblog/2020/mar/12/governance/)
[The Django organization documentation ](https://docs.djangoproject.com/en/dev/internals/organization/)
[The Django decision-making process document ](https://github.com/django/deps/blob/main/final/0001-dep-process.rst/)
[The Django code of conduct ](https://www.djangoproject.com/conduct/)
[The PySAL governance model](https://github.com/pysal/governance/)
[The PySAL code of conduct ](https://github.com/pysal/governance/blob/main/conduct/code_of_conduct.rst/)
[The PySAL contributor guidelines ](https://pysal.org/community/)

### GOVERNMENT MODEL ANALYSIS

The PySAL project is an open-source project for spatial analysis in Python that is governed by a meritocracy model where decision-making power is based on merit, and quality of contributions. This is designed to ensure that the project remains sustainable, transparent, and responsive to the needs of its users and contributors. As the community share their ideas and suggestions through various channels and forums.

- [ ] The governance model of [PySAL](https://github.com/pysal/governance/) and [Django](https://www.djangoproject.com/weblog/2020/mar/12/governance/)are similar because they both follow an open-source model of governance. This means that the source code for the project is freely available for anyone to view, modify, and distribute.The governance model for both projects is also community-driven, with contributions and decision-making.

-  PySAL and Django are two open-source software projects with different aims. PySAL is for a spatial data analysis, while Django is a web framework for building web applications.

- The governance model of PySAL is based on a meritocracy model but has a more centralized decision-making process, with the final decision-making authority settling with the core team but decisions are based on the  community. This means that anyone can contribute, and their contributions will be evaluated based on the impact they have on the project development as technical decisions are made by the core team in alignment with the community. The decision-making power is distributed among a group of core developers and community, rather than a single individual.

- While the governance model of Django is also based on meritocracy model, the core team and technical board are the main committers. The core team of developers are responsible for making decisions related to the project while the technical board gives guidance and advice to the core team. These decisions are made through a consensus-based process, in which all members of the team  and community have an equal right to contribute.

In my opinion, the success of a project depends on the specific goals, needs and size. In smaller projects like *PySAL* with a clear vision and a small team of developers, the meritocracy model is more effective. There's a collaborative and small distributed decision-making process among the community based on quality of the contributions and merit. While larger projects like *Django* with a complex set of goals and a larger community of contributors, the core teams and technical board are the major decision-makers to ensure the best interests of the project are actualized.

**Comment by BlessingKaz** [comment]
@arliss-NF please kindly review my second contribution

**Comment by BlessingKaz** [comment]
@arliss-NF  please kindly review my contribution.

**Comment by arliss-NF** [comment]
Hi @BlessingKaz - good work.  I'm glad you chose projects that differ in size and complexity.  Your analysis is clearly stated. Well done.

**Comment by BlessingKaz** [comment]
thank you so much for the feedback and guidance so far @arliss-NF
