### ISSUE TITLE
Second contribution by Oluwaseun Odunayo

### ISSUE THREAD

**Issue by oluwaseun-tech** [numfocus/outreachy-contributions-2023#72]
Name: Oluwaseun Odunayo Aribisogan
The project analyzed: BentoML| FluxML
Project Links of BentoML: https://github.com/bentoml/BentoML/blob/main/GOVERNANCE.md
Project Link of FluxML: https://fluxml.ai/governance/

PROJECT OVERVIEW:
 BentoML and FluxML governance model is quite similar. Although they are both serving different purposes. FluxML is more concerned with research and development while BentoML is more of potential implementation and organization use cases. The communities of contributors and users drive the growth and accomplishment of both projects.

DIFFERENCES
•	The governance structure in BentoML is merit-based and discussion. That is, the community is influencing it. FluxML, on the other hand, is not entirely merit-based and perception. Your willingness to serve matters.
•	BentoML core team members are primary contributors who have made significant contributions in both the amount and quality with no time restrictions. Unlike FluxML, the core team member is known as the steering council, and it is made up of project contributors who have made contributions that have been maintained for at least a year.
•	To become a contributor in BentoML, someone must have contributed above a certain level of expectation and must be of good health condition, and then be nominated by the core team members. In FluxML, however, to become a contributor, all you need is consistency for at least a year then be nominated and asked to indicate whether you're willing to serve.
•	The benevolent dictator, known as the BDFL (Benevolent Dictator for Life) in BentoML, has the authority to make final project decisions. The BDFL is only used when the community and the core team disagree on a decision. In FluxML, BDFL is also known as an Advisory Committee, and it works to ensure the project's long-term survivability. They are used by the council to break up disputes or major misunderstandings that might happen among them.
•	In BentoML, decision-making is based on a Lazy Consensus policy. A policy that allows any community member to propose an idea and if no one expressly objects to the idea, the community recognizes and supports it. And it takes 72 hours after the idea has been made with no opposition for the lazy consensus policy to be effective. Meanwhile, the steering council makes practically all the decisions in FluxML.

SIMILARITIES
•	Both projects have a distinct mission, which is stated clearly in their separate governance models.
•	They also address conflicts of interest in like manner; members are advised to report any conflict of interest with other community members.
•	They both use Voting systems and discussion to address conflicts of interest. 

MY OPINION:
I think the BentoML model is more improved than that of FluxML because Decision making in FluxML is power autonomous to the steering committee and the model is not well detailed, unlike BentoML which stated, well-detailed roles and responsibilities, the contribution processes and its guide which make it very easy to understand.

**Comment by oluwaseun-tech** [comment]
CC @arliss-NF, Here is my second contribution ma'am, what do you think?

**Comment by arliss-NF** [comment]
@oluwaseun-tech - great analysis.  Very thorough.  It is important to be able to make and share an opinion when doing analysis projects, and you have done this.  Suggestion:  start to include bolding and indentation in your writing to make it easy to read and highlight key points.  Well done.

**Comment by oluwaseun-tech** [comment]
Thank you, mentor Arliss. I've made a note of it and will take it into account. This is a great learning experience and platform I do not take for granted. Thank you so much
