### ISSUE TITLE
Second Contribution by Riya Sharma 

### ISSUE THREAD

**Issue by Riya2909** [numfocus/outreachy-contributions-2023#75]
**Name:** Riya Sharma 
**Project Analyzed:** [ESLint](https://eslint.org/) | [QuTip](https://qutip.org/)
**Link to the ESLint Governance Model:** https://eslint.org/docs/latest/contribute/governance
**Link to the QuTip Governance Model:** https://github.com/qutip/governance/blob/main/governance.md

I have chosen QuTip and ESLint open source projects to draw a comparative analysis between their governance models. 

### ESLint
ESLint is an open-source project which finds and fixes bugs in a JavaScript code. As an open-source project, ESLint relies on community contributions. Anyone can contribute at any moment by sending code, taking part in conversations, offering comments, or making any other kind of contribution they deem appropriate.
### QuTip
QuTiP, the Quantum Toolbox in Python, is an open-source software to study and simulate quantum systems. It includes tools for defining and simulating the dynamics of quantum systems, as well as for developing an intuitive understanding of quantum mechanics. Aside from the educational aspect, in which QuTiP can be used to visualize and simulate simple quantum systems, advanced functionalities exist that enable cutting-edge research in open quantum systems using QuTiP. It provides the most complete toolbox for characterizing noise and dissipation in quantum systems, as well as quantum information processing features.

### Project Overview
From above, it can be noted that both the communities are well established in the open source . Although QuTip and ESLint are open-source projects, their governance model differs in many aspects.

### Differences 

1.  In ESLint , the authority of final decision making and nominations resides with **Technical Steering Committee (TSC)** whereas in QuTip none have the ultimate power of autonomy.
2.  ESLint community follows the **consensus seeking decision making approach**. It is a type of formal decision making accompanied with a fallback voting procedure. If the consensus is unattainable then fallback voting process is characterized by high number of votes with the idea that this approximates decision by consensus. In case of QuTip , it uses the **Voting System** for its decision-making. This ensures fair decision making.
3. There are **six project roles** present in the ESLint whereas there are **four distinct project roles** in QuTip.
4. The **Board members** are responsible for making final decision making in QuTip. While **Technical Steering Committee (TSC)** look after the working of the projects within the community. They are also responsible for making the final decisions.
5. Communication Channels: QuTip uses **GitHub** as a communication channel to disseminate information among its members . While ESLint makes use of communication channels such as **Discord** and **GitHub**.
6. The **Board Members in QuTip meet** **once a year** to review project development, while the **Technical Steering Team of ESLint** meets on a **weekly** basis for the project development. 

### Similarities

1. Both QuTip and ESLint have a **Code of Conduct** that adheres the members altogether and necessitates them to respect one another.
2. Both the open source projects are **community-driven**. It works on community contributions for enhancement and working of the project.
3. Both the communities follow **hierarchical structure** organizing its employees according to specific project roles and responsibilities. This minimizes **role confusion** which helps in smooth running of the organizations without conflicts.

### MY OPINION
After presenting the comparative study , I believe that the governance model of QuTip is better than ESLint as it follows a fair voting system and no one has the power of autonomy to make decisions. The decision making model of ESLint uses consensus seeking approach in which the opinions of the group formulating the majority overpowers the minority. This leads to neglection of the opinions of the people formulating the minority. Unlike QuTip where each member has a fair chance of participating in the decision making via voting system.

**Comment by Riya2909** [comment]
@arliss-NF

**Comment by arliss-NF** [comment]
@Riya2909 - great analysis - I liked very much how you used bolding to highlight the key points.  This is a great technique, as I used it to read through the analysis quickly and could understand your thought process.  Also, very glad you chose one over the other.  It's important to be able to have an opinion long with the analysis to back it up.  Good work.
