### ISSUE TITLE
 Second contribution by CHIDIOGOR AKUPUE

### ISSUE THREAD

**Issue by akupueerica** [numfocus/outreachy-contributions-2023#76]
My name is Chidiogor Akupue
Project Name: BQplot / CVXPY
Governance Model of BQplot-(https://github.com/bqplot/governance/blob/master/governance.md)
Governance Model of CVXPY: https://github.com/cvxpy/org/blob/main/governance.md

**Comparative analysis of BQplot and CVXPY governance models**

BQplot is an open-source software project for exploratory and interactive data visualization and the CVXPY is an open-source software project which provides a domain-specific language for convex optimization in the Python programming language. 
The governance model of the BQplot project is built on the sole leadership of substantial (in quality and quantity) project contributors who make up a steering council with no stated quorum while the CVXPY project governance model has a three-tier leadership structure starting with a Benevolent Dictator for Life (BDFL) then, Project Maintainers and Steering Committee, both with a quorum of five members each. 

The steering council of the BQplot undertakes all leadership responsibilities for the project and may delegate some of the said responsibilities to other Project Contributors or committees (not specified) while the CVXPY governance model describes succinct responsibilities for each of the three active roles. Decision-making processes in CVXPY require a vote of majority approval by steering committee members on financial matters or a consensus by project maintainers on non-financial matters with the BDFL making a final decision in an event that consensus on a non-financial decision cannot be achieved while all BQplot major project decisions are made by the steering council after a vote.   
 
The steering council of BQplot has monthly meetings, 3/4 of which Council Members are required to attend while the steering committee of CVXPY has biannual meetings, both to discuss project-related matters. Both projects handle conflict-of-interest issues similarly and have a spelled-out, Code of Conduct that community members have to abide by. Also, both projects have eligibility rules to onboard new members into their various leadership roles.

Both projects’ governance models have some pitfalls which make neither, better than the other. The CVXPY governance document provides no explicit funding mechanism for the project or specified term of service for steering committee members and project maintainers while this was stated in the BQplot governance model; a two-year term for council members with institutions, being the primary funding mechanism for the project. The BQplot governance model makes that all leadership responsibilities be assumed by the steering council unless they decide to delegate them, in contrast, the CVXPY governance model shared these responsibilities among the three active roles, which may be a more effective approach. While the BDFL governance model in CVXPY gives room for abuse of power which could adversely affect the project, the BQplot governance model provides that all major decisions can only be made after a majority vote by steering council members.

**Comment by akupueerica** [comment]
Hello @arliss-NF please review and would appreciate any feedback

**Comment by arliss-NF** [comment]
Hi @akupueerica - great analysis.  Really enjoyed reading it.  Your writing is very clear, and your comparisons are well constructed.
