### ISSUE TITLE
First Contribution by Khadija

### ISSUE THREAD

**Issue by Khadija411** [numfocus/outreachy-contributions-2023#77]
Name:  Khadija
Project:  bqplot
Governance model:  [https://github.com/bqplot/governance/blob/master/governance.md](url)

Bqplot is an open-source project, and as such, it has a community-driven governance model. The project is hosted on GitHub, and anyone can contribute to the project by submitting pull requests, reporting issues, or participating in discussions on the project's issue tracker. The core team of Bqplot is responsible for maintaining the project, reviewing contributions, and making decisions about the direction of the project. The core team consists of experienced contributors who have demonstrated their expertise and commitment to the project over time. The project has a well-defined code of conduct, which outlines the expected behavior of contributors and users of the project. The code of conduct is enforced by the core team, who are responsible for resolving any disputes or issues that arise.

Therefore the foundations of Project governance are:
- Openness & Transparency
- Active Contribution
- Institutional Neutrality
The Project leadership consists of a Steering Council.

The main project roles in the Bqplot project are:
- Core Contributors
- Contributors
- Maintainers
- Users
Additionally, the Bqplot project has a Steering Committee made up of core contributors.

The Bqplot project follows a consensus-based decision-making process, where decisions are made through discussion and collaboration among the project's contributors and maintainers. The goal of this process is to ensure that decisions are made in a transparent and inclusive manner, with input from all stakeholders.

Specifically, the decision-making process in the Bqplot project involves the following steps:
- Discussion.
- Consensus.
- Voting.
- Implementation. 
It's worth noting that the decision-making process may vary depending on the nature and scope of the issue at hand.

The governance model for the Bqplot project is easy to find. The project's governance model is documented in a file named "GOVERNANCE.md", which can be found on the project's GitHub page. The file provides a detailed overview of the project's governance structure, including the roles and responsibilities of project contributors, decision-making processes, and conflict resolution mechanisms. The file is well-organized and easy to navigate, making it easy to find the information you need about the project's governance model.

**Comment by Khadija411** [comment]
@arliss-NF

**Comment by maryamgbemisola** [comment]
It is better to give your full name as we may have one than one Khadija here

**Comment by arliss-NF** [comment]
@Khadija411 - good work.  This task seems to have been an easy one, but I hope you learned a bit about governance models.  Often the model is found in a file with the name you gave, but it can be buried deep in a GitHub repo.  It should be as easy to find the governance model for all open-source projects ... often it is not.
