### ISSUE TITLE
Second Contribution by Kehinde Adebisi

### ISSUE THREAD

**Issue by Kehindeadebisi** [numfocus/outreachy-contributions-2023#79]
### Links
**Project Links:** 
[CVXPY](https://github.com/cvxpy/org/blob/main/governance.md) | [BentoML](https://github.com/bentoml/BentoML/blob/main/GOVERNANCE.md)

**Resources:**
https://www.redhat.com/en/blog/understanding-open-source-governance-models 
http://oss-watch.ac.uk/resources/meritocraticgovernancemodel

### Similarities
Both models uphold the fundamentals of open source with respect to transparency, contribution, and active participation from members. Both encourage code sharing, involvement, and communication through community channels. 
The decision-making process of both communities involves consensus, voting, and sometimes the Benevolent Dictator for Life  (BDFL), although with varying degrees of influence and authority. When a conflict of interest occurs, both projects allow members involved in the conflict to participate in discussions regarding the issue but are exempted from voting or decision-making.

### Differences
CVXPY combines the Founder-Leader and Self-Appointing governance models, while BentoML adopts Meritocracy; a model that decentralizes decision-making whereby authority is earned through contributions rather than a top-down, approach. In contrast to CVXPY where decisions making capacity is accorded by roles, split into financial and non-financial decisions, and leadership groups are appointed to govern different aspects of the project with the BDFL making the final decision, anyone who contributes to BentoML can participate in the decision-making process. 
BentoML adopts a lazy consensus approach through proposals, discussions, then voting if there are objections to the proposal or an inability to reach a consensus. The majority of decisions are made without voting. CVXPY, however, makes decisions using developer calls. Also, in BentoML members in roles such as the core team and BDFL, do not have significant authority over the contributors, except in cases where consensus is not reached by the community.

### Which is Better?
Considering the ideals of open source which reinforces community participation and inclusiveness, the BentoML’s governance model is better as the CVXPY’s models might hinder While meritocracy may have its downside such as biases, it ensures that the focus of contributions is on the idea itself rather than the role of the person proposing it which gives room for more robust development. Also, while both models are clear, concise, and relatively easy to find, the BentoML model is more explicit in stating how potential contributors can engage with the project and clearly communicates its policies, guidelines, as well as conduct. Additionally, it includes links to open community channels and mailing lists that do not involve role assignments such that a new contributor can easily get started. This inspires an immediate connection with the community, giving an impression of a community that is ‘open’ in the real sense.

**Comment by Kehindeadebisi** [comment]
@arliss-NF Please give feedback, thank you

**Comment by arliss-NF** [comment]
@Kehindeadebisi - great work, good analysis.  Your argument for which is better is solid.  Well done.

**Comment by Kehindeadebisi** [comment]
Thank you so much for the feedback @arliss-NF
