### ISSUE TITLE
First Contribution by Ewete Esther 

### ISSUE THREAD

**Issue by Abosed** [numfocus/outreachy-contributions-2023#8]
Name: Ewete Esther

Project Assigned: Signac

Link to Signac Governance Model: https://signac.io/governance/

**Signac Governance Model:**

The Signac governance model describes how participation takes place, what roles community members may be able to fill and the responsibilities and privileges these roles entail. There is no expectation of long-term commitment to the project, no specific skill requirements, and no selection process, however all contributors must abide by the project’s [Code of Conduct] (https://www.signac.io/conduct/) and each repository’s respective contributing guidelines. All committers are expected to be aware of the project's overall strategic development, for example, by participating in Slack or [Gitter channels] (https://gitter.im/signac/Lobby) and/or attending semi-regular development meetings. Potential committers must also have the technical proficiency required to assess code submissions, as well as a thorough comprehension of an agreement with the project's goals and strategy. It is expected that all project maintainers will participate in discussions and vote on whether to accept or reject committer and project maintainer nominations.

**Project Roles:** 

The Signac governance model has a diverse group of roles that are essential for the success of the project. Each role has a specific set of responsibilities that contribute to the overall success of the project. They Include:

1. Users
2. Contributors
3. Committers
4. Project Maintainers
5. Administrators
6. Project Managers

**The Decision-Making Process:** 

The Signac project aims to create a strong and sustainable governance structure that reflects its members' needs and values. The decision-making process are:

1.The existing project maintainers must vote by two-thirds to approve new project maintainers.

2. If necessary, a project maintainer may also be dismissed from their position by the other project leads with a two-thirds vote.

3. By a majority vote, the project maintainers will decide whether to accept or reject the nomination.

4. The committer role may be revoked by the project maintainers by majority vote if necessary, such as after a prolonged period of inactivity.

**How easy or difficult it was to find and understand the governance model:**

I found the  governance model relatively easy to understand and work with.

**Comment by Abosed** [comment]
cc @arliss-NF 

The project topic sparked my curiosity. I look forward to hearing your personal opinions on my contribution.

**Comment by Chimnwendum** [comment]
Hello Esther, remember in the Contribution task, under the 'Roles' we were asked to list them. 

It says: 
Any project roles (just the names are fine)

**Comment by Abosed** [comment]
> Hello Esther, remember in the Contribution task, under the 'Roles' we were asked to list them.
> 
> It says: Any project roles (just the names are fine)

Hello Chinm,thank you.will edit it.
thank you.

**Comment by arliss-NF** [comment]
Hi  @Abosed - great first contribution. I really appreciate your response to feedback from a community member. Being able to respond positively to feedback is important in open-source communities.
One quick fix - the link to the governance model doesn't get me to signac's model.  Could you update that and ping me again, please?  
Great work - looking forward to your second contribution.

**Comment by Abosed** [comment]
Hello Arliss,

Trust you're doing great.

Thanks for the feedback.

Will update the link.

**Comment by Abosed** [comment]
@arliss-NF 

Link updated.

**Comment by arliss-NF** [comment]
Thanks @Abosed for responding so quickly.

**Comment by Abosed** [comment]
Hello Arliss,

Trust you are doing great.

Can i go ahead and record my contribution on outreachy?
