### ISSUE TITLE
Second Contribution by Bazgha Razi

### ISSUE THREAD

**Issue by Bazgha19** [numfocus/outreachy-contributions-2023#83]
**Name:** Bazgha Razi
**Projects:** [BentoML](https://www.bentoml.com/) | [CVXPY](https://www.cvxpy.org/)
**Project 1 Governance Model:** [BentoML Governance Model](https://github.com/bentoml/BentoML/blob/main/GOVERNANCE.md)
**Project 2 Governance Model:** [CVXPY Governance Model](https://github.com/cvxpy/org/blob/main/governance.md)

_- BentoML help us to deploy ML models in an easy way. It provides machine learning services to our model._
_- CVXPY is a python embedded modeling language for convex optimization problems._

**Project Roles:**

Benevolent Dictator : _In CVXPY [Steven Diamond](https://stevendiamond.me/) holds the title of BDFL(Benevolent Dictator for Life). Both (BentoML and CVXPY) have one BDFL._

Project Maintainers: They lead the technical development of CVXPY project. But in BentoML we have core team.

Emeritus Project Maintainers: _These have less roles and powers as compare to project maintainers. In BentoML we have contributors which have less power as compare to core team._

Steering Committee: _It supports project maintainers. It represent all administrative and legal capacities of CVXPY. It also approves expenditure. But in BentoML we have conflict of interest in which members with a conflict of interest in a particular issue may participate in Core Team discussions on that issue, but must recuse themselves from voting on the issue._
 
**Decision Making Process:**

Financial Decisions: _These decisions are made by steering committee._

Non financial Decisions: _These decisions are made by consensus of the project maintainers._

Conflict of Interest: _All members with a conflict of interest in a particular issue may participate in Steering Committee discussions on that issue._

**Similarities of Project**

_- It is easy to find and understand the governance model for both the projects._
_- Both have one BDFL (Benevolent Dictator For Life)._
_- Both have conflicts of interest to solve the conflicts occur during the work._
_- Both recuse themselves from voting on the issue._

**Differences of Project**
|Differences | BentoML | CVXPY |
| --------- | ------- | --------|
| Aim of the project | _It  help us to deploy ML models in an easy way. It provide ML services for our model._ | _It is to improve the accessibility and expand the scopes of third-party convex optimization solvers._ |
| BDFL (Benevolent Dictator For Life) | _Chaoyu Yang_ | _Steven Diamond_  |
| Manages the decisions of project  | _Core Team_  |  _Project Maintainers_ |
| Where to ask about help? | _[BentoML Contibutor Mailing List](https://groups.google.com/forum/#!forum/bentoml)_ | _[CVXPY Google Group](https://groups.google.com/g/cvxpy) or [Github Discussion within the CVXPY repository](https://github.com/cvxpy/cvxpy/discussions)_ |

**Which is better according to me?**

_In my view, both have different aims and working. According to our priorities, we'll use the project and its benefits as much as possible. If we want ML services for our model we'll use BentoML and if we need to improve the accessibility and expand the scopes of third-party convex optimization solvers we use CVXPY._

**Comment by Bazgha19** [comment]
cc @arliss-NF

**Comment by arliss-NF** [comment]
@Bazgha19 - great work.  I like how you presented the information in your differences section.  Tables are a great way to summarize information and are helpful in explaining complex concepts.  Kudos!
Agree with your summary, "one size fits all" does not work.  Governance needs to be tailored to the project needs.
