### ISSUE TITLE
SECOND CONTRIBUTION BY QUEENETH OGBONNA

### ISSUE THREAD

**Issue by kwin-eth** [numfocus/outreachy-contributions-2023#88]
**Name: Queeneth Ogbonna
Project: QuTip | CVXPY 
  [Link To QuTip Governance Model](https://github.com/qutip/governance/blob/main/governance.md)
 [Link To CVXPY Governance Model](https://github.com/cvxpy/org/blob/main/governance.md)**

**INTRODUCTION**

CVXPY is an open-source optimization modeling language that provides a convenient and intuitive way to formulate and solve convex optimization problems.
QuTiP, an open-source software package written in Python, provides users with a variety of tools to learn and simulate quantum systems.

Open-source governance models have become increasingly important in the software development industry, as they can significantly impact the success and sustainability of a project. In this essay, we will conduct a comparative analysis of two open-source projects: CVXPY and QuTiP. The purpose of this analysis is to explore the governance models of these projects and how they prioritize ethics, integrity, and responsible conduct among their leaders, volunteers, and workers. We will examine factors such as transparency, collaboration, accountability, and leadership to evaluate the effectiveness of their governance models.

**SIMILARITIES**

- CVXPY and QuTiP projects have permissive open-source software licenses that permit code modification and commercial use. Their packages are widely used by researchers and professionals around the world to view, modify and distribute.
 
- CVXPY and QuTiP have a high level of transparency in their governance models. They have a well-documented contributor code of conduct. The project's website provides information on how to contribute, how decisions are made, and how the project is funded.
  
-  CVXPY and QuTiP projects emphasize collaboration between contributors and maintainers. They have a large and vibrant community of contributors 

 

**DIFFERENCES**

- A formal governance structure exists for CVXPY. The governance model for CVXPY is primarily led by its creator, Professor Stephen Boyd, who is the Benevolent Dictator for Life.   In contrast, the governance model of QuTiP has a more Democratic Approach.
     
- CVXPY's project steering committee comprises academic and industry representatives, while  QuTiP's development is coordinated by a core team of developers who are not affiliated with a single institution.
 
- The decision-making process in CVXPY is more hierarchical and based on technical merit, whereas the decision-making process in QuTiP is more community-driven and based on consensus. Furthermore, QuTiP has a formal voting process while CVXPY does not.

 
 

**CONCLUSION**

After evaluating all factors, I am inclined to choose the governance model of QuTiP over CVXPY. While both projects have strong governance models, QuTiP's deliberate consideration for the community stands out. QuTiP's governance model fosters a welcoming and growth-conducive environment, which aligns with our goals for this analysis.

**Comment by kwin-eth** [comment]
SECOND TASK COMPLETED @arliss-NF

**Comment by arliss-NF** [comment]
@kwin-eth - strong analysis.  I liked how you said, " I'm inclined to ..".  When doing analysis, it's important to have an opinion and make a decision, so getting comfortable with doing this is important.  This is done by providing a strong, clear, concise argument backed up with data. You have done this.
