### ISSUE TITLE
Second Contribution by Pamela Ropafadzo Pfunye

### ISSUE THREAD

**Issue by PamelaRopafadzo** [numfocus/outreachy-contributions-2023#89]
**Name:** Pamela Ropafadzo Pfunye

**The projects you analyzed** : [InterpretML](https://pytorch.org/)| [PyTorch
](https://interpret.ml/) 
**Links:**

_Pytorch:_

 https://pytorch.org/docs/master/community/governance.html
https://ai.facebook.com/blog/pytorch-foundation/

_InterpretML:_ 

https://github.com/interpretml/interpret/blob/develop/GOVERNANCE.md
https://github.com/interpretml/governance/blob/master/org-governance.md
https://github.com/interpretml/governance

PyTorch and InterpretML are two popular open-source frameworks that offer tools to make it easier to create and train machine learning models.

**SIMILARITIES**

- **Ownership:** Facebook owns PyTorch, while Microsoft owns InterpretML. The fact that these businesses own the libraries does not imply that they have influence over how the software is developed. To guarantee that the libraries are created and maintained in a sustainable way, they instead give resources and assistance to the development teams. 
- **Governance body:** Determines the project's course, evaluates and accepts community contributions, and monitors the library's security and quality. PyTorch has a Technical Steering Committee, whereas InterpretML has a Core development team
- **Development processes:** all code modifications, problem complaints, and feature requests are accessible to everyone on GitHub. Regular community meetings are held at both libraries to talk about the project's direction and solicit user feedback

The libraries similarities demonstrate their commitment to openness, transparency, and community involvement, which are essential principles for the development of open-source software and sustainability.

**DIFFERENCES**

- **Governance structures:** InterpretML has a more centralized governance structure, with decisions about the direction of the library being made by a small group of developers responsible for the core components of the library. In contrast, PyTorch has a more decentralized governance structure, with the PyTorch Technical Steering Committee providing oversight and guidance but leaving many decisions to the community of contributors and users.
- **Development Process:** InterpretML has a more structured and formalized development process, while PyTorch has a more informal development process. InterpretML places more emphasis on formal review processes and clear guidelines for contributions, while PyTorch places more emphasis on community involvement and collaboration.
- **Community Involvement:** PyTorch has a larger and more active community of users and contributors than InterpretML. This reflects the fact that PyTorch is a more general-purpose library with a wider range of use cases and applications, while InterpretML is a more specialized library focused on interpretability for machine learning models.

**MY OPINION**

Both governance models are successful and I believe the best model will depend on the size, scope, and goals of the project, as well as the culture and values of the community involved. InterpretML's more centralized governance structure may be more effective for a smaller and more specialized library focused on interpretability for machine learning models, while PyTorch's more decentralized governance structure may be more effective for a larger and more general-purpose library that provides tools for building and training deep neural networks.

**Comment by PamelaRopafadzo** [comment]
@arliss-NF Looking forward to hearing your thoughts on my second contribution

**Comment by arliss-NF** [comment]
@PamelaRopafadzo - excellent work.  Very well-organized and easy to read.  good level of content and use of bolding and indentation.  Very easy to read and is invaluable when one needs to review a lot of content.  Thank you.
Your "My Opinion" section is well written, and it's important to decide which one you prefer when you have a strong analysis to back up the decision.  Well done.
