### ISSUE TITLE
First Contribution by Diana OFODU

### ISSUE THREAD

**Issue by Diana-Ofodu** [numfocus/outreachy-contributions-2023#9]
**Name:** Diana OFODU (she/her)
**Project:** The Carpentries (https://carpentries.org/)
**Link to The Carpentries governance model:** https://carpentries.org/governance/

The governance model of The Carpentries consists of rules set by the executive council. The council is responsible for determining the organization's mission, maintaining and updating bylaws, selecting and evaluating the executive director, strategic planning, financial management, identifying revenue streams, program approval, public image enhancement, and self-assessment. The executive director serves as the Chief Executive Officer and their actions are overseen by the executive council.

The executive council is made up of nine members; four of whom are elected by the community members (community-elected members) and five are elected by the executive council (council-elected members). Though they strive for transparency in their activities, some things are still kept to themselves.

**Project roles**
There are three major project roles:
- Instructor
- Trainer
- Maintainer

In addition to the formal roles, there are different committees which make up of the executive council members in charge of various operations, for example:
- Officers Committee
- Governance Committee
- Finance Committee
- Program Committee

**Decision-making process**
Voting is done yearly and the Executive Director is exempted from it. There are four sets of people who are eligible to vote. These individuals are considered active in the community. They include those who completed an Instructor or Trainer certification within the past year, those who completed it within the last two years and have taught at least one Carpentries workshop, those who are certified instructors or trainers and have taught at least two Carpentries workshops in the past two years and those who have participated in a committee as a mentor or maintainer in the past year.

To approve an appointment or removal of any party, a majority of votes by the executive council is required.

**How easy or difficult was it to find and understand the governance model?**
It was not difficult for me to find the governance model as there was a button that clearly stated what I was looking for. The amazing thing was that I was going down a rabbit hole of information just like I usually do when I start binge-watching videos on YouTube. I understood it pretty well although it was my first experience with governance models and was not sure if I was getting the correct information.

**Comment by Diana-Ofodu** [comment]
@arliss-NF what do you think about this? Kindly share your thoughts and anyway I can improve.

**Comment by arliss-NF** [comment]
@Diana-Ofodu - this first contribution is great.  While this project was relatively easy, they have a very well-defined model and they do a good job of providing ways for community members to engage.  This is a good example of a governance model.  Thank you for summarizing in your own words and adhering to the guidelines. I'm really looking forward to your second contribution.
