### ISSUE TITLE
Second contribution by Desire Oluwarotimi.

### ISSUE THREAD

**Issue by RotimiDesire** [numfocus/outreachy-contributions-2023#91]
NUMFOCUS 2

NAME :- Desire Oluwarotimi
PROJECTS ANALYZED :- PYTORCH & OPENJS

**RELEVANT LINKS.**

PyTorch’s website:-  https://pytorch.org/
PyTorch’s governance model:-  https://pytorch.org/docs/stable/community/governance.html
OpenJS’ website:-  https://openjsf.org/
OpenJS’ governance model:-  https://openjsf.org/about/governance/

**A COMPARATIVE ANALYSIS OF THE GOVERNANCE MODELS OF PYTORCH AND OPENJS.**

**Projects’ overview**

PyTorch is an open source machine learning library for Python that is majorly used for the development of deep learning models. Some special characteristics of PyTorch include its dynamic computation graph, its support for GPU acceleration and its extensive set of libraries and mechanisms for tasks.

OpenJS is a non-profit organization that aims at backing the JavaScript community by promoting the growth and development of open source JavaScript projects. The long term goal is to enhance the adoption of JavaScript and its technologies by providing a neutral forum that encourages collaboration, education and community establishment.

**Similarities in governance models**

* Transparency is a key attribute that was emphasized in the governance models of both projects and this is made possible with the availability of public forums and documentations to every individual associated to their projects.
* Community involvement is encouraged by both projects with channels for communication and contribution giving a fair opportunity for everyone to participate in the process of hitting the projects’ goals and targets.
* Both governance models showed the delegation of duties to specific working groups while also highlighting that each working groups are responsible for specific areas of the project.
* The governance models of both projects lay emphasis on the importance of respectful and inclusive behaviour within their communities.
                                    

**Differences in governance models.**

* PyTorch has a Technical Steering Committee (TSC) constituted with members elected by the community. OpenJS instead has a Board of Directors that constitutes individuals from different organizations. The Board of Directors is supported by a Cross Project Council (CPC) that is responsible for implementing the technical policies and procedures set by the Board.
* PyTorch is a single project with a single governance model but the OpenJS supports a set of projects each with its own governance model.
* OpenJS has a membership structure with various member companies but PyTorch does not have a formal membership structure instead it does have a community of contributors who participate in discussions and contribute code.

**My Opinion on the better model**

I’d pick the PyTorch governance model as the better model. This is majorly because of its openness to random individuals and their involvement in the decision making process. Decisions are made collectively by the PyTorch developers and the community unlike OpenJS that conducts a centralised consensus-based decision-making process.

**Comment by RotimiDesire** [comment]
@arliss-NF This is my second contribution. Kindly review. Thanks.

**Comment by arliss-NF** [comment]
@RotimiDesire - well done - good analysis.  You have highlighted the key aspects that should be discussed around these models.  I appreciate that you made a decision on which is better 'in your opinion" because in doing analysis work, you are often asked to make these types of decisions based on the information you've gathered.  Keep up the good work.

**Comment by RotimiDesire** [comment]
@arliss-NF Thank you for the review.
