### ISSUE TITLE
First Contribution by Tanishka Goel

### ISSUE THREAD

**Issue by tg-100** [numfocus/outreachy-contributions-2023#96]
**Name:** Tanishka Goel
**Project Name:** [signac](https://signac.io/)
**Link to Project Governance Model:** [https://signac.io/governance/](url)

## What is signac?
The signac is a framework that helps researchers manage their project data with a well-defined, indexable storage layout for their data and metadata. It streamlines the post-processing and analysis, making data collectively accessible.

## Governance Model
The governance model of this project is a derivative of the **Meritocratic Governance Model** and has the following features: **_Consensus-based, inclusive, and open to all (community-based)_**.

- **_The project is open source_** and is managed and sustained by people who have an interest in the project and are willing to be a part of it whether by using the framework, contributing to the development and upgradation of the project, or managing the project community.
- It **_has various specified project roles_**, _**each with a**_ **_different responsibility_**. A community member can identify with a specific role (as a user or project manager) based on their technical abilities, experience with the project, and commitment to the project.
- It **_has consensus-based decision-making, achieved with inclusive majority voting_**.  The decisions are required for progressing roles in the community and managing the future workflow of the project. These are made by the voters considering the involvement of the member, responsibilities, and the accomplishments of their current role; deemed suitable or unsuitable for future role or involvement.

## Project Roles

- ### Users
    - ### Contributors
    - ### Committers
    - ### Project Maintainers
    - ### Administrators
- ### Project Managers
   - ### Triage Manager
   - ### Community Manager

## Decision-Making
**Voting Process:** The decision-making for different roles is done through majority voting or 2/3rd voting based on the project role of the member. The following description explains how members are chosen for the roles below and how the decisions are made for those roles.
- **Committers:** (Technical expertise and a high level of understanding of the project strategy and alignment towards its objectives is required) Members apply for this role by self-nomination. The project maintainers may accept or reject the nomination by majority vote. The project maintainers may also revoke a committer by majority vote if warranted (e.g. due to long inactivity).
- **Project Maintainers:** (Exceptional commitment to the signac project and overall strong understanding of project strategy is required) Project maintainers are chosen by existing maintainers by 2/3rd votes. The maintainer may also be removed by 2/3rd votes if required.
- **Project Managers:** Managers are selected by rotation from a pool of project maintainers or volunteer project committers (all committers are allowed for a triage manager position). They are selected periodically in the alphabetic order of their last name.

## How easy/difficult was the governance model to find and understand for me?
The governance model was easy to locate on the website. It was also easy to understand, given that I had a little idea about the open-source terms being used and have considerable fluency in the English language. I think people who are completely new to open-source or do not have fluency in English may find it a bit difficult to get through. But, beginners to open-source who are at least familiar with the terminology would easily grasp the model.

**Overall level:** Moderate (for understanding), Very Easy (to find)

**Comment by tg-100** [comment]
@arliss-NF Please have a look at it. I will be glad to have your suggestions. :)
Thank you!

**Comment by Chimnwendum** [comment]
Hello Tanishka, under the roles, we were asked to list them out. 

So you don't need to explain what they do, all you have to do is list them out.

**Comment by tg-100** [comment]
@Chimnwendum Hello, thank you for your suggestion! I'll edit it :)

**Comment by arliss-NF** [comment]
@tg-100 - great first task.  I appreciate how you responded to feedback from the community. 💯

**Comment by tg-100** [comment]
@arliss-NF Thank you so much!
